### ISSUE TITLE
Satis does not appear to recognise branch-alias syntax

### ISSUE THREAD

**Issue by parsingphase** [composer/satis#100]
As per https://igor.io/2013/01/07/composer-versioning.html I have a module with a tagged dev alias:

```
    "extra": {
        "branch-alias": {
            "dev-master": "0.3.x-dev"
        }
    }
```

My satis install (self-rebuilding from dev-master) does not list 0.3.x as an installable version in the HTML interface, but copies the above stanza to packages.json, meaning that the stanza:
```
"require": {
    "acme/devtools": "0.3.x-dev"
}
```
can be honoured by composer (ie, installation works), despite there being no 0.3.x named branch.

It would be ideal if satis could recognise this syntax and thereby list all installable versions in the human-readable interface.

**Comment by marcovtwout** [comment]
Composer install is working fine, but the aliases are indeed missing from the generated Satis output. Could these be added, maybe similar to how Packagist displays them?

**Comment by alcohol** [comment]
Closing, please re-open if this is still a concern.
