### ISSUE TITLE
Error when mirroring a "type: metapackage"

### ISSUE THREAD

**Issue by h4cc** [composer/satis#119]
My satis build failed with this message

```
Dumping 'h4cc/phpqatools-1.0.0.0'.
PHP Fatal error:  Call to a member function download() on a non-object in phar:///home/satis/satis.phar/vendor/composer/composer/src/Composer/Downloader/DownloadManager.php on line 182
```

The mentioned line is here:
https://github.com/composer/composer/blob/master/src/Composer/Downloader/DownloadManager.php#L182

and the what is causing the error is this:
https://github.com/composer/composer/blob/master/src/Composer/Downloader/DownloadManager.php#L133

**Comment by alcohol** [comment]
Closing, please re-open if this is still a concern.
