### ISSUE TITLE
Satis and http://user:pass@host

### ISSUE THREAD

**Issue by huglester** [composer/satis#127]
Hello,

I have private repos, I need to scan them to build packages.json for satis usage.
With ssh option - it all worked, but setting up ssh keys can be tricky on windows etc etc...
so I decided to switch to http mode.

but with http mode stis builds packages.json file containing username and pass in URL, so everyone can freely download the packages without entering username/pass.

is there a way around it? like pass username/pass via:
export SATIS_HTTP_USERNAME='user'
export SATIS_HTTP_PASSWORD='pass'

thank you!

**Comment by mitch10593** [comment]
I have tried this solution, and it works for me:
  { "type": "vcs", "url": "svn://mysvnuser:mysvnpassword@svnhost.net/SvnProjectName" },

**Comment by alcohol** [comment]
Closing, please re-open if this is still a concern.
