### ISSUE TITLE
include directory filling up with json files

### ISSUE THREAD

**Issue by Burgov** [composer/satis#141]
We upgraded to the latest version some hours ago, and since then a include directory appeared which is filling up with files quite rapidly. Within 2 hours it grew to 2MB already. Is this intentional behaviour? Is this directory to be kept clean manually or am I missing something here?

**Comment by mbrodala** [comment]
If you do this, you might want to keep the exiting `dist` directory, otherwise Satis must download and package all releases of all packages over and over again.

**Comment by alcohol** [comment]
Closing, please re-open if this is still a concern.
