### ISSUE TITLE
Satis build failed. Authentication failed. Satis not asking for username and password anymore

### ISSUE THREAD

**Issue by ali-irawan** [composer/satis#150]
I'm using Satis.
At first I build my own private repo using

php bin/satir build satir.json web/

and it asking for username and password, the build succeed.

But I don't know why satis does not ask for username and password any more ?

It shown error as:
[RuntimeException]                                                                                             
  Failed to clone https://myprivaterepo, could not read packages from it  
                                                                                                                 
  fatal: Authentication failed   

How I force Satis to ask for username and password.
I'm using Linux.

**Comment by arielcalcano** [comment]
Just update the satis vcs repositories credentials, stored at: ~/.composer/cache/vcs/satisRepo.git

**Comment by alcohol** [comment]
Closing, please re-open if this is still a concern.
