### ISSUE TITLE
Bug: jsonfile write method does not handle unicode characters gracefully

### ISSUE THREAD

**Issue by chrischnweiss** [composer/satis#156]
Now i open up a new issue for this problem, that i also mentioned in https://github.com/composer/satis/issues/140, because I think it's another problem we speak about.

The build process of satis ran fine and i got this notes as a feedback:
```sh
wrote packages json /satis/web/include/all$adc83b19e793491b1c6ea0fd8b46cd9f32e592fc.json
Writing packages.json
Writing web view
```
The web view works great an my packages are shown there. No problem with that, so I add my new Composer repository to the composer.json of little test-project and fire up:
```sh
composer install
```
There is the trouble. I got this error message back after loading the composer repositories:
```sh

Loading composer repositories with package information

[Seld\JsonLint\ParsingException]
"http://url-to-my-satis-web-interface/include/all$adc83b19e793491b1c6ea0fd8b46cd9f32e592fc.json" does not contain valid JSON
Parse error on line 1:

  ^
 Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['
```
It seems my composer repo is reachable, but the include-file.json is empty.

Have anyone a solution or the same issue?

**Comment by alcohol** [comment]
This seems to work fine in the current state of the codebase. `JsonFile` is part of our `composer/composer` dependency. Probably something that got fixed a long time ago already.
