### ISSUE TITLE
Documentation: Add howto for re-using existing SSH connections

### ISSUE THREAD

**Issue by quafzi** [composer/satis#161]
Satis should not create new connections for every package, but instead re-use existing connections.

(@flyingmana)

**Comment by alcohol** [comment]
This is not a Satis issue really. This is more on a OS level. The same can be applied to Composer actually. Neither of them (Satis/Composer) can really solve this or properly deal with it. A good blog post on the subject could be useful for people interested in this.

Closing, please re-open if this is still a concern.

**Comment by Flyingmana** [comment]
It is still a concern. Satis targets a complete different kind of user then composer and is usually used with enough packages, so a shared connection affects a lot the usability. It can not be expected that users know about this ssh related feature, as it does not give proper improvements for most other usecases with ssh.
