### ISSUE TITLE
version rewrite support

### ISSUE THREAD

**Issue by glensc** [composer/satis#162]
In my repo I have tags formed in a way that satis does not like. I would like to rewrite them somehow to `1.0-1` -> `1.0.0.1`, or just `1.0`

```
$ satis build -v satis.json ./
Scanning packages
Reading composer.json of vendor/urlutil (1.0-1)
<warning>Skipped tag 1.0-1, invalid tag name</warning>
Reading composer.json of vendor/urlutil (1.0-2)
<warning>Skipped tag 1.0-2, invalid tag name</warning>
Reading composer.json of vendor/urlutil (1.0-3)
<warning>Skipped tag 1.0-3, invalid tag name</warning>
Reading composer.json of vendor/urlutil (1.0-4)
<warning>Skipped tag 1.0-4, invalid tag name</warning>
Reading composer.json of vendor/urlutil (1.1-1)
<warning>Skipped tag 1.1-1, invalid tag name</warning>
Reading composer.json of vendor/urlutil (1.10-1)
<warning>Skipped tag 1.10-1, invalid tag name</warning>
Reading composer.json of vendor/urlutil (1.11-1)
<warning>Skipped tag 1.11-1, invalid tag name</warning>
Reading composer.json of vendor/urlutil (1.11-2)
<warning>Skipped tag 1.11-2, invalid tag name</warning>
Reading composer.json of vendor/urlutil (1.11-3)
```

**Comment by alcohol** [comment]
You need to solve that on a repository level, satis simply reads, it does not modify your repositories.

**Comment by glensc** [comment]
i can not solve this on repo level, we have policy of VERSION-RELEASE scheme for tags. that's why the feature request here.

**Comment by alcohol** [comment]
Rewriting your versions is not going to solve anything. Composer will not be able to find them.

**Comment by glensc** [comment]
yes it would, if `1.11-2` is rewritten as `1.11-p2`.

**Comment by alcohol** [comment]
How would Composer install that tag? It does not exist. So no, it would not.

**Comment by glensc** [comment]
eee, what? version and repo url are stored in different properties!

https://github.com/eventum/composer/blob/8e5d19657e4c3fd9163a589e3ae7e9cbf86d7da4/all.json#L4
https://github.com/eventum/composer/blob/8e5d19657e4c3fd9163a589e3ae7e9cbf86d7da4/all.json#L6-L7
https://github.com/eventum/composer/blob/8e5d19657e4c3fd9163a589e3ae7e9cbf86d7da4/all.json#L8-L18

in git case the reference is git hash, in svn case it's revision number!

**Comment by alcohol** [comment]
Le sigh. 

#unsubscribe

**Comment by glensc** [comment]
here's patch that does exactly that:

https://github.com/pld-linux/satis/blob/a923f5293e7aba6e3fa3d0ff3db1f6d2d64a427d/versionparser.patch

and the resulting json looks like this:
```json
        "vendor/di": {
            "3.1.0.73-1": {
                "name": "vendor/di",
                "version": "3.1.0.73-1",
                "version_normalized": "3.1.0.73-patch1",
                "source": {
                    "type": "svn",
                    "url": "svn+ssh://svn.example.org/di",
                    "reference": "/tags/3.1.0.73-1/@79091"
                },
                "dist": {
                    "type": "tar",
                    "url": "https://svn.example.org/dist/vendor-di-3.1.0.73-1-213bc2.tar",
                    "reference": "/tags/3.1.0.73-1/@79091",
                    "shasum": "f11d806489bf59d3025654b48ca1e6c68347608f"
                },
                "time": "2014-08-18 14:45:59",
                "type": "library",
            }
```

**Comment by glensc** [comment]
@Seldaek what's your opinion here? clearly @alcohol doesn't want to do anything, not even understand.

**Comment by JamesRezo** [comment]
@glensc as your patch demonstrates it, this is not a Satis concern, but a composer's one, as it is a version parser tweak.
I'm not @Seldaek nor @alcohol but if my opinion can be considered, I would remind you that Composer follows semver specification as your policy doesn't. I guess Composer can't support all policies that move away from semver as it could become a nightmare in maintenance load terms.
Maybe, but I didn't test it, your tweak could fit in a composer plugin ?

**Comment by Seldaek** [comment]
@glensc I'm sorry but we have to draw the line somewhere in terms of version support. Enforcing some amount of normalization is a good thing IMO as it keeps things sane and commonly understood. If p1 is what you mean, how about using p1?

**Comment by glensc** [comment]
not everyone can afford themselves changing existing versioning schema in their repos:
https://github.com/composer/satis/issues/162#issuecomment-158792998

VERSION-RELEASE scheme is used in rpm/deb packaging as well. VERSION being the "upstream" release, and "RELEASE" being the distro level repackaging, aka distro "release" counter.

and if i read [current versionparser](https://github.com/composer/semver/blob/1.2.0/src/VersionParser.php#L35) then "-" seems to be allowed in versions, but that would require version to be three components, not only two?

**Comment by Seldaek** [comment]
Then if you can't change your version you can still generate a composer repo by hand and normalize yourself to what you want, or run a patched version, but we can't support everything in composer..

**Comment by glensc** [comment]
yeah. i run patched version for now. but as the patch is rather trivial, i had idea that maybe composer could just adjust for similar solution. currently it treats whole version invalid, but it could just ignore parts it does not recognize, the beginning part of the version is still valid for composer (i.e from `1.3-44` it can just take `1.3`)

btw, if you mean by generate by hand using {type:vcs,url:svn_url}, then currently satis does not find the tags, so need to use [patch](https://github.com/composer/satis/issues/162#issuecomment-158906504) to find the tags.

**Comment by Seldaek** [comment]
No generate by hand I mean you could build a json file yourself from the repo metadata. It's a bit more work though than running a patched version. Just pointing out that everything is open and possible so that we don't *have* to support everything under the sun.
