### ISSUE TITLE
Add satis.bat for windows user

### ISSUE THREAD

**Issue by odan** [composer/satis#169]
Hello

For windows user (like me) it would be nice to have a "bin\satis.bat" file with this content:

@echo off
php %~dp0satis %*

Then I just need to add the bin path to the %PATH% env variable and start satis in console with:
satis build "satis.json" "dirname"

**Comment by alcohol** [comment]
Is it not easy enough to just build the Phar and run that? Or running the docker container of Satis? I am not against adding a `bin/satis.bat`, I just have zero windows systems to test it on.

**Comment by alcohol** [comment]
Feel free to submit a pull request by the way.

**Comment by AnrDaemon** [comment]
```php "%~dp0satis" %*```
would be more appropriate.

**Comment by alcohol** [comment]
Added this in #363, let me know if it needs adjusting.
