### ISSUE TITLE
Satis should allow defining abandoned packages like packagist

### ISSUE THREAD

**Issue by naderman** [composer/satis#183]
The equivalent of https://github.com/composer/packagist/issues/192 in satis.json

**Comment by patkar** [comment]
:+1:

**Comment by SvenRtbg** [comment]
Committing an additional key `"abandoned":"true"` into the composer.json of a package will forward the flag into Satis repository metadata. However this won't work for tagged versions that cannot be altered afterwards. My local solution is to run an afterburner script that detects "abandoned" flags on the master branch and duplicates it onto every other version if it isn't already present.

**Comment by patkar** [comment]
Can you create a gist of your afterburner script?

**Comment by SvenRtbg** [comment]
Here you are: https://gist.github.com/SvenRtbg/2cf56388ac996870f380

Your execution of Satis may vary, but you should get the idea: Run the php script with the json file name as first parameter. Satis creates one packages.json file that only contains a reference to another file - THAT file should be worked on, but you cannot be sure that updates of Satis change this structure and create more files.

Note that this script uglyfies the result - Satis creates beautiful indented JSON, PHP with json_encode() does not.

**Comment by stof** [comment]
@SvenRtbg you can create a beautiful indented JSON file on PHP 5.4+ by changing the flag passed as second argument to ``json_encode``. This is exactly how Satis does it.

**Comment by alcohol** [comment]
Does #268 suffice, @naderman ?

If not, please re-open this.
