### ISSUE TITLE
Very long to build when you have hundreds (or more) of packages

### ISSUE THREAD

**Issue by taymour** [composer/satis#186]
Question : would it be possible to try executing download commands in separate threads, so that it builds faster ?

**Comment by killerwolf** [comment]
+1

**Comment by astehlik** [comment]
It would be great if you could specify a set of packages that should be updated and leave the rest as it is.

**Comment by stof** [comment]
@astehlik this is already supported. This command would update only ``symfony/console`` and ``symfony/http-kernel``:

```bash
bin/satis build packages.json web/ symfony/console symfony/http-kernel
```

**Comment by mpdude** [comment]
Yes, but it still scans all available repos which is slow for VCS.

**Comment by planktonfun** [comment]
same problem here 171 vendors with more than 100 tags each, maybe I'll leave my pc running for over a week

**Comment by alcohol** [comment]
Actually, it is for this reason that this line exists:
https://github.com/composer/satis/blob/master/src/Builder/ArchiveBuilder.php#L53

It is not perfect. But it does mean that you could run several build commands in parallel using for example GNU `parallel`. If one of the commands encounters a package already downloaded by another command running in parallel, it will simply skip it.
