### ISSUE TITLE
Specific commit

### ISSUE THREAD

**Issue by crisp-github** [composer/satis#190]
Does satis allow a specific commit to be required e.g.

"someone/something": "dev-master#43634587676dgd22ae89a93245435dfgfddsfg",

I'm trying to use this feature but not having any luck - a more recent version of the package is being installed.

**Comment by huglester** [comment]
Actually it should work, but I had also problem with this earlier. Try:

"someone/something": "dev-master#43634587676dgd22ae89a93245435dfgfddsfg as 1.0.0",

or something like that

**Comment by mbrodala** [comment]
See #242 for an explanation.
