### ISSUE TITLE
Host Port from composer.json Missing in composer.lock

### ISSUE THREAD

**Issue by seydu** [composer/satis#193]
My Statis server is listening on a non standard port, so I had to put the port in the composer.json.
But in the generated composer.lock the port is stripped (9877), so my downloads fail
```json
{
    "name": "...",
    "description": "...",
    "repositories": [ 
      { "type": "composer", "url": "http://packagist.my-company.net:9877" },
      { "type": "composer", "url": "https://packagist.org" }
    ],
    "require": {
        "my-company/my-repo":                                      "0.1.1"
    },
    "minimum-stability": "dev"
}
```
It seems to me that this problem is a Composer behavior.

**Comment by stof** [comment]
This should be reported to the Composer issue tracker instead, to have the issue in the right project. the composer.lock is not handled by Satis at all.

**Comment by seydu** [comment]
That's what I thought. Will close this issue and open a similar one on composer.
Thanks.
