### ISSUE TITLE
Suggestion: Add a favicon

### ISSUE THREAD

**Issue by valioDOTch** [composer/satis#194]
Feature suggestion:
Integrate a favicon, so that's it's easier to find the link in the bookmarks

Suggested image template: 
http://commons.wikimedia.org/wiki/File:Package-x-generic.svg

Ico-File created from suggested template above with 48x48, 32x32 and 16x16px size http://s000.tinyupload.com/index.php?file_id=15029993054614563384
(sorry for the ads, but github doesn't support .ico-filetype for image uploads)

**Comment by GromNaN** [comment]
This is a nice icon 
![Favicon](http://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Package-x-generic.svg/48px-Package-x-generic.svg.png)

 It could replace be used on Packagist.com too ![Favicon](https://packagist.org/favicon.ico)

**Comment by valioDOTch** [comment]
Yes I think the image language is more obvious with this one

**Comment by alcohol** [comment]
@seldaek I'll leave this up to you, as to what is an appropriate or acceptable image.

**Comment by timdiels1** [comment]
So any progress on this?

**Comment by alcohol** [comment]
I don't see any open pull requests, so I guess not.

**Comment by timdiels1** [comment]
@alcohol I would love to help for this, but no clue where to start as i don't seem to find a way to test this locally...

**Comment by alcohol** [comment]
The quickest way to test this would be to run Satis within docker with a very minimal configuration.

**Comment by moneef** [comment]
@alcohol @valioDOTch @timdiels1 , i have created a pull request https://github.com/composer/satis/pull/597 to add favicon.

**Comment by theimbender** [comment]
I'm pretty sure this issue can be closed, a favicon was added to satis more than two years ago.
