### ISSUE TITLE
Runtime exception when building -  Could not parse version constraint

### ISSUE THREAD

**Issue by corleonis** [composer/satis#200]
I am running latest Satis but when I try to build I am getting run time exception:

[RuntimeException]
Could not load package phpspec/prophecy in http://packagist.org: [UnexpectedValueException] Could not parse version constr
aint ^1.0.2: Invalid version string "^1.0.2"

I presume the caret ^ is new symbol added to Composer ut not backported to Satis.

**Comment by DennisBecker** [comment]
Easy fix - update Satis, run composer install and then it will work.

**Comment by haoyuguo** [comment]
I have the similar problem while trying to install a set of behat related packages (https://github.com/laracasts/Behat-Laravel-Extension/issues/16). No luck even with the latest composer.phar ( 1.0.0-alph-9 ).

Any suggestion?

Thanks!

**Comment by RomainLanz** [comment]
Same solution. You need to update your composer.

````
composer selfupdate
````

**Comment by GrahamCampbell** [comment]
1.0.0-alpha-9 is not the latest. It's too old for this to work.

**Comment by nykopol** [comment]
1.0.0-alpha-9 seems to be to old. But avoiding to switch to composer/composer:dev-master would be pleasant because dev-master require sf 2.5. Actually, I'm still on 2.3 and haven't planned to do this upgrade soon.

**Comment by stefanruijsenaars** [comment]
The latest tagged version is alpha9. Can we get a new alpha10 that allows for the caret?

**Comment by alcohol** [comment]
Closing, please re-open if this is still a concern.
