### ISSUE TITLE
Relative path problem with 'include/all$somehash.json'

### ISSUE THREAD

**Issue by h4cc** [composer/satis#201]
The given `include/` path is a relative path that will break if you run your satis from a subdir like http://example.com/satis/.
Because then composer will not try to fetch http://example.com/satis/includes/all$somehash.json but http://example.com/includes/all$somehash.json which will result in a 404.

Should here maybe used the `homepage` key from the configuration?

**Comment by h4cc** [comment]
Or is this a bug in composer because it does not use the relative path correctly from the packages.json?

**Comment by aaukt** [comment]
We run exactly this setup and it's working without problem if you set the "homepage" like:
```javascript
{
    ...
    homepage: "http://example.com/satis"
    ...
}
```

**Comment by h4cc** [comment]
@aaukt Whats your  `composer --version`?

**Comment by h4cc** [comment]
Seems to be fixed by composer.
Anybody with the same problem: Update to newest composer version.
