### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by davidsteinsland** [composer/satis#207]
We're using Satis internally for private repositories, but lately we're faced with some problems.

In the satis web page, all the links to "Releases" gives:
```json
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

Some of our colleagues are also having problems installing these packages via composer; either getting partially downloaded files or none at all.

Is there a recent update to the Github API that satis does not handle? We're using latest satis version.

**Comment by GrahamCampbell** [comment]
Not found responses are often github's way of saying access denied.

**Comment by davidsteinsland** [comment]
Well that's interesting.. I have administrator privileges to the repositories in question, so that should not be a problem.

**Comment by GrahamCampbell** [comment]
Are they on an organisation? Do you have that new third party access control enabled? That could be it.

**Comment by davidsteinsland** [comment]
`No restrictions`, so that shouldn't be a problem either …

**Comment by brunogaspar** [comment]
If they are private repositories, it's perfectly normal that you get the 404, they are private and not publicly accessible, therefore you need to authenticate yourself to the GitHub Api.

It's the way it should be, for your own security, otherwise anyone could download your stuff, easily.

**Comment by davidsteinsland** [comment]
Yeah, I get that, but we are having issues like these as well:

```
- Installing OWNER/REPO (0.1.1)
   Downloading: connection...    Failed to download OWNER/REPO from dist: The "https://api.github.com/repos/OWNER/REPO/zipball/SHASUM" file could not be downloaded (HTTP/1.1 404 Not Found)
   Now trying to download from source
 - Installing OWNER/REPO (0.1.1)
   Cloning SHASUM
```

**Comment by brunogaspar** [comment]
If Composer can't download but can clone, i believe your issue is that the GitHub Oauth token is invalid/expired/removed.

Try to follow this guide https://coderwall.com/p/kz4egw/composer-install-github-rate-limiting-work-around

**Comment by alcohol** [comment]
Closing, please re-open if this is still a concern.
