### ISSUE TITLE
URL of custom repository duplicated

### ISSUE THREAD

**Issue by mbrodala** [composer/satis#210]
I have set up a private Composer repository like `http://composer.example.org/` via Satis and so far it seems to be built fine. The basic structure of my `satis.json`

```json
{
  "name": "Example",
  "homepage": "http://composer.example.org/",
  "repositories": [
    { "type": "vcs", "url": "git@..." }
  ],
  "require-all": true,
  "output-dir": "web"
}
```

I have added this repository globally on my machine, the relevant lines from `composer config --global --list`:

    [repositories.custom.type] composer
    [repositories.custom.url] http://composer.example.org/

While trying to `create-project` one of the listed repositories, I get an error like this:

    [Composer\Downloader\TransportException]
    The "http://composer.example.org/http://composer.example.org/include/all$<checksum>.json"
    file could not be downloaded (HTTP/1.1 404 Not Found)

As you can see the repository URL has been duplicated and I am not sure why this happens. The `packages.json` generated by Satis looks like this:

```json
{
    "packages": [],
    "includes": {
        "http://composer.example.org/include/all$<checksum>.json": {
            "sha1": "<checksum>"
        }
    }
}
```

Any idea what might be wrong here?

**Comment by mbrodala** [comment]
The disadvantage of this is that the web index now suggests this:

> Adding the repository to composer.json:
> ```
> {
>     "repositories": [
>         {
>             "type": "composer",
>             "url": ""
>         }
>     ]
> }
> ```

The missing URL is normally determined from the `homepage` field.

**Comment by stof** [comment]
This looks like a bug in Satis. The ``includes`` section in packages.json is not expected to contain an absolute URL

**Comment by mbrodala** [comment]
The issue seems to be fixed by now.
