### ISSUE TITLE
dist url drops prefix if using homepage default

### ISSUE THREAD

**Issue by matthew-james** [composer/satis#211]
I am using Satis to mirror zip archives of packages.  Our Satis repo uses ssl and http basic auth.

Here is (a sanitized version of) my current satis.json:

https://gist.github.com/matthew-james/9e8cd15320d0cadbf46a

Originally I did not specify a prefix-url.  This resulted in Composer trying three times before failing to download the zip file.

This is the strace output:

````
open("/var/www/7.1-Branch/laravel/packages.my-company.com/packages/dist/symfony-event-dispatcher-ce9246f87133be616f5db06b5e162f5210f95280-zip-b8ca22.zip", O_RDONLY) = -1 ENOENT (No such file or directory)
write(4, "\10\10\10\10\10\10\10\10\10\10\10\10\10\10\10\10\10\10\10\10\10\1) = 300\10\10\10\10\10\10", 30
write(4, "    Downloading: \33[33m100%\33[39m", 31    Downloading: 100%) = 31
write(4, "         ", 9         )                = 9
write(4, "\10\10\10\10\10\10\10\) = 9", 9
write(4, "\n", 1
````

Once I added the prefix-url it downloaded correctly.

The Composer output originally showed this:

````
  - Installing symfony/event-dispatcher (2.7.x-dev ce9246f)
Reading packages.my-company.com/packages/dist/symfony-event-dispatcher-ce9246f87133be616f5db06b5e162f5210f95280-zip-b8ca22.zip
````

After adding the prefix-url it shows this:

````
  - Installing symfony/event-dispatcher (2.7.x-dev ce9246f)
Downloading https://packages.my-company.com/packages/dist/symfony-event-dispatcher-ce9246f87133be616f5db06b5e162f5210f95280-zip-b8ca22.zip
    Down    Downloading: 100% 
````

So it seems the https:// prefix is dropped when using the homepage url.

Thanks,

Matt

**Comment by alcohol** [comment]
Closing, please re-open if this is still a concern.
