### ISSUE TITLE
Satis not using auth.json in same directory

### ISSUE THREAD

**Issue by dasuchin** [composer/satis#216]
I have an auth.json file:
`
{
    "http-basic": {
        "https://svn-url.com": {
            "username": "svnuser",
            "password": "svnpassword"
        }
    }
}
`

and my satis.json:
`
"url": "https://svn-url.com/svn-directory"
`

But it's not using the credentials in the auth.json file, its still asking me for them.

Anyway to resolve this?

**Comment by shochdoerfer** [comment]
If I recall correctly the auth.json file needs to be placed in $HOME/.composer, not sure if satis will read the file when it`s placed next to the satis config file. Also make sure to not use the protocol in the auth.json file, just use the hostname as is. In your case "svn-url.com".

**Comment by alcohol** [comment]
Closing, please re-open if this is still a concern.

**Comment by carlosrochap** [comment]
Hi guys,

but what can be done if the user don't have a home folder?

**Comment by shochdoerfer** [comment]
@carlosrochap IIRC you can define an COMPOSER_HOME environment variable to define the home folder. At least for Composer itself does it work this way, might also work for Satis then.

**Comment by carlosrochap** [comment]
@shochdoerfer you are right, I created that variable to point to a custom folder and is working fine.  Thanks ;)
