### ISSUE TITLE
Serve both HTTP(s) and SSH repos

### ISSUE THREAD

**Issue by huglester** [composer/satis#217]
Hello,

I wonder, is there a way, to tell satis, that my vendor/package1 has both versions available, via SSH and HTTPS?

Currently we have some problems with dockerCI images, when they try to access the repos, so basicly we would like to CI runners to clone repo via SSH, but for example for windows users (and beginners, and some public places) HTTPS is faster/easier.

Thank you for any information.

**Comment by narcoticfresh** [comment]
+1; I'm having the same issue..

**Comment by ihor-sviziev** [comment]
:+1:
