### ISSUE TITLE
Satis - update single repo?

### ISSUE THREAD

**Issue by huglester** [composer/satis#219]
Hello,

currently when updating satis, we run it through all packages. But when more packages appear/more bnraches/tags it starts to get slower and slower. Is there a way to tel satis, that, for example, update repo: vendor/repo1 only, not the whole repo-list? 

Thanks

**Comment by mpdude** [comment]
There are already a few issues/PRs addressing this, try the search (don't have the issue numbers at hand).

**Comment by huglester** [comment]
already exists? #142

**Comment by huglester** [comment]
I can't manage it to work...

it says:
`build [--no-html-output] [--skip-errors] [file] [output-dir] [packages1] ... [packagesN]`
but packages1, packagesN .. Where do I get this packages1 naming?

**Comment by stof** [comment]
@huglester these are the name of packages you want to update (this is used for partial updates)
