### ISSUE TITLE
Many silent failures == inability to create repo

### ISSUE THREAD

**Issue by weierophinney** [composer/satis#222]
I'm attempting to rebuild the ZF2 composer repository (https://packages.zendframework.com), as we have recently split our components into dedicated development repositories (which has necessitated changing URIs).

The satis.json I'm working with is this:

```json
{
  "name": "Zend Framework Repository",
  "homepage": "https://packages.zendframework.com",
  "repositories": [
    {"type": "vcs", "url": "https://github.com/zendframework/zend-authentication.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-barcode.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-cache.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-captcha.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-code.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-config.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-console.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-crypt.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-db.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-debug.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-di.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-dom.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-escaper.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-eventmanager.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-feed.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-file.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-filter.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-form.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-http.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-i18n.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-i18n-resources.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-inputfilter.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-json.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-ldap.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-loader.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-log.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-mail.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-math.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-memory.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-mime.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-modulemanager.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-mvc.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-navigation.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-paginator.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-permissions-acl.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-permissions-rbac.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-progressbar.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-serializer.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-server.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-servicemanager.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-session.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-soap.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-stdlib.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-tag.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-test.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-text.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-uri.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-validator.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-version.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-view.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zend-xmlrpc.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendCloud.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendDeveloperTools.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendGData.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendOAuth.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendOpenId.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendPdf.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendQueue.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendRest.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_AgileZen.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_Akismet.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_Amazon.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_Api.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_Apple_Apns.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_Audioscrobbler.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_Delicious.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_DeveloperGarden.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_Flickr.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_GoGrid.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_Google_C2dm.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_Google_Gcm.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_LiveDocx.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_Nirvanix.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_OpenStack.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_Rackspace.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_ReCaptcha.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_SlideShare.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_StrikeIron.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_Technorati.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_Twitter.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendService_WindowsAzure.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendXml.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZendSkeletonApplication.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zf1.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/zf2.git"},
    {"type": "vcs", "url": "https://github.com/zendframework/ZFTool.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-angular.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-apigility.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-apigility-admin.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-apigility-admin-ui.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-apigility-doctrine.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-apigility-documentation.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-apigility-documentation-swagger.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-apigility-example.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-apigility-provider.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-apigility-skeleton.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-apigility-welcome.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-api-problem.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-configuration.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-console.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-content-negotiation.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-content-validation.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-deploy.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-development-mode.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-doctrine-querybuilder.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-hal.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-http-cache.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-mvc-auth.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-oauth2.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-rest.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-rpc.git"},
    {"type": "vcs", "url": "https://github.com/zfcampus/zf-versioning.git"}
  ],
  "require-all": true,
  "archive": {
    "directory": "composer",
    "format": "zip",
    "skip-dev": false
  }
}
```

I then execute this using

```console
$ ./bin/satis build ./satis.json ../../public
```

I have run into several errors, however, that I cannot figure out how to recover from.

First, frequent errors of the following nature:

```
ZipArchive::extractTo(...) : failed to open stream: Invalid argument
```

The only way to recover from the above is to remove the line for that component, unfortunately.

Second, I am frequently seeing 255 exit status codes with *no* error information whatsoever, even when running using `-vvv`. The specific one that tends to create the 255 error code regularly is `zendframework/zendframework1:1.12.0`; I have a sneaking suspicion that we may be hitting either a timeout or memory condition (as it's a very, very large package).

The end result of both, however, is that I am unable to complete a build of the repository with the full set of components we wish to provide.

Any tips or suggestions are welcome.

**Comment by lenada** [comment]
@weierophinney I ran a satis build against your satis.json over night. takes ages but completes. Once all the zip files are created re-running satis build is much faster.
I used the latest satis.phar with php7 (php5-7.0.0-dev-20150428-140950) and memory_limit cranked up to 4GB

**Comment by weierophinney** [comment]
Hmm.. we have 5.4 on the server this runs on, which may be part of the issue.

Stephan Hochdörfer indicated that he points `satis.json` at local bare checkouts. My thought is that we could potentially do this, which would speed up the generation (in part by removing the GitHub API out of the equation), and also isolate whether or not the issue is specifically in PHP.

**Comment by lenada** [comment]
satis uses the composer cache, so once a dist package/repo has been downloaded/cloned  github api rate limiting should not be an issue. My testbuild has not run into any github api issues btw.. It seems the critical part is to have one successful run that creates the packages.json and its include file (around 10mb). Then re-running the build takes about 10 minutes (tested with php 5.6.9). Even when deleting public/composer/* , rebuilding from cache with about 3gig of package data does not take too long.

should I post my generated package.json somewhere?

**Comment by weierophinney** [comment]
> satis uses the composer cache, so once a dist package/repo has been downloaded/cloned github api rate limiting should not be an issue.

In testing this week, I *consistently* hit API limits, despite the cache.

> It seems the critical part is to have one successful run that creates the packages.json and its include file (around 10mb). Then re-running the build takes about 10 minutes (tested with php 5.6.9).

I'm aware of this. We've been running our own repo for a couple of years or more. ;-)

I'm *rebuilding*, for the reasons noted in the summary, and it's during the rebuild that I'm running into issues. I'd do it on my local machine and push to the server, but the size of the repo is far too large to do this.

> should I post my generated package.json somewhere?

I'm not sure this would help, as we also want/need the generated packages, and it seems the bulk of the issues we're running into have to do with package generation.

**Comment by shochdoerfer** [comment]
@weierophinney Does it work when you disable the archiving?

**Comment by weierophinney** [comment]
> Does it work when you disable the archiving?

Indeed. Trying a full run with archives locally now, against local repos.

**Comment by weierophinney** [comment]
W.T.F?!?!?! I ran the same command a second time, this time enabling archives. I immediately got this:

```console
$ ./bin/satis build ./satis.json public
Scanning packages
Reading composer.json of zendframework/zendservice-agilezen (release-2.0.0)
Skipped branch release-2.0.0, Could not parse version constraint >=2.0.*: Invalid version string "2.0.*"

Creating local downloads in 'public/composer'
Dumping 'composer/satis-1.0.0.0-alpha1'.
  - Installing composer/satis (1.0.0-alpha1)
    Cloning b20fd944ec40ad65c1e54bb0860fe844f4efd56e



  [RuntimeException]
  Failed to execute git clone --no-checkout '' '/tmp/composer_archive556895fb428cd' && cd '/tmp/composer_archive556
  895fb428cd' && git remote add composer '' && git fetch composer
  fatal: The empty string is not a valid path



build [--no-html-output] [--skip-errors] [file] [output-dir] [packages1] ... [packagesN]
```

- Why is it dumping composer/satis? That's nowhere in my repo list..
- Why is it trying to clone an empty path?

**Comment by weierophinney** [comment]
I know we had some bad version constraints in some of our early packages; does that mean I'll need to identify and omit each one of those from the build? I didn't have to previously...

**Comment by weierophinney** [comment]
I've started running it with the `--skip-errors` flag, and I'm getting better results. Will let you know if/when it successfully finishes.

**Comment by weierophinney** [comment]
I completed a run with archives using the `--skip-errors` flag, and did a separate run, outputting to a separate directory, with no archives.

What I saw was interesting:

- The `packages.json` included `composer/satis` in both. However, there were no archives present for it. I do not understand why it was present.
- None of zftool, zf1, zf2, or any zfcampus modules (other than, strangely, zf-angular) were present, in *either* the `packages.json` *or* the archives.

I'm going to re-run with the `-vvv` flag and `--skip-errors` in the hopes that I can see why those were omitted.

**Comment by weierophinney** [comment]
Found the issue; when I repointed to local repositories, I introduced some incorrect paths in the `satis.json`. The dry-run without archives ran perfectly, and I'm now running with archives.

**Comment by weierophinney** [comment]
Everything was successful locally, using PHP 5.5.6. Unfortunately, our server is on a late 5.4 version, so I may still end up with issues once I run there. However, I think the "checkout bare clones of each repo locally" hack from @shochdoerfer gives us a path forward finally - thanks, Stephan!

**Comment by shochdoerfer** [comment]
@weierophinney You are welcome. If you need help or want me to review your final solution ping me. Happy to help out! I spent a lot of time optimizing our own infrastructure...

**Comment by weierophinney** [comment]
@shochdoerfer Finally got it up and running again! I ended up doing the following:

- Cloning all repos locally on the server
- Pointing `satis.json` at those local checkouts
- Adding functionality to our `Makefile` to update all repositories prior to running `satis build`
- Adding the `--skip-errors` flag to our `satis build` invocation

It took 5 runs of `satis build` before it successfully completed. My guess is that satis is not freeing memory as it completes package builds, because it was failing silently, even when `-vvv` was present. Once I had a complete build, however, I was able to get the above working without an issue.

I suspect we'll have one more problem as we finish an upcoming 2.5 release, as this is the last release where all components will update at once; past that, however, I hope we'll have smooth sailing.

Thanks for the pointers!

**Comment by shochdoerfer** [comment]
@weierophinney You can update one package a time when you run satis like this $ ./bin/satis build ./satis.json public zendframework/zend-console zendframework/zend-config

This will still query every git repo in your satis.json file but generate only the package metadata for the specified packages. This is how we configured or Jenkins instance to re-built just the package which received the changes.

**Comment by weierophinney** [comment]
@shochdoerfer Yeah, aware of that feature; considering setting up a webhook in the future to do this. Right now, I have an hourly cronjob to update all repos at once (which effectively only updates those with changes since last run). Unfortunately, I've spent too much time already rebuilding, so I'll need to push that to another date.

**Comment by naderman** [comment]
@weierophinney I tried generating the repo from this issue locally, and it worked without any problems. Did you set the machine up with an oauth token? Are you sure there's sufficient disk space on it? It seems more likely to me that there was some environmental issue triggering this behavior?

**Comment by weierophinney** [comment]
@naderman Yes - I ran into the same issues both on our server and on my local workstation, and they have quite different environments, ranging from PHP version (5.4 on the server, 5.6 locally) to available RAM (4 GB on the server, 16 GB locally) to PHP configuration (memory_limit is 128M on the server, -1 locally). Both have plenty of disk space. I setup OAuth2 tokens in the composer configuration for both. I appreciate that you and others were able to run the initial build without error, but I have not yet been able to do so myself, which was what prompted this report.

(Interestingly, I discovered that even *with* an OAuth2 token, you're limited to 5000 calls, and that limit is aggregated per user; i.e., adding another token will not give you more calls if the token is for the *same* *user*. During testing i was hitting that limit, which made tracing down issues even harder; this was when @shochdoerfer suggested using local checkouts of the git repositories.)

Even when I used the local repositories, I was hitting problems creating the initial build; I had to re-run `satis build` 5 times before it completed successfully. Each would get a little bit farther, and then inexplicably die. Using the `-vvv` flag and turning on `display_errors` did not help; the script would die with no diagnostic information whatsoever. Once I got a successful build, however, it has worked flawlessly (with the exception of the fact that the source URLs were pointing to the local repos, and not the canonical github repos, a situation I've now fixed by post-processing the generated JSON).

If you cannot reproduce, and I have a working repo now, I'm not sure if anything more can be done. But I'm hoping that if anybody else has the same experience, they can find this post and try similar processes  to what I have to get a successful build.

**Comment by naderman** [comment]
Alright that certainly covers all the obvious ideas I had for environment issues. Just trying to understand what could be causing this problem on those machines but not on others. Would certainly like to avoid that everyone needs to setup local mirror repositories just to build a satis repository.

But other than trying to debug it on your machines, I don't really have any further ideas for what to do.

**Comment by joshdifabio** [comment]
> Why is it dumping composer/satis? That's nowhere in my repo list..

@weierophinney It might be worth checking your global Composer config (`~/.composer/config.json` by default on unix systems) as any repos defined there will be processed during your Satis build. Given that your Satis config uses `require-all = true`, any packages provided by repositories which are included in your global Composer config will be downloaded.

To ignore the repositories defined in your global config you can run your Satis build like this:

```
$ COMPOSER_HOME=/dev/null COMPOSER_CACHE_DIR=~/.composer/cache php bin/satis build ...
```
