### ISSUE TITLE
Provide Docker Image

### ISSUE THREAD

**Issue by jwhitcraft** [composer/satis#228]
It would be awesome if an official Docker Image could be provided so we can use docker to get it up and running faster than having to provision our own server.

**Comment by ihor-sviziev** [comment]
:+1:

**Comment by ihor-sviziev** [comment]
@alcohol what about pushing docker image to docker hub?

**Comment by alcohol** [comment]
Sorry. I only merged this file to please the few users that asked for it. We (@composer) don't really have a desire to maintain a docker image.
