### ISSUE TITLE
DateTime Unexpected character

### ISSUE THREAD

**Issue by NV-iloweb** [composer/satis#230]
Hello,

I've been using satis for a while now and since a little while (I couldn't find when exactly) I encounter this error :  ``Skipped branch 1.6, DateTime::__construct(): Failed to parse time string (@) at position 0 (@): Unexpected character``

It is to retrieve a simple bundle, it's the only bundle that gets this error (all of the others work fine) and I don't know what this DateTime is used for or where it comes from.
The problem happens on a server running PHP v5.4.41 but the thing is I don't have this problem when trying myself using PHP v5.5.14 or PHP v5.4.19 (if it matters..).

If anyone has anything (solution or even hints) that could help solve this problem.

Thanks.

**Comment by alcohol** [comment]
Closing, please re-open if this is still a concern.
