### ISSUE TITLE
Is commit hash respected for git ?

### ISSUE THREAD

**Issue by crisp-github** [composer/satis#242]
In config.json we have:

"bllim/datatables": "dev-master#4013d18bf000ac",

but the latest satis with hash bde740b5c9b877caa5abcc51da0010bc5628165f is downloading the latest dev-master not that specific hash. 

Is this a bug, a feature or I'm making a mistake ?

Thanks.

Some more info, it seems satis is downloading the latest on dev-master and then returning this when a specific commit hash is requested. In the composer.lock generated by running composer that is pulling from satis:

            "dist": {
                "type": "zip",
                "url": "http://localhost:8001/dist/bllim-datatables-2e3aaca5455049f94d21ad47c5db868a8ca12d32-zip-f95e77.zip",
                "reference": "4013d18bf000ac",
                "shasum": "19fab27fd67d28d1f2e75b77ab6a10ac02f2811d"
            },

Notice that the reference is the start of the commit hash and should match the zip filename ?

**Comment by mbrodala** [comment]
This is a Composer thing, see [the docs](https://getcomposer.org/doc/04-schema.md#package-links):

> **Note**: While this is convenient at times, it should not be how you use packages in the long term because it comes with a technical limitation. The composer.json metadata will still be read from the branch name you specify before the hash. ...

#190 is basically the same issue.
