### ISSUE TITLE
Customizing a Package's "name"

### ISSUE THREAD

**Issue by tyler-sommer** [composer/satis#244]
I have a use-case where I want to add a prefix to specific package names. For example, I'd like to modify all references of `internal/framework` to `client1-internal/framework` but leave all references to `int-build/core` as `int-build/core`. 

I understand that I can simply [reference my Satis repository with a "vendor-alias"](https://getcomposer.org/doc/05-repositories.md#custom-vendor-alias), but that replaces *all* vendor names with the alias; it does not simply prefix it, and not on a per-package basis.

I've looked through the Composer internals, and I can see that the Package `LoaderInterface#load` method takes a second argument for the class name. I was hoping this could be an extension point, but it looks like that argument is actually reserved for internal use.

Is there a way to modify a package's name prior to generating `packages.json`?

**Comment by alcohol** [comment]
Why not do that on the package level? So in the composer.json of the package/library itself.

**Comment by tyler-sommer** [comment]
@alcohol That would work and may actually be the right way to go. This was requested by a user of one of my projects (https://github.com/terramar-labs/packages/pull/17), so I am not able to come up with a proper rebuttal.

As a matter of curiosity, is it even possible to hook that deeply into the Composer process? If I could, what consequences might I want to consider?

**Comment by alcohol** [comment]
I'm not quite sure I understand what the purpose is. If it is to avoid name clashes, then you should make sure there are no packages with identical names (that is how packagist solves it).

As for hooking deep into the Composer process; I would strongly advise against that. While some of the internal API is exposed, it is not set in stone. So anything you implement on top of that would be at your own risk. So far Composer has always tried to maintain backwards compatibility whenever possible. But this is not a guarantee for the future.

**Comment by tyler-sommer** [comment]
@alcohol The more thought I put into, the more I question the original motive, as well. It seems that modifying the `composer.json` itself in each package is the correct solution to this particular request.

Regardless, thank you for the information. I really appreciate the explanation.
