### ISSUE TITLE
why satis  select all public package ?

### ISSUE THREAD

**Issue by Jamlee** [composer/satis#247]
![image](https://cloud.githubusercontent.com/assets/5196641/9835965/fc30d472-5a36-11e5-8e97-8eee93e8ce85.png)
![image](https://cloud.githubusercontent.com/assets/5196641/9835970/1747630c-5a37-11e5-8b59-a8aa59290c49.png)

##my satis.json

![image](https://cloud.githubusercontent.com/assets/5196641/9835971/2be78b20-5a37-11e5-9e09-0dbc6df1e300.png)

**Comment by alcohol** [comment]
Probably because you have no "require" filter and "require-all" is set to true.

**Comment by Jamlee** [comment]
@alcohol  `Then it uses "require-all": true which selects all versions of all packages in the repositories you defined.` taken from :https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md#setup.  so the `require-all` is not problem source.

**Comment by realshadow** [comment]
I know I am comming late to the party, but it happens because you have `require-all` set to `true`. If you want to skip packagist altogether, you should add 

```
{ "packagist": false }
```

to `repositories`section.
