### ISSUE TITLE
Build - specifying packages seems to do nothing

### ISSUE THREAD

**Issue by rmwebs** [composer/satis#249]
When building a satis repository, setting the packages at the end of the request now seems to do nothing. When it used to allow you to do --repository-url= it worked absolutely fine, however removing this seems to completely ignore the request to only build specific packages.

Example of how this is currently being run (Note there are no document or examples of this at all!)

    ./vendor/composer/satis/bin/satis build ./repository.json ./ git@git.oursite.com:some/repo.git

Any ideas why this wouldn't just build the package you wan't it to? The docs for this section are non-existant so I'm struggling to find any info on this.

**Comment by alcohol** [comment]
Uh, `--repository-url` seems a feature not even implemented/merged yet? See PR #232

So not sure what you mean by "it used to work".

**Comment by stof** [comment]
``git@git.oursite.com:some/repo.git`` is not a package name. So there is no doubt why it does not match any package

**Comment by alcohol** [comment]
As @stof pointed out, the last argument to build is
```
new InputArgument('packages', InputArgument::IS_ARRAY | InputArgument::OPTIONAL, 'Packages that should be built, if not provided all packages are.', null),
```

A repository is not a package name. :-)
