### ISSUE TITLE
add a "Community Tools" section to README

### ISSUE THREAD

**Issue by benschw** [composer/satis#250]
I've created a management UI for adding repos to satis that we've been using successfully at my company for several months now: https://github.com/benschw/satis-go

Would it make sense to include a "Community Tools" section in your README to link off to this and other projects using satis?

**Comment by realshadow** [comment]
+1

When I was integrating composer into our development process I had tried bunch of out-dated tools and in the end ended up writing my own solution (https://github.com/realshadow/satis-control-panel) and I only needed a simple UI and an API for integration with Stash and Bamboo.

This would save me quite a bit of time

**Comment by alcohol** [comment]
Merged the initial PR. Please feel free to submit more PR's linking to more useful resources/tools.
