### ISSUE TITLE
Package dependencies downloading many versions

### ISSUE THREAD

**Issue by oligriffiths** [composer/satis#254]
Hi

Here's my satis.json:

```
{
    "name": "Composer Package Host",
    "homepage": "http://localhost:8080",
    "repositories": [
        {
            "type": "composer",
            "url": "https://packagist.org"
        }
    ],
    "require": {
        "illuminate/html": "~5.0"
    },
    "require-dependencies": true,
    "archive": {
        "directory": "dist",
        "format": "tar",
        "skip-dev": true
    },
    "minimum-stability": "stable"
}
```

This results in 60MB and 174 packages downloaded into the `public/dist` folder. There are multiple versions of each packages dependencies. Is there a way to have satis not download all previous dependency versions and only download the most recent that matches the version requirements? 

It seems that `illuminate/html` requires `"illuminate/http": "~5.0"`, which results in the following versions being cached:

```
v5.1.20, v5.1.16, v5.1.13, v5.1.8, v5.1.6, v5.1.2, v5.1.1, v5.0.33, v5.0.28, v5.0.26, v5.0.25, v5.0.22, v5.0.4, v5.0.0
```

Is there a way to have satis cache only the latest available package that matches the version requirements, e.g. `v5.1.20`?

Thanks

Oli

**Comment by alcohol** [comment]
No.

**Comment by oligriffiths** [comment]
Oh, is there a reason for this? Why do we cache all the dependency versions?

**Comment by alcohol** [comment]
Because that is pretty much how it's supposed to work? If you only store the latest versions, then why even run satis at all? Disk space costs nothing, you really should not even be thinking about this. Get back to work instead.

**Comment by oligriffiths** [comment]
@alcohol Thanks for your informative response.

**Comment by alcohol** [comment]
I'm sorry but I just don't know how to respond to a question like this. Satis is like a simplified version of packagist. It stores versions locally so you don't have to rely on packagist and github for example. Why would it only store the latest version? There is no reason to assume you would only ever only want to install the latest version. It knows nothing about the clients interacting with it.

**Comment by oligriffiths** [comment]
`satis.json` contains `"illuminate/html": "5.0.0"`
`illuminate/html` contains `"illuminate/http": "~5.0"`
`~5.0` == `>=5.0.0 <6.0.0`
At this time of writing, `illuminate/http` is at `v5.1.20`, so why are all versions prior to `5.1.20` and `> 5.0.0` downloaded?

**Comment by alcohol** [comment]
Because satis !== composer ?

**Comment by alcohol** [comment]
I don't understand the question. It makes all packages that fit the ~5.0 requirement available. Why would you expect anything else?

**Comment by oligriffiths** [comment]
Fair enough. The docs don't make this clear.

**Comment by alcohol** [comment]
There is no way satis can know what specific version your projects have in their composer.lock file. So it makes sure it has everything available that fits the requirement.

**Comment by oligriffiths** [comment]
I guess the difference is between what I have in *my* composer.lock/json file, vs a dependency of a package.

**Comment by alcohol** [comment]
I don't understand that statement.

**Comment by oligriffiths** [comment]
Don't worry about it, I think I understand why these things are setup the way they are, as you say satis !== composer

**Comment by alcohol** [comment]
Satis is like a simple version of packagist that you can run locally, behind your company firewall for example, so you can host your external dependencies internally still.

**Comment by iproger** [comment]
@alcohol I have the same problem. I tried build magento 2 and I cannot to do this because satis becomes crazy. I think >10 gb for satis is too much. May be satis has a different ways to select last versions?

**Comment by alcohol** [comment]
Put more specific constraints in your `satis.json` for packages that you want to cache/proxy.

**Comment by iproger** [comment]
@alcohol I can. But will be better set one depend. Something like composer logic.
