### ISSUE TITLE
dead code in pool generation ?

### ISSUE THREAD

**Issue by JamesRezo** [composer/satis#263]
I'm not sure, but i think there is some dead code a this line 
https://github.com/composer/satis/blob/master/src/Composer/Satis/Builder/PackagesBuilder.php#L111

As far as I understand, the method addRepository(), and inside methods called, of Pool object never throws any Exception to be catched.

if someone can confirm, i'll do a PR

**Comment by stof** [comment]
it does: adding a repository in the pool loads packages of the repository, and this can throw exceptions if some package is invalid

**Comment by JamesRezo** [comment]
My bad :) I didn't explore enough Composer :)

**Comment by JamesRezo** [comment]
For the record, I found that a RuntimeException is thrown via ComposerRespository::loadRootServerFile() in ComposerRepository::hasProviders() if  the url property starts with https and open_ssl extension isn't loaded. No idea how to test that.

**Comment by stof** [comment]
Well, many different kind of extensions can be triggered
