### ISSUE TITLE
satis.phar is fat

### ISSUE THREAD

**Issue by JamesRezo** [composer/satis#282]
Since unit tests are developped alongside satis, the Compiler builds a very big satis.phar and the needs on max open files is growing up.
This issue could be easily resolved by adding
```php
->exclude(array(
    'phpunit', 'mikey179',
    'phpdocumentor', 'sebastian', 'phpspec', 'doctrine',
    'test', 'tests', 'Tests'
))
```
in the Finder.

As nobody complains with this issue :), we could also replace that piece of code by a `box.json` file in order to use [box project](https://github.com/box-project/box2)

Whatever the choice, we also could add some documentation on that feature.

**Comment by alcohol** [comment]
I quite like Box and would personally vote in favour of that approach.

/cc @Seldaek @naderman any objections/feedback?

**Comment by Seldaek** [comment]
Nope. If it does the job it's fine by me.
