### ISSUE TITLE
Archiving Empty Folders

### ISSUE THREAD

**Issue by atishgoswami** [composer/satis#289]
Hi,

I am facing an issue with a composer package `magento/magento2-base` which I am trying to cache on my Satis server instance. Seems that composer package has some empty folders which are getting ignored while satis is re-zipping it to its `dist` folder (package storage folder), as it using `Phar::buildFromIterator()` to re-archive the package, which ignores empty folders.

Is there any way to make it include the empty folders as well during the archiving process.

Thanks

**Comment by mc388** [comment]
This is not a satis issue it is a composer issue. I will try to fix this and create a PR

**Comment by atishgoswami** [comment]
Just wanted to add reference to the [composer/composer](https://github.com/composer/composer) repo PR [#5144](https://github.com/composer/composer/pull/5144) which might have fixed the issue.
