### ISSUE TITLE
Satis tries to list bogus SVN path, aborts.

### ISSUE THREAD

**Issue by cxj** [composer/satis#291]
For some reason, Satis tries to do an `svn ls` on a non-existent directory in my SVN repository, and aborts.

```
$ satis build -vvv satis.json .
Loading config file /home/user/.composer/config.json
Loading config file /home/user/.composer/auth.json

[snip]

Scanning packages
Executing command (CWD): svn ls --verbose --non-interactive  'https://svn.example.com/svn/libs/'
Executing command (CWD): svn ls --verbose --non-interactive  'https://svn.example.com/svn/libs/tags'
Executing command (CWD): svn --version



  [RuntimeException]
  Repository https://svn.example.com/svn/libs/php could not be processed,
  svn: warning: W160013: URL 'https://svn.example.com/svn/libs/tags' non-existent in revision 24839
  svn: E200009: Could not list all targets because some targets don't exist
```

The satis.json file is below.  Note the difference in the path name of the actual repository URL and what satis tries to use in the second `svn ls` command above.  What's up with that?

```
{
    "name": "Package Repository",
    "homepage": "https://phppkg.example.com",
    "repositories": [
        {
            "type": "vcs",
            "url": "https://svn.example.com/svn/libs/php/"
        }
    ],
    "require-all": true
}
```

See attached file bar.txt for the full output from the satis run including stack backtrace.
[bar.txt](https://github.com/composer/satis/files/79407/bar.txt)

**Comment by aaukt** [comment]
From the docs:
>Since Subversion has no native concept of branches and tags, Composer assumes by default that code is located in $url/trunk, $url/branches and $url/tags.

You should check the [Subversion options](https://getcomposer.org/doc/05-repositories.md#subversion-options) and adjust accordingly.

**Comment by cxj** [comment]
trunk/tags/branches all exist as proper subdirectories beneath each Composer project.

As a side note, Satis appears to ignore several of the Composer VCS options, but I haven't extensively investigated that point.

**Comment by cxj** [comment]
This looks like it might have been caused by a require line in my ~/.composer/composer.json file.  Although the path and package was not all related, removing them seems to have made Satis work correctly.
