### ISSUE TITLE
Unable to mirror Packagist 404 Not Found

### ISSUE THREAD

**Issue by tschechniker** [composer/satis#294]
Hi,

i want to mirror Packagist with satis. I'm using the following satis.json:

````json
{
  "require-all": true,
  "repositories": [
    {
      "type": "composer",
      "url": "https://packagist.org"
    }
  ]
}
````

I'm always getting an 404 Not Found error on different packages:

````bash
  [Composer\Downloader\TransportException]
  The "https://packagist.org/p/anomaly/users-module%2406a29a55bf0105835171a0950a784600691d18b2dd414f60c01545ed94282b12.json" file could not be downloaded (HTTP/1.1 404 Not Found)
````

How can i solve this problem? I tried --skip-errors but this seems not to handle this kind of error.

**Comment by alcohol** [comment]
This use-case isn't really supported. There is far too much metadata to mirror. Most of this data is resolved recursively. But by the time the update process gets to deeper urls, they may be outdated already.
