### ISSUE TITLE
Dependencies are not archived

### ISSUE THREAD

**Issue by mc388** [composer/satis#296]
In my satis.json file a added a link to my repository and set die archive node. My repository includes some dependencies and dev dependencies. If I run `php bin/satis build --no-interaction satis.json /var/www` it will only include an archive for my repository but not for the dependencies.

Here my satis.json file:

```json
{
  "name": "My satis repository",
  "homepage": "http://satis.example.com",
  "repositories": [
    {
      "url": "git@github.com:<user>/<repository>.git",
      "type": "vcs"
    }
  ],
  "require-all": true,
  "require-dependencies": true,
  "require-dev-dependencies": true,
  "archive": {
    "directory": "dist",
    "format": "zip",
    "skip-dev": true
  }
}
```

I want that from all of my dependencies an archive is created.

**Comment by alcohol** [comment]
As far as I know, Satis will do that, as long as each of those dependencies is also hosted on github/bitbucket.

**Comment by mc388** [comment]
For example in my repository i have phpunit in `required_dev`. This package is not available in the `dist`folder.

**Comment by alcohol** [comment]
Can you show your exact `require` and `require-dev` definitions?

**Comment by mc388** [comment]
```json
{
  "name": "<user>/<repository>",
  "type": "magento2-module",
  "require": {
    "symfony/console": "~2.3 <2.7"
  },
  "require-dev": {
    "phpunit/phpunit": "4.1.0",
    "squizlabs/php_codesniffer": "1.5.3",
    "phpmd/phpmd": "@stable"
  }
}
```

**Comment by mc388** [comment]
Any updates?

**Comment by alcohol** [comment]
Sorry, I have no idea. I might have some time later to try and reproduce your setup.

**Comment by aaukt** [comment]
Note that satis disables packagist by default, so you have to add the required repositories to your satis.json.

https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md#resolving-dependencies

**Comment by alcohol** [comment]
Ah right, I forgot about that. Thanks @aaukt :-)
Can you give that a shot @mc388 ?

**Comment by mc388** [comment]
So I need to add this repo do download packages like phpunit?

```json
"repositories": [
    {
      "type": "composer",
      "url": "https://packagist.org/"
    },
    ....
]
```

**Comment by alcohol** [comment]
No, adding packagist should be enough.

**Comment by mc388** [comment]
Ok, I will test this.

**Comment by mc388** [comment]
I added the packagist repository and run `php bin/satis build --no-interaction satis.json /var/www` again. This is very very slow and I get lots of error messages.

```
The chrono/infusionsoft * requirement did not match any package                            
The contao-legacy/bit3basics * requirement did not match any package
The contao-legacy/diffiehellman * requirement did not match any package
The contao-legacy/hidepagetitle * requirement did not match any package
The contao-legacy/phpseclib * requirement did not match any package
The contao-legacy/ziparchivecto * requirement did not match any package
The crunchy/crunchysignup * requirement did not match any package
The dayax/collections * requirement did not match any package
The ellicom/mailgun * requirement did not match any package
...
```

**Comment by stof** [comment]
@mc388 disable ``require-all`` when you enable Packagist. You don't want to require all of packagist

**Comment by mc388** [comment]
Changed the `satis.json`but get the same issue.

```json
{
  "name": "My satis repository",
  "homepage": "http://satis.example.com",
  "repositories": [
    {
      "type": "composer",
      "url": "https://packagist.org/"
    },
    {
      "type": "vcs",
      "url": "git@github.com:<user>/<repository>.git",
    }
    ...
  ],
  "require-dependencies": true,
  "require-dev-dependencies": true,
  "archive": {
    "directory": "dist",
    "format": "zip",
    "skip-dev": true
  }
}
```

**Comment by mc388** [comment]
Ok finally it got it. To the previouse `satis.json` I added my repositories. Currently it downloads all my packages with all dependencies.

**Comment by daften** [comment]
@mc388  could you outline how you fixed this, i can't seem to make this work. Thanks!

**Comment by erikfrerejean** [comment]
@daften it appears that you'll have to define all private packages in the `require` block as well. See also: https://github.com/AOEpeople/composer-satis-builder#example

**Comment by lushtech** [comment]
If you add "https://packagist.org"  in "repositories" and make "require-dependencies": true,
  "require-dev-dependencies": true, but not define the  "require", you will saw the error message "The chrono/infusionsoft * requirement did not match any package ..........".
So you should add your project or package name in "require". Here is a example:
`
{
    "name": "composer-satis Repository",
    "homepage": "http://packages.example.org",
    "repositories": [
            {
            "type":"vcs","url":"https://github.com/Seldaek/monolog"},
            {
        "type": "composer",
        "url": "https://packagist.org"}
    ],
    "require":{"monolog/monolog":"2.0.2"} ,
    "require-dependencies": true,
    "archive": {
       "directory": "dist",
       "format": "tar",
       "prefix-url": "http://example.com",
       "skip-dev": false
       },
    "config": {
      "github-oauth": {
            "github.com": "your token"
        }

    
    }
}
`
