### ISSUE TITLE
Different sources between original and downloaded package

### ISSUE THREAD

**Issue by mc388** [composer/satis#297]
I created a satis with magento 2 modules. Therefore I added the magento 2 composer to my `satis.json` file and satis downloads all available versions. 

After running `composer update` from my own satis I get an error while installing magento 2. If I download the packages directly from magento it works fine (same module version).

I checked the difference between both installations with `diff -yarq m2-mysatis/vendor m2-magentosatis/vendor` and get the following:

```
Only in magento2/vendor/magento/magento2-base/app: code
Only in magento2/vendor/magento/magento2-base/app: design
Only in magento2/vendor/magento/magento2-base/app: i18n
```

My `satis.json` file:

```json
{
  "repositories": [
    {
      "type": "composer",
      "url": "https://packagist.org/"
    },
    {
      "type": "composer",
      "url": "https://repo.magento.com/"
    }
  ],
  "require": {
    "magento/magento2-base": "*"
  },
  "require-all": false,
  "require-dependencies": true,
  "require-dev-dependencies": true,
  "archive": {
    "directory": "dist",
    "format": "zip",
    "skip-dev": true,
  }
}
```

**Comment by alcohol** [comment]
I do believe that repository definition order is important. Have you tried moving the magento repository *before* the packagist repository?

**Comment by mc388** [comment]
I have deleted the magento modules, changed the order and run satis build aganin but the same issue

**Comment by alcohol** [comment]
Can't really help you here unless you can come up with a small and simple scenario to reproduce. It would also help a lot if you actually figured out what the real issue is. Saying there is a difference in directories somewhere tells us nothing (of value).

**Comment by mc388** [comment]
I debugged satis and stopped after downloading the archive. I take a look into the archive and this is broken. So i think this is no satis problem anymore.

**Comment by atishgoswami** [comment]
I believe you are having the same issue I had #289
