### ISSUE TITLE
Fatal error after Command was renamed to BaseCommand

### ISSUE THREAD

**Issue by danielsmink** [composer/satis#306]
`PHP Fatal error:  Class 'Composer\Command\BaseCommand' not found in /Users/***/projects/app-internal-packagist/satis/src/Composer/Satis/Command/InitCommand.php on line 27

Fatal error: Class 'Composer\Command\BaseCommand' not found in /Users/***/projects/app-internal-packagist/satis/src/Composer/Satis/Command/InitCommand.php on line 27`

This is after a fresh install.

**Comment by alcohol** [comment]
I just pushed a commit that fixes this.

**Comment by danielsmink** [comment]
Confirmed! Thanks for the quick fix.

**Comment by alcohol** [comment]
No problem, thanks for reporting it so quickly :-)
