### ISSUE TITLE
Failed updating

### ISSUE THREAD

**Issue by garygreen** [composer/satis#307]
I'm trying to update satis but I keep getting:

```
Failed to update git@git.xx.net:repos/common.git, package information from this repository may be outdated (Failed to execute git remote set-url origin 'git@git.xx.net:repos/common.git' && git remote update --prune origin

fatal: No such remote 'origin'
```

Is there anything I'm doing wrong?

**Comment by alcohol** [comment]
Uhm, not sure what you are doing. But it looks to me like your git clone is broken.

**Comment by garygreen** [comment]
That's the weird thing... I can clone just fine and also ssh fine.

**Comment by alcohol** [comment]
Wait. Are you talking about 
* updating satis (as in, `cd /path/to/satis && git pull`);
* trying to run the `/path/to/satis/bin/satis build` command?

**Comment by garygreen** [comment]
The `/path/to/satis/bin/satis build` command.

**Comment by garygreen** [comment]
The repository is a bare repository. Does that make a difference?

**Comment by alcohol** [comment]
Not really sure. Satis should clone it locally (and it doesn't make bare clones itself). So I don't see why that would matter.

**Comment by garygreen** [comment]
Could you point me in the direction of the code that initiates the clone, that way I can maybe try and track it down?

**Comment by alcohol** [comment]
I'm honestly not sure. I reckon it uses https://github.com/composer/composer/blob/master/src/Composer/Package/Archiver/ArchiveManager.php (called from `src/Composer/Satis/Builder/ArchiveBuilder.php`), but when and in what context, not sure.

**Comment by garygreen** [comment]
It turned out to be the cache for composer which seems to have got borked somehow. So it was looking in cache, getting the tags etc but failing. Didn't get even to the stage of trying to look for updates over ssh. Cleared the cache and fixed. Sorry for wasting your time!
