### ISSUE TITLE
JetBrains TeamCity + Docker + Composer Satis = file could not be downloaded: failed to open stream: Connection timed out

### ISSUE THREAD

**Issue by IgorTimoshenko** [composer/satis#308]
Hi!

I'm using TeamCity as CI server and I want to build Docker image in order to push it to private Docker Registry but I got an error message: `file could not be downloaded: failed to open stream: Connection timed out`. The file is existing.

Any ideas?

Thanks!

**Comment by IgorTimoshenko** [comment]
@alcohol, thanks you for your help :)

**Comment by alcohol** [comment]
Insufficient information to provide any help. Does not look satis related. Thread went idle. Closed due to inactivity.

**Comment by IgorTimoshenko** [comment]
@alcohol, maybe, but you didn't ask anything and just closed the issue. Actually, I've found the resolution and it's not related to satis
