### ISSUE TITLE
git ssh repos in index.html

### ISSUE THREAD

**Issue by glensc** [composer/satis#311]
so, i put some git repo to satis.json:

`git@github.com:composer/satis.git`

satis will scan it via ssh, etc. but html it generates would be vcs link as:

```
<a href="git@github.com:composer/satis.git" title="5aa6fd7833019ffe0f09d7d794a34af2ab77450f">dev-master</a>
```

meaning browser will treat this as relative url, and the link would be:

```
https://satis.example.org/git@github.com:composer/satis.git
```

the alternative way to specify git links that are absolute and understood by git and browser would be to prefix with `ssh://` and change colon to slash:

`ssh://git@github.com/composer/satis.git`

this way the links in generated html won't be relative

**Comment by glensc** [comment]
so, satis should fixup such urls when generating html pages, those git@foo urls are what most git web interfaces expose (checked github, gitlab)

**Comment by patzerr** [comment]
The solution from glensc worked here as well.

So when generating the satis.json we had to change the URLs.
The alternative would have been to not generator anchor-tags in the twig-template.
See:
https://github.com/composer/satis/blob/master/views/package.html.twig#L94-L96

**Comment by alcohol** [comment]
We welcome pull requests :-)

**Comment by patzerr** [comment]
I don't know why links/anchor-tags are generated in the first place by "Rob Bast" in 3892972ff3d094c1937a1300a890609794ccbc58.

**Comment by alcohol** [comment]
I am not sure why you felt like you had to quote my name when referencing a commit I made, or how it is relevant to this topic. The purpose of anchor tags is rather straight forward. They let you link directly to a specific package on the page.

**Comment by patzerr** [comment]
Didnt know it was your name, just saw it in the history.

I am talking about anchor-tags for the "Release" URLs.
Maybe it makes sense for version.distType but as this issue shows, maybe not for version.sourceUrl

**Comment by glensc** [comment]
@patzerr 

Don't link to branches!
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
- hit `y`
- and perhaps https://github.com/josephfrazier/octopermalinker
