### ISSUE TITLE
Array found but object required

### ISSUE THREAD

**Issue by drabajs** [composer/satis#316]
I am getting this error message: "require : Array value found, but an object is required".
Require should be an array containing objects, Isn't it a bug? My require key contains data according to the doc.

**Comment by alcohol** [comment]
It would help if you actually showed us your configuration.

**Comment by stof** [comment]
no, ``require`` is a map, not an array. and maps are objects when being represented in JSON.

**Comment by drabajs** [comment]
I see, the generator I've found is creating wrong config, where it is sets default require value as [] and I make a mistake in changing the repository where it is an array for require, I am sorry. This issue can be closed.
