### ISSUE TITLE
[Question] Can I locally host packages with satis? (Not using an VCS)

### ISSUE THREAD

**Issue by mooror** [composer/satis#321]
Hey there, First off I want to apologize if this is not the proper place to post questions, I did not know of anywhere else I could post a question for you. Now, on with the main event! My question is can I use satis with locally hosted packages (stored as zip files). The composer documentation seems to indicate that something like this is possible with a `composer` repository with something like this: 
```
{
    "packages": {
        "vendor/package-name": {
            "dev-master": {
    "name": "smarty/smarty",
    "version": "3.1.7",
    "dist": {
        "url": "http://www.smarty.net/files/Smarty-3.1.7.zip",
        "type": "zip"
    }
} 
    }
}
```

However a) im not sure if this is a composer only thing, and b) if satis can do this I have no idea how. All the examples I have seen for satis seem to use the VCS type so I thought I would ask you about it. 

P.s. The composer example code that I posted above is from [here](https://getcomposer.org/doc/05-repositories.md#composer)
Thanks in advance,
Mooror

**Comment by astorm** [comment]
@mooror Try the following top level configuration node in your `satis.json` file.

    "archive": {
        "directory": "dist",
        "format": "tar",
        "prefix-url": "http://your-satis-url.dev",
        "skip-dev": true
    }

**Comment by alcohol** [comment]
Yes, it is possible. But you will have to provide the metadata for each individual zip file in your satis configuration, according to the Composer repository for a package specification.

**Comment by alcohol** [comment]
See https://getcomposer.org/doc/05-repositories.md#package-2

**Comment by alcohol** [comment]
If you use the artifact approach, you shouldn't need to specify the metadata in your configuration, as long as each zip file contains the composer.json as mentioned in the documentation.

**Comment by mooror** [comment]
Thank you so much for the quick answers. I actually had just came across artifacts and had come to the same conclusion. Now my question is, can I use artifacts with satis and if so, would there be any real benefit to using them together?

Thanks a ton,
Mooror

**Comment by alcohol** [comment]
Yes you can use Satis with artifacts. The benefit would be that you could use Satis also to proxy public packages, making them available internally, which could significantly increase performance for your CI environments for example.

**Comment by mooror** [comment]
Ah ok, that makes sense. The ability to proxy public packages is definitely a great option to have. Now from what I understand of Artifacts it seems that they must be called to in each projects composer.json manually. Would using satis allow me to only call the artifacts repository in the satis.json and then use the command line to install those artifacts into each project?

Thanks,
Mooror

**Comment by alcohol** [comment]
No. You have to add them to each individual package requirements. You can use the command line for that; `composer require some/artifact` (as long as your satis repository is added as a repository to your project composer.json or global config).
