### ISSUE TITLE
Can't Mirror Archives for apigen/apigen on OS X

### ISSUE THREAD

**Issue by astorm** [composer/satis#322]
I've got the following satis.json (actually named `satis-api.json`, in case that matters)

    {
        "name": "Creating a Magento 2 Mirror",
        "homepage": "http://composer.pulsestorm.dev",
 
        "repositories": [
            { 
                "type": "composer", 
                "url": "https://repo.magento.com" 
            },
            {
                "type": "composer",
                "url": "https://packagist.org"
            }
        ],
        "require": {
            "apigen/apigen": "*"
        },
        "archive": {
            "directory": "dist",
            "format": "tar",
            "prefix-url": "http://composer.pulsestorm.dev",
            "skip-dev": true
        }    
    }

If I run 

    $ php bin/satis build satis-api.json public_api -vvv

Satis eventually halts with the following error

    Dumping 'apigen/apigen'.
      - Installing apigen/apigen (v2.8.1)
    Downloading https://api.github.com/repos/apigen/ApiGen/zipball/bca0954e92621a48c6870be57115026a8d032706
        Downloading: 100%         
    Writing /Users/alanstorm/.composer/cache/files/apigen/apigen/217014fdea6f80b43cc599dc7cb1e830f37f689f.zip into cache from /var/folders/t_/9fbkrtf13cvfczzy2myg539w0000gn/T/composer_archive5701ed52a53df/1563f0c4b67822c6042a6c22e5f8addb
        Extracting archive
    Executing command (CWD): unzip '/var/folders/t_/9fbkrtf13cvfczzy2myg539w0000gn/T/composer_archive5701ed52a53df/1563f0c4b67822c6042a6c22e5f8addb' -d '/Users/alanstorm/Sites/satis-magento2-mirror.dev/satis/vendor/composer/7c1b49a3' && chmod -R u+w '/Users/alanstorm/Sites/satis-magento2-mirror.dev/satis/vendor/composer/7c1b49a3'

                                                                                   
      [ErrorException]                                                                 
      ZipArchive::extractTo(/Users/alanstorm/Sites/satis-magento2-mirror.dev/satis/ve  
      ndor/composer/7c1b49a3/ApiGen-ApiGen-bca0954/apigen): failed to open stream: Is  
       a directory                                                                     
                                                                                   

    Exception trace:
     () at /Users/alanstorm/Sites/satis-magento2-mirror.dev/satis/vendor/composer/composer/src/Composer/Downloader/ZipDownloader.php:81
     Composer\Util\ErrorHandler::handle() at n/a:n/a
     ZipArchive->extractTo() at /Users/alanstorm/Sites/satis-magento2-mirror.dev/satis/vendor/composer/composer/src/Composer/Downloader/ZipDownloader.php:81
     Composer\Downloader\ZipDownloader->extract() at /Users/alanstorm/Sites/satis-magento2-mirror.dev/satis/vendor/composer/composer/src/Composer/Downloader/ArchiveDownloader.php:43
     Composer\Downloader\ArchiveDownloader->download() at /Users/alanstorm/Sites/satis-magento2-mirror.dev/satis/vendor/composer/composer/src/Composer/Downloader/DownloadManager.php:199
     Composer\Downloader\DownloadManager->download() at /Users/alanstorm/Sites/satis-magento2-mirror.dev/satis/vendor/composer/composer/src/Composer/Package/Archiver/ArchiveManager.php:150
     Composer\Package\Archiver\ArchiveManager->archive() at /Users/alanstorm/Sites/satis-magento2-mirror.dev/satis/src/Composer/Satis/Builder/ArchiveBuilder.php:83
     Composer\Satis\Builder\ArchiveBuilder->dump() at /Users/alanstorm/Sites/satis-magento2-mirror.dev/satis/src/Composer/Satis/Command/BuildCommand.php:186
     Composer\Satis\Command\BuildCommand->execute() at /Users/alanstorm/Sites/satis-magento2-mirror.dev/satis/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
     Symfony\Component\Console\Command\Command->run() at /Users/alanstorm/Sites/satis-magento2-mirror.dev/satis/vendor/symfony/console/Symfony/Component/Console/Application.php:874
     Symfony\Component\Console\Application->doRunCommand() at /Users/alanstorm/Sites/satis-magento2-mirror.dev/satis/vendor/symfony/console/Symfony/Component/Console/Application.php:195
     Symfony\Component\Console\Application->doRun() at /Users/alanstorm/Sites/satis-magento2-mirror.dev/satis/src/Composer/Satis/Console/Application.php:53
     Composer\Satis\Console\Application->doRun() at /Users/alanstorm/Sites/satis-magento2-mirror.dev/satis/vendor/symfony/console/Symfony/Component/Console/Application.php:126
     Symfony\Component\Console\Application->run() at /Users/alanstorm/Sites/satis-magento2-mirror.dev/satis/bin/satis:9

    build [--repository-url[="..."]] [--no-html-output] [--skip-errors] [file] [output-dir] [packages1] ... [packagesN]

This appears to be a problem with the archive containing both an `apigen` and and `ApiGen` folder, and some combination of OS X, PHP, and ZipArchive not liking that. If I manually download the archive and unzip it on OS X, I'm prompted about the folder

    replace ApiGen-ApiGen-bca0954/apigen? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
    error:  cannot delete old ApiGen-ApiGen-bca0954/apigen

If I manually download the archive and unzip it a linux or BSD system, the archive extracts successfully.

I'm not sure how Satis should handle this sort of "everyone's and no one's fault" problem, but having the entire build crash because of this error doesn't seem like a good thing.

Thanks for your time/attention!

**Comment by alcohol** [comment]
I am guessing you don't use the case sensitive version of the apple file system? I personally always do a clean install whenever I get a new Mac and make sure that it uses HFS+ with case sensitivity. Not sure though if this is a Satis issue, or actually a Composer issue. Any idea @seldaek ?

**Comment by astorm** [comment]
@alcohol -- was this issue fixed and closed, or closed as wontfix?

**Comment by alcohol** [comment]
It's a matter of case-sensitivity, like I explained. Very edge-case scenario. Not much to fix here.

**Comment by astorm** [comment]
@alcohol Right, I understand the reason for the issue -- it's right there in my bug report, but shouldn't Satis handle this more gracefully?  There's a large number of people who use PHP natively (non-VM) on case insensitive OS X and Windows systems.  

Ideally Satis should be able to handle this -- it's an edge, yes, but an edge case that blocked at least one real world PHP developer (me!) from being able to use Satis on a real world project.

It's easy enough to punt this off on the Satis user for having a "bad" file system, or the package creator for setting up a potentially sketchy package, but those are the conditions in the world, and a good tool can/should work with those. 

Even if you don't think Satis should work hard to work around this issue, it seems like a pretty fragile thing to completely **halt** mirroring because of one bad package. 

I get you might not want to personally work on this, but someone else in the community might -- either right away, or at some point in the future.  Closing the issue out sense a clear (if unintentional) message not to work on this, or not to issue a pull request for it. 

It seems worth fixing, or at least worth working around.

At the end of the day -- your project, your call, but dismissing this as a `WONTFIX` edge case seems like the wrong choice.

**Comment by alcohol** [comment]
I understand that it would be nice to have a solution for this. But it is better to clearly identify and state the issue + offer a possible solution, in a new Github issue. That way if anyone else stumbles upon it, they don't have to read through a whole discussion to figure out what the issue actually is, and how it perhaps could be solved.

While I do not see a way to fix the issue regarding conflicting names of directories and files due to case-insensitivity, your other proposal (add an option to proceed on failure), sounds fair. But if I am not mistaken, the latter is actually already possible using the `--skip-errors` flag.

**Comment by stof** [comment]
Well, AFAICT, there is nothing Satis could do here (except ignoring this package and mirroring others, which is already possible with ``--skip-errors``).
The issue is on Apigen's side: the fact that they have folder names differing only by the case makes their repository incompatible with case insensitive filesystems (which means Mac by default and Windows).

**Comment by astorm** [comment]
Fair enough guys -- I'm not sure why Satis can't just grab the archived package without unspooling/re-spooling if it hits an error condition, but your project, your choices. 

Best wishes!

**Comment by alcohol** [comment]
I don't understand. It can do exactly that if you pass the `--skip-errors` flag. Why do you keep ignoring this fact?
