### ISSUE TITLE
Files missing from dist archive

### ISSUE THREAD

**Issue by marcaube** [composer/satis#324]
I've hit a weird problem with [an old package](https://github.com/leafo/scssphp/tree/v0.0.7), not sure if it's an issue with Satis or with the package, but one of the files in the library is missing from the dist archive created by Satis. The file is present in the archive created by GitHub though.

I've created a small project to reproduce the issue, simply checkout the [missing-files-bug branch](https://github.com/marcaube/satis/tree/missing-files-bug) and check the content of the zip archive in `public_html/dist/`.

Compare that with the files in [the project](https://github.com/leafo/scssphp/tree/v0.0.7) and you can see that `scss.inc.php` is missing from the archive. If you check in the [GitHub archive](https://github.com/leafo/scssphp/archive/v0.0.7.zip), `scss.inc.php` is present.

At first I thought it could be an issue with something in `.gitattributes` but I can't pinpoint the problem.

**Comment by alcohol** [comment]
Correct, it is ignored due to the .gitattributes entry for `/*.php`.

**Comment by marcaube** [comment]
@alcohol even if the file is committed to the repo ? That seems odd.

**Comment by glensc** [comment]
do not confuse `.gitattributes export-ignore` and `.gitignore`. if satis exports archive via github api, then `.gitattributes` exclusion is handled by github. if satis additionally parses `.gitignore`, that i do not know, but i do not see why it should as there's `archive.exclude` `composer.json` attribute for that.

also you can commit files which are in `.gitignore` using `-f` option or just commit the file first and then modify `.gitignore`

**Comment by alcohol** [comment]
Satis uses the archiving capabilities of Composer if I am not mistaken, and those in turn use the [`GitExcludeFilter`](https://github.com/composer/composer/blob/master/src/Composer/Package/Archiver/GitExcludeFilter.php) among other features.

**Comment by marcaube** [comment]
@glensc it's not my package, so I have no control over what's committed to the repo and what's excluded. I choose it as an example, because it's a problem we face when we install dist dependencies from Satis in one of our projects. Installing dist deps from GitHub is fine though.

@alcohol You may have hit the nail on the head right there. I'm going to remove Satis from the equation and try with composer directly.

**Comment by alcohol** [comment]
@marcaube that will not reveal much, since a Composer install either does a checkout of the tag (`--prefer-source`), or unpacks the tarball that Github creates (`--prefer-dist`). Neither of those approaches will result in said specific file being missing.

**Comment by marcaube** [comment]
```bash
$ composer archive leafo/scssphp 0.0.7
Searching for the specified package.
Found an exact match leafo/scssphp v0.0.7.
Creating the archive into ".".
  - Installing leafo/scssphp (v0.0.7)
    Downloading: 100%         

Created: ./leafo-scssphp-e5a79218c349cbc03dc99004fbad938c7b82391f-zip-0db3e8.tar
```

Open the archive and... as expected, the file is missing.

**Comment by alcohol** [comment]
Correct :-)

**Comment by marcaube** [comment]
Well, it has little to do with Satis then, and it seems like this behaviour is *by design* in the archive command of Composer. I found an issue relating to that very problem composer/composer#3733, so I'm closing here.

Thanks for the help!

**Comment by Seldaek** [comment]
Seems correct to me.

**Comment by mykeetm** [comment]
Hello,

could somebody add  "ignore filters option" to config (archive or repository) json for this feature? https://github.com/composer/composer/pull/6062

thank you
