### ISSUE TITLE
Is it possible to require several dev-xxx versions plus tag versions ? 

### ISSUE THREAD

**Issue by bgaillard** [composer/satis#326]
Hi, we currently have a Jenkins build with a satis update job which pulls every packages in all versions and all repos (we use `require-all`). 

I would like to speed-up the satis updates by selecting only specific versions of my libraries, as explained in the docs I have several options to specify my versions https://getcomposer.org/doc/articles/versions.md#stability. 

But, il my case I would like satis to pull the following versions on my `company/package` library : 
* `~1.88` 
* and `dev-master`
* and `dev-develop`
* and `dev-new`

I do not want to pull versions `<1.88`, so ideally I would like to do something like that.
```json
"require" : {
    "company/package" : "~1.88 AND dev-master AND dev-develop AND dev-new"
}
```

Is it possible to do it with satis ? 

I think our use case is very common, we have a stable library in version `~1.88` which is in production. 

Because we use the git flow workflow (https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) we use the `dev-develop` and `dev-master` branches to release new production versions. In the same time we are preparing a new version of our library on a `dev-new` branch. 

Problem is that `require-all` it too slow for us because we have lot of libraries which more that 50 tags / versions each.

**Comment by bgaillard** [comment]
Oups sorry I close this issue its really easy to do what I want, the following configuration works.
```
"require" : {
    "company/package" : "~1.88 || dev-develop || dev-master || dev-new"
},
```

**Comment by alcohol** [comment]
Your code sample is logical `OR` though, whereas you originally asked for `AND`. Are you certain this resolved your issue?

**Comment by bgaillard** [comment]
Hi @alcohol  and thanks for your reactivity, 

Not 100% sure but in the context of Satis we want satis to store packages so their are no real difference between `AND` and `OR` in this context ?

I mean...
```json
"require" : {
    "company/package" : "~1.88 || dev-develop || dev-master || dev-new"
},
```

and...

```json
"require" : {
    "company/package" : "~1.88 dev-develop dev-master dev-new"
},
```

should both store the same versions in Satis ? Is this reflexion correct ?

I did not test the second version with `AND` but if its important to check it I can do it.

**Comment by stof** [comment]
@alcohol if you read the explanation about what he wants to do rather than reading the suggested constraint, you will see that the needed requirement is a OR. He wants to include both versions of the package, which means versions matching a OR constraint of these versions, not a AND constraint (which would not match anything as a version cannot be ``dev-master`` and ``dev-develop`` at the same time)

**Comment by alcohol** [comment]
@stof I know.

@bgaillard no it's fine :-)
