### ISSUE TITLE
How the heck we pronounce SATIS?

### ISSUE THREAD

**Issue by phackwer** [composer/satis#330]
Greetings,

Around me there is a bunch of people pronouncing it as we pronounce satisfaction. And there is some bunch of other people saying that "satis" has a latin root which means the "a" sounds like the latin "a".

What is the right pronunciation?

**Comment by alcohol** [comment]
Well first of all, it's not written in all-caps as far as I know. So, Satis, not SATIS. Secondly, I think you can pronounce if however you want. But the 'satis' in satisfaction is probably the right pronunciation.

/cc @Seldaek want to weight in here, or? :p
