### ISSUE TITLE
Show errors on rendered html

### ISSUE THREAD

**Issue by garygreen** [composer/satis#333]
If it fails silently (due to json parse errors etc) you don't know why unless you check the logs / run command manually on server.

**Comment by alcohol** [comment]
I actually do not see any purpose or utility in this feature request. Errors should not end up in the generated html output.

**Comment by garygreen** [comment]
@alcohol it's particularly useful if you use the satis html to see the packages that it has pulled down / updated, or use it as a general status page. At the moment, if satis fails for whatever reason, it will not show such a status and will technically be giving you false view. It's a very useful feature imo, it's not about "errors should not end up in the generated html output" it's about providing the actual status of the statis build -- whether that was successful or not, and why it was not successful is a part of that imo.

**Comment by alcohol** [comment]
The output of the build command is for that.

**Comment by garygreen** [comment]
> The output of the build command on the console is for that.

I doubt anyone is running satis command manually every time and will therefore see any potential errors. I've only run satis from a cron task - unless I put something in place that will send an email of the error logs or something then I'll never know, until something doesn't look right and I manually have to go and check. 

One time I was struggling to work out why my satis wasn't updating -- turned out we had a problem in one of our projects composer json and it failed updating satis. It took waaaaay longer to figure out why it failed than it could have had there of been a message on the HTML page. It would have made it so much easier to see the true status of the build.

**Comment by alcohol** [comment]
I'm not saying that error reporting could not be improved. I'm just saying that it does not belong in the generated html output. It simply has no place there.

**Comment by stof** [comment]
@garygreen using the HTML page to report the build status would still mean that you would have to deploy the result of a broken build (but hopefully deploying it only partially so that consumers can at least get the old package info rather than getting a broken repository). This is why it is clearly not the place to report errors.
If you have a cron job building Satis regularly, you should have this same cron job report errors when Satis exits with a non-0 exit code.

**Comment by garygreen** [comment]
>using the HTML page to report the build status would still mean that you would have to deploy the result of a broken build

That's absolutely not what I'm suggesting.  It should not deploy a partial build. This suggestion merely serves as a tool for letting you know the last satis build failed and why it failed, so you are visually aware something is not right and what need's to be fixed in order for satis to build properly. Right now you have to go through log files to see, or hope that satis is update to date.

> If you have a cron job building Satis regularly, you should have this same cron job report errors when Satis exits with a non-0 exit code.

But why can't it report (in a nice red box) on the html page the last error? It would make it obvious when your browsing your generated packages if it is update to date, failed the last build, etc. Of course you can setup something that reports when satis exists with non-0 exit code but that involves having to actually setup some kind of reporter - there already is a reporter in place for the status of satis, it's called the generated HTML. It IS the status of the build and the packages. I see absolutely no problem in adding a visual hint for the build status, whether that means built successfully, failed to build, etc.

**Comment by stof** [comment]
> That's absolutely not what I'm suggesting. It should not deploy a partial build. This suggestion merely serves as a tool for letting you know the last satis build failed and why it failed, so you are visually aware something is not right and what need's to be fixed in order for satis to build properly. Right now you have to go through log files to see, or hope that satis is update to date.

If you don't deploy the new index.html file, how would you see that ? And if you deploy only the updated index.html, it is a partial deploy. If you replace the whole deployed files, it means that the repository is not usable anymore (as old metadata are gone, and new metadata are broken)

**Comment by stof** [comment]
> there already is a reporter in place for the status of satis, it's called the generated HTML. It IS the status of the build and the packages.

That's wrong. The generated HTML file is not a build reporter. It is one of the assets of the generated repository (the UI telling people using this repository what they can find in it, so that they don't have to read the JSON metadata to figure it).

**Comment by garygreen** [comment]
It shouldn't update the meta data, instead if would update some kind of `status.json` with the error message in which the HTML file could include and use it to determine when to show the error of the last build. That's one way it could be done, without touching the meta data or 'partial' update.

> That's wrong. The generated HTML file is not a build reporter. It is one of the assets of the generated repository (the UI telling people using this repository what they can find in it, so that they don't have to read the JSON metadata to figure it).

That's true if you only use satis in a build-on-demand like fashion. Most do not. Most setup a cron task to have it doing it's own thing in the background - in that instance I personally see the generated HTML as a near real-time presentation of the status of satis, the "human friendly" control panel if you will. If statis fails, I would expect to see it on there and why it fails - I see value in that.

**Comment by stof** [comment]
@garygreen well, the index.html is not a control panel. It is what is displayed to users of your repository when they access it. For instance, https://packages.zendframework.com/ shows everyone in the world which packages are available in the Satis repository hosted there.
This is why there are features like showing how to register the repository in your project or searching packages btw.

> Most setup a cron task to have it doing it's own thing in the background

Even if it is a cron task in the background, it does not mean that this cron task is forced to be running in the deployed instance directly (btw, if you do, your building is not atomic, and so you might have a broken deployment during the generation, which might take some time if you generate archives). This is equivalent to saying that your deployment task for your prod website is ``git pull && composer install --no-dev`` in the live server...
If you want a safe build, you could have the cron job build in a new folder (sharing the archive output folder through symlinks to avoid regenerating archives already available from a previous build) and the swapping the symlink used by the document root of your webserver to make it point to the new folder (and then deleting the old unused folder).

Making Satis treat the index.html file as a reporting file would encourage such setup.

**Comment by garygreen** [comment]
> Even if it is a cron task in the background, it does not mean that this cron task is forced to be running in the deployed instance directly (btw, if you do, your building is not atomic, and so you might have a broken deployment during the generation, which might take some time if you generate archives). This is equivalent to saying that your deployment task for your prod website is git pull && composer install --no-dev in the live server...

Well that makes the status displayed on the HTML page even more important. I didn't realise that if satis failed it has now partially deployed.

> Making Satis treat the index.html file as a reporting file would encourage such setup.

It doesn't really encourage anything, it just serves as a visual hint that 'everything is ok' - just like in travis, or whatever CI tool you use - satis builds stuff and if the build fails, imo it should allow the user to know that. The easiest, least friction way of displaying that is in the already generated HTML status page for satis. Anyway, I get the impression your not fond of this idea, meh.  I'd find it useful, would be nice to see others thoughts on it too.

**Comment by stof** [comment]
@garygreen except that CI tools have reporting UI, which are meant to report the build of CLI tools being run for the build. Satis is **not** such a CI tool. It is a CLI tool generating assets to be deployed. The "CI" tool in your case is the cron job itself, not Satis.
If your CI tool publishes build assets to a continuous deployment pipeline, you don't expect it to sent the build failure logs to this same pipeline. But this is exactly what you are asking your Satis setup to do.

> It doesn't really encourage anything

It encourages having a setup leading to a partial deployment on failure rather than an atomic deployment, because the *only* way to have a new index.html file appearing with the failures on the live server is to have a partial deployment. If you make atomic deployments, the index.html of the broken build will never become live.

> it should allow the user to know that.

IMO, the user does not care that the build failed, as they can do nothing about it. They care about the last update date, and this is displayed.
The ones care about the build failures are the maintainers of the repository.

> Well that makes the status displayed on the HTML page even more important. I didn't realise that if satis failed it has now partially deployed.

it depends at which point it failed actually. Depending of the failure, it could be before Satis started generated new stuff at all (in which case it has not replaced anything).

**Comment by garygreen** [comment]
> except that CI tools have reporting UI, which are meant to report the build of CLI tools being run for the build. Satis is not such a CI tool. It is a CLI tool generating assets to be deployed. The "CI" tool in your case is the cron job itself, not Satis.

**reporting tool definition**

> Reporting tools are software applications that make data extracted in a query accessible to the user. For example, a “dashboard” is a common reporting tool that makes a variety of information available on a single screen, in the form of charts, graphs, ordered lists, etc.
> Ref: http://businessintelligence.com/dictionary/reporting-tool/

In the case of satis, the reporting tool is the friendly HTML GUI. To say that the reporting tool is the CLI would be a bit of a skewed view on what a reporting tool actually is.

> It encourages having a setup leading to a partial deployment on failure rather than an atomic deployment, because the only way to have a new index.html file appearing with the failures on the live server is to have a partial deployment. If you make atomic deployments, the index.html of the broken build will never become live.

Incorrect. As I mentioned a few comments up, there is a way to have partial deployment whilst still reporting that the last satis build failed, for whatever reason.

> IMO, the user does not care that the build failed, as they can do nothing about it. They care about the last update date, and this is displayed.

I care. Satis failed because a syntax error in one of your packages? Couldn't connect to server because ssh keys configured wrong? SSL not configured right? You can do something about it. And it would be easier and quicker to see what you need to fix if it's there in front of you, rather than digging through logs or running the command manually each time.

> The ones care about the build failures are the maintainers of the repository.

I agree with you on this - I am seeing this all from a view of a package maintainer, it may not be as useful information to someone who can't do anything about it.

**Comment by aaukt** [comment]
We are using Jenkins to run the satis build, so if it fails the build fails and you have multiple notification options, even if you are just using cron there are possibilities.

Anyway, you can always do what you suggested and dump the build output into a file that you can load however you like on the repo index (iframe, ajax, ...), but i don't think it should be included as a default, because most of the time the "normal" users can't do anything about it. Als some people have satis repositories in the public, so showing errors might be a security concern.

**Comment by stof** [comment]
> In the case of satis, the reporting tool is the friendly HTML GUI. To say that the reporting tool is the CLI would be a bit of a skewed view on what a reporting tool actually is.

Satis is a tool generating a static website (exposing both JSON metadata for composer and a UI for humans). The index.html is **not** the build reporting. It is part of the build assets. The CLI output is the build report.
There is nothing in the definition of reporting saying that the report must be in HTML format

> I care

**you** care. Users of your repository don't, as they cannot solve the build issue. You are the maintainer of the Satis repository, not only a user of it. The paragraph you replied too was talking about users of the repository, which are the one for which the index.html is meant to be.

**Comment by garygreen** [comment]
> Anyway, you can always do what you suggested and dump the build output into a file that you can load however you like on the repo index (iframe, ajax, ...), but i don't think it should be included as a default

I think this is the key point. It's possible to do, and it would be useful -- but only to package maintainers, so it wouldn't be a one size fits all and maybe therefore more trouble that it's worth. Thanks for chipping in 😄

**Comment by stof** [comment]
@garygreen btw, Satis is much more similar to Jekyll than to Travis. It is also a static content generator (but specific to some kind of content).
Would you expect github pages to replace the index.html of your website by the Jekill build logs when the build fail ?
