### ISSUE TITLE
include-filename not working

### ISSUE THREAD

**Issue by Rudloff** [composer/satis#335]
Hello,

The _include-filename_ parameter seems to be ignored.

**Comment by glensc** [comment]
isn't that great then?

really: describe what you were doing, what's your config, whats your commandline, as much details as possible to be able to understand what are you doing.

**Comment by alcohol** [comment]
I think he is correct.

https://github.com/composer/satis/blob/d3cb8f4f93fa42e6363824d794c853edd097714e/res/satis-schema.json#L108-L111

I can't find any code that actually uses this config argument/definition. Seems to me default filename actually cannot be overruled.

It is also set in the class here, but never actually used: https://github.com/composer/satis/blob/c41456ad18a5b104ee531aca26c921e1f474ab49/src/Composer/Satis/Builder/PackagesBuilder.php#L47

**Comment by Rudloff** [comment]
Sorry, I was a bit in a hurry when I submitted the bug.

Here is my satis.json file:
```
{
	"name": "MediaWiki Packagist",
	"homepage": "https://mwpackagist.netlib.re/",
	"repositories": [{
		"type": "vcs",
		"url": "https://github.com/wikimedia/mediawiki.git"
	}],
	"require-all": true,
	"output-html": false,
	"output-dir": ".",
	"include-filename": "cache/core.json"
}
```

I am using the latest commit from master.
When I run `satis build`, it still creates a file like *include/all$a20894c4524cb60e8c38c71d0a251b9865ea70f6.json*.

It seems the filename is set here: https://github.com/composer/satis/blob/master/src/Composer/Satis/Builder/PackagesBuilder.php#L85
As @alcohol said, it does not use the `includeFileName` property set in the constructor.

**Comment by glensc** [comment]
should be bisected then, it was working when initially added in #292 (9e8ef8e)

**Comment by glensc** [comment]
by looking [PackagesBuilder.php history](https://github.com/composer/satis/commits/c41456ad18a5b104ee531aca26c921e1f474ab49/src/Composer/Satis/Builder/PackagesBuilder.php), i'd say #295 broke it.
