### ISSUE TITLE
Possible Bug: Missing Tags

### ISSUE THREAD

**Issue by infabo** [composer/satis#341]
According to https://github.com/wirecard/magento-wcp.git the repository has 3 releases/tags.
But this is not represented in Satis. Using the latest available Satis.
Another one which is failing: https://github.com/winkelsdorf/magento-autocomplete

![newtown repository composer repository](https://cloud.githubusercontent.com/assets/3999104/16690505/9d01476a-4528-11e6-946e-97cc6f03b3bb.png)

Already tried: removed ~/.composer/cache.

**Comment by infabo** [comment]
https://api.github.com/repos/wirecard/magento-wcp/tags

**Comment by stof** [comment]
These tags don't have any composer metadata (there is no composer.json in them), so Composer cannot use them (it cannot know what the requirements are for this version, and so on).

**Comment by stof** [comment]
btw, it you run Satis in verbose mode, it will probably tell you about this issue

**Comment by infabo** [comment]
@stof You're perfectly right. Thanks for the explanation!
