### ISSUE TITLE
<small>¶</small>

### ISSUE THREAD

**Issue by luckyraul** [composer/satis#342]
Can some one describe why you use such symbol here ??

https://github.com/composer/satis/blob/master/views/index.html.twig#L47 

It looks weird
![schermata 2016-07-12 alle 11 40 55](https://cloud.githubusercontent.com/assets/7735520/16760681/f0b200e0-482d-11e6-812d-e3cf6a878259.png)

**Comment by alcohol** [comment]
This symbol is generally used in typography to denote (the start of) a paragraph. We use it as anchor links on the page.

Whether or not it looks weird is a personal opinion. Personally I think it could benefit from some whitespace between the package name and the symbol.

**Comment by kevindierkx** [comment]
@alcohol Why don't you use the package title for anchor purposes?

**Comment by alcohol** [comment]
I did not create the template. Satis is developed and maintained by the community. You are free to submit any changes you see fit. If they are reasonable, we will merge them without question. Design has a strong tendency to be motivated by personal preference however. So please do try to motivate your changes when you submit them :-)

**Comment by kevindierkx** [comment]
@alcohol Sorry my mistake should have looked through the issues and PRs beforehand, it looks like there wasn't really a founded discussion on this topic to start with: #172 #302 
I'll stop spamming this topic for now and open a new issue regarding the 'placement' of the anchor.

**Comment by glensc** [comment]
i think such anchor is rather typical, take look at and markdown file in github where are section headers.

**Comment by luckyraul** [comment]
Github use such anchors
![schermata 2016-07-12 alle 12 23 20](https://cloud.githubusercontent.com/assets/7735520/16762038/df35c724-4833-11e6-81be-b7b68e0b3a55.png)
