### ISSUE TITLE
Auto-hide package 'anchor' on the package title instead of appending an extra element

### ISSUE THREAD

**Issue by kevindierkx** [composer/satis#343]
In response to #342.
PRs #172 and #302 added a little symbol to support page anchors. This is great however, in their current form, they add extra bloat to the page.

GitHub supports something similar on their wiki pages bij prefixing an anchor element with a fancy chain icon and hiding it by default. The anchor wil only pop up when the user is hovering over the title.

My suggestion would be to move the anchor to the front and do something similar as GitHub does with the hover states.

![screen shot 2016-07-12 at 11 22 54](https://cloud.githubusercontent.com/assets/2406615/16762023/085bfe0e-4823-11e6-980c-a6550dc47c08.png)

**Comment by alcohol** [comment]
Like I said in the referenced issue, Satis development depends entirely on its community. As much as we appreciate issues with feature and/or change requests, in the end, if you want to see something changed, your best chance of success is submitting the change yourself :-)

Just letting you know as an FYI.

**Comment by kevindierkx** [comment]
@alcohol Sure, but since a discussion was starting in the previous issue I think it's a good idea to give it a decent place for a discussion. When I have the time I will gladly create a PR. Or somebody else could do it, but without an issue there wouldn't really be a place to keep track of all the things people could do for the project and who is doing it. To prevent confusion, and wasting other peoples time, creating the issue is the least I could do for now.

**Comment by alcohol** [comment]
I was definitely not disputing that. Just wanted to make sure you did not have idle hopes that someone else would pick this up anytime soon :-)

**Comment by kevindierkx** [comment]
That's the whole reason I've became a developer, all hope is gone... 😛

**Comment by kevindierkx** [comment]
@alcohol All joking aside, found some time and fixed it: #345
The inline SVG is from GitHubs Octicons, those are released under the MIT license.

**Comment by glensc** [comment]
doesn't such inline make this satis output html bigger? the `<svg>...</svg>` markup is repeated for each package.

**Comment by alcohol** [comment]
Feel free to submit a PR that "optimizes" this solution.

**Comment by kevindierkx** [comment]
@glensc: Better solution would be to make an actual SVG instead. However there isn't a place for assets at the moment.
