### ISSUE TITLE
Failed to run on Windows, packed by box.

### ISSUE THREAD

**Issue by garrydzeng** [composer/satis#346]
I got bellow error:
```
[ErrorException]
hash_file(phar://.../satis.phar/vendor/composer/ca-bundle/src/../res/cacert.pem): 
failed to open stream: phar error: "vendor/composer/ca-bundle/res/cacert.pem" 
is not a file in phar ".../satis.phar"
```

**Comment by alcohol** [comment]
Satis is not distributed as a phar. Your build seems broken. Try finding an up-to-date version or running from source.

**Comment by alcohol** [comment]
Oh, you mean if you pack it through box, it is missing essential files. I see now. My bad.

**Comment by alcohol** [comment]
Can you see if https://github.com/composer/satis/commit/56e3976301893dc89838380fa4b81024a5ac602c fixes it?

I don't have access to a proper dev machine right now so cannot test myself.

**Comment by garrydzeng** [comment]
@alcohol it works, thank you !

**Comment by alcohol** [comment]
Great. Closing this issue then. But feel free to reply here if you run into any more issues regarding the Box packing process.
