### ISSUE TITLE
[Documentation Request] How to implement API token auth

### ISSUE THREAD

**Issue by bkuhl** [composer/satis#352]
The documentation references using an API-Token header to authentication with Satis.  There's not any mention of how to go about implementing this or what tooling/approaches might be useful.  Could more detail on this topic be added to the [security section of this article](https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md#security)?

**Comment by alcohol** [comment]
What do you mean?

**Comment by bkuhl** [comment]
See the 3rd example in https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md#security

**Comment by alcohol** [comment]
That is only supported if you implement it yourself. Satis has no such token authentication mechanism.

**Comment by alcohol** [comment]
Satis merely generates static content. It does not serve the content. As such, header authentication should be implemented by whatever you use to serve this content.
