### ISSUE TITLE
Github Webhook Integration

### ISSUE THREAD

**Issue by ChristianRiesen** [composer/satis#36]
Github has this wonderful feature of webhooks, which is beautifully generic. Now instead of running a satis update every 2 minutes, wouldn't it be much more convenient to run the update only when the webhook is called? Our installation has only a handful of repos in it, mostly libraries that change either multiple times in a day or then not for days or even weeks. So instead of running a cronjob every 5 minutes to ensure the packages.json is fresh, the webhook would be the ideal candidate for the task.

I'm currently working on creating something like this. I don't know yet how exactly I'll be implementing it, but I would love to hear input, so maybe I can publish my efforts here later.

**Comment by dbpolito** [comment]
Any updates on this one? I would love to see this feature too.

**Comment by lxlang** [comment]
:+1:

**Comment by alcohol** [comment]
Since Satis is a (command line based) build tool, and not an application that is actually web facing or exposes any kind of web based API, I do not see this fitting the scope of the project.
