### ISSUE TITLE
Only stores a limited number of versions

### ISSUE THREAD

**Issue by daften** [composer/satis#366]
When I include repositories with a large number of versions, on each satis build it starts again from a specific version. It seems only the latest 21 versions are stored.
An example satis file for which this happens with me:

```
{
    "name": "Digipolis Gent Packagist",
    "homepage": "http://packagist.gentgrp.gent.be",
    "repositories": [
        {
          "type": "composer",
          "url": "https://packagist.org/"
        },
        {
            "type": "vcs",
            "url": "https://github.com/sebastianbergmann/phploc.git"
        }
    ],
    "require-all": false,
    "require": {
        "phploc/phploc": "*"
    },
    "require-dependencies": false,
    "require-dev-dependencies": false,
    "archive": {
        "directory": "dist",
        "format": "tar",
        "skip-dev": true
    }
}

```

**Comment by aaukt** [comment]
Composer support was added in phploc starting version 1.7.3, any version before that will not be considered.

**Comment by alcohol** [comment]
What @aaukt said.

**Comment by daften** [comment]
Thanks.
Is there a way to make satis not scan already scanned tags again maybe? This could eat up a lot of time for each scan now.

**Comment by alcohol** [comment]
Not at the moment, as far as I am aware. Making use of caching helps speed up the process a little bit, but it will not incrementally scan, since we have to check also if older tags have been removed/deleted possibly.

**Comment by daften** [comment]
Was thinking of the older tags changing this weekend, thanks for the info!
