### ISSUE TITLE
Register additional archiver format

### ISSUE THREAD

**Issue by sabbelasichon** [composer/satis#370]
Hi, 
first of all, thanks for this great piece of code.

I would like to know, if it is possible to register an own format for the archive process?
Can´t see a possibility to hook into the  Composer\Factory::createArchiveManager method.
Any ideas?

**Comment by alcohol** [comment]
I don't believe so, but I could be wrong. What format are you looking to add?

**Comment by sabbelasichon** [comment]
Some kind of special old outdated format for CMS TYPO3 called t3x. Not very useful for others and for the future. 
What do you think: If i could provide a pull request so it is possible to add additional archivers during runtime? Chances to make it in the composer core or just a waste of time?

**Comment by alcohol** [comment]
It wont make it into Composer core (but this is the Satis repository).

**Comment by sabbelasichon** [comment]
Sorry, you are absolutely right. Anyways, thanks.
