### ISSUE TITLE
composer update 

### ISSUE THREAD

**Issue by babwar** [composer/satis#373]
Hello,

build is not working anymore after a composer update.
If i install from github and run the composer install (from the composer.lock), all is fine. If i run composer update. the build does not work anymore. This come from the composer library update.

**Comment by alcohol** [comment]
Please define, "does not work".

**Comment by babwar** [comment]
sorry, normally i hate people say "it doesn't work without explain what's wrong.

I've few private repository. My Satis Json : 
`{
    "name": "My repositories",
    "homepage": "https://my-repositories.com/",
    "repositories": [
        { "type": "git", "url": "ssh://git@git.my-repositories.com:4905/home/git/library/common.git" },
        { "type": "git", "url": "ssh://git@git.my-repositories.com:4905/home/git/library/other.git" },
        
        ...
    ],
    "require-all": true
}`

When i run composer install, the build command works fine : 
`php bin/satis build data/satis.json public`

After a composer update, the same command dosen't work. It try to check Packagist packages: 

`The contao-legacy/bit3basics * requirement did not match any package ...`

**Comment by alcohol** [comment]
`contao-legacy/bit3basics` does not exist on Packagist.

**Comment by babwar** [comment]
Yes ... but it's not on my json. I don't know where this package from

**Comment by alcohol** [comment]
Then maybe you should not use `require-all`.

**Comment by babwar** [comment]
require-all is only for the repositories i'have  in the json, no ? (take all branches)
I have only my libraries on the satis.json. And all works fine before running the composer update in satis folder. Like it dosen't found my satis.json

**Comment by alcohol** [comment]
No, it will also try to include all dependencies of every package it encounters.

**Comment by alcohol** [comment]
But honestly, if you want us to help, show us your real `satis.json`.

**Comment by babwar** [comment]
My json satis are ok. I'he only few packages referenced. The problem come from the composer update inside satis directory. J've make a copy of each package updated and replace then one by one. The problem come from the compser package itself : 

`Removing composer/ca-bundle (1.0.4)
Installing composer/ca-bundle (1.0.6)

Removing composer/composer (1.2.1)
Installing composer/composer (1.2.3)`

when i replace by the old one, all works fine

**Comment by stof** [comment]
Don't run composer update inside the Satis project. Composer ships its lock file, which are the dependencies with which Satis has been tested. Updating Satis dependencies to newer versions could indeed create issues (and so doing it involves the work of contributing to Satis, not just of using it)

**Comment by alcohol** [comment]
I just updated dependencies locally though. Everything works fine for me.

**Comment by babwar** [comment]
So i don't know. As it's working without updating packages, i let it like it is. I'll try to investigate more and try to see what's wrong and i'll tell you. 
Alcohol thanks for your time.

**Comment by alcohol** [comment]
Can you check if the latest version of satis solves this issue for you?

**Comment by babwar** [comment]
Yes it's ok now. Thanks again
