### ISSUE TITLE
Problem syncing composer.json data with satis

### ISSUE THREAD

**Issue by mooror** [composer/satis#376]
I'm having weird syncing issues were data from my package's composer.json file is not being added to satis when I do a rebuild. I have double checked that the files contain valid json and conform to the composer schema (as far as I can see). But I want you guys to have a look to see if you can spot anything. Heres my composer.json:
```
{
    "name": "system-administrator/sl-store",
    "description": "This silverstripe package enable us to install/uninstall composer add-ons from our private satis repository.",
    "version": "1.0.0",
    "type": "silverstripe-module",
    "homepage": "http://www.example.ca",
    "time": "2016-12-05",
    "authors": [
        {
            "name": "System Administrator",
            "email": "mooror@example.ca"
        }
    ],
    "support": {
        "email": "support@example.com",
        "issues": "https://bitbucket.org/example/sl-store/issues?status=new&status=open",
        "source": "https://bitbucket.org/example/sl-store/src"
    },
    "require": {
        "silverstripe/framework": "~3.3",
        "silverstripe/cms": "~3.3",
        "silverstripe/gridfieldajaxrefresh": ">=0.0.0",
        "colymba/gridfield-bulk-editing-tools": ">=2.1.8"
    },
    "keywords": [
        "example",
        "store"
    ]
}
``` 
and here is that satis's web view is displaying:

## system-administrator/sl-store
**This silverstripe package enable us to install/uninstall composer add-ons from our private satis repository.**

| Authors     | System Administrator |
|-------------|----------------------|
| Releases    | 1.0.0                |
| Required By | n/a                  |
| Requires    | n/a                  |

NOTE: A bit better :D

As you can see, the description, keywords, requirements and support links are all not displaying. Any help is appreciated.

Thanks in advance,
Mooror

**Comment by alcohol** [comment]
Do you use git tags? Cause you also have the version specified in your composer.json and you should never ever combine both. So please make sure you only use one or the other (and honestly, putting version in your composer.json is really counter productive).

Also,

```
| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |
```

| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |

**Comment by mooror** [comment]
To clarify, these are static packages that are stored in archives. They are not linked to any github or bitbucket repository (though some of them have been brought down from git as an archive). Therefor I do not believe git tags has anything to do with it.

Thanks for the quick reply,
Mooror
 
P.S. I agree that placing versions in composer.json files seems counter productive, however I believe it to be necessary due to the nature of our static repository.

**Comment by stof** [comment]
Can you show us your Satis config too ?

**Comment by alcohol** [comment]
Could it be that since it is an archive, Satis will not actually check for changes to the composer.json inside the archive once it has been downloaded already?

**Comment by mooror** [comment]
Here is my satis.json file contents:
```
{
  "name": "Example Repository",
  "homepage": "http://repository.example.ca",
  "repositories": [
      {
         "type": "artifact",
         "url": "/home/example/public_html/assets/artifact-repository/"
      }
  ],
  "require-all": true 
}
```
To answer your question @alcohol , I find that when I overwrite any of the archives and rebuild satis (using `php bin/satis build satis.json web/`) the system updates the data displayed in the web interface.

UPDATE: I discovered that I had a duplicate composer.json file in on of the other archives. Therefor the satis system was using the information from that file instead of the one a posted above. Once I removed that duplicate archive, and did a rebuild the web interface displayed this:

| Homepage   | http://www.suresteps.ca                                                                                                                                       |
|------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Authors    | System Administrator                                                                                                                                          |
| Support    | Email: support@example.ca Issues: https://bitbucket.org/example/sl-store/issues?status=new&status=open Source: https://bitbucket.org/example/sl-store/src |
| Releases   | 1.0.0                                                                                                                                                         |
| Require By |                                                                                                                                                        |
| Require    |                                                                                                                                                        |

As you can see, satis is now displaying my support links and homepage correctly. Also as I search for `sl-store` (the name of the package) on the web page I find that satis has added it to the `Required By` row of its requirements. Unfortunately as you can see, my Requirements row is not being populated which indicates an error in my implementation of that row.

Thanks for your help,
Mooror

P.S. Please note that in all the above file contents I have replaced the domain of our website with "example". Due to the nature of the project I am working on, I would like to keep the domain unamed for security reasons.

**Comment by mooror** [comment]
I will close this issue after I double check that the requirements are being pulled down when I use the `composer require` command

**Comment by mooror** [comment]
I am satisfied that it is working now. Thank you both for your help/suggestions.

Cheers,
Mooror

**Comment by alcohol** [comment]
@mooror afaik, the requires row you implemented will only show packages that are known to your Satis instance. From your composer.json example they seem to be public packages hosted by packagist. If you do not mirror them on your satis instance, satis will not know about them, therefor it cannot display them in the requires row.
