### ISSUE TITLE
Problems after satis update

### ISSUE THREAD

**Issue by sokolnikov911** [composer/satis#377]
Few days ago I had a problem. Satis starts to synchronize packages which I don't need.

**How to reproduce:**

If I install fresh satis version and build with my config it works fine.
But if I'm trying to update satis like:

```
cd satis
composer update
```

And after that I'm trying to build repository with my config, like:

`php satis/bin/satis -n -vv build config.json .`

Even if I use almost clear config, like that:

```
{
    "name":        "Sample packagist",
    "homepage":    "https://pkg.sample.org",
    "repositories":[
    ],
    "require-all": true,
    "require-dependencies": false,
    "require-dev-dependencies": false
}
```

It starts synchronize packages which I don't need:

```
petka@petka-laptop:/www/satis_test$ php satis/bin/satis -n -vv build config.json .
Scanning packages
Selected 0s1r1s/dev-shortcuts-bundle (dev-master)
Selected 11ya/excelbundle (dev-excel-forks)
Selected 11ya/excelbundle (dev-master)
Selected 11ya/excelbundle (v0.0.8)
Selected 11ya/excelbundle (v1.0.0)
Selected 11ya/excelbundle (v1.0.2)
Selected 11ya/excelbundle (v1.0.4)
Selected 11ya/excelbundle (v2.0)
Selected 1stvamp/phpweekly.info (dev-gh-pages)
Selected 2085020/zendframework1 (1.12.0)
Selected 2085020/zendframework1 (1.12.1)
......
```

It has been tested on PHP 5.6 and 7, 
on ubuntu 16.04, 16.10, 12.04,
with composer 1.2.1, 1.2.3.

**Comment by alcohol** [comment]
Since you specified no repositories and have set `require-all` to true, it will try to mirror packagist.org for you :-0

**Comment by sokolnikov911** [comment]
No, it was for example without repositories. Even if I try to build for example one repository, like:
```
{
    "name":        "Sample packagist",
    "homepage":    "https://pkg.sample.org",
    "repositories":[
        {
            "type":   "package",
            "package":{
                "name":   "amsul/pickadate.js",
                "version":"3.2.2",
                "source": {
                    "url":      "https://github.com/amsul/pickadate.js",
                    "type":     "git",
                    "reference":"3.2.2"
                },
                "dist":   {
                    "url": "https://github.com/amsul/pickadate.js/archive/3.2.2.zip",
                    "type":"zip"
                }
            }
        }
    ],
    "require-all": true,
    "require-dependencies": false,
    "require-dev-dependencies": false
}
```

It starts to synchronize some stuff which I don't need after synchronizing package which I need:

```
petka@petka-laptop:/www/satis_test$ php satis/bin/satis -n -vv build config.json .
Scanning packages
Selected amsul/pickadate.js (3.2.2)
Selected 0s1r1s/dev-shortcuts-bundle (dev-master)
Selected 11ya/excelbundle (dev-excel-forks)
Selected 11ya/excelbundle (dev-master)
Selected 11ya/excelbundle (v0.0.8)
Selected 11ya/excelbundle (v1.0.0)
Selected 11ya/excelbundle (v1.0.2)
......
```

But if I didn't update satis, it synchronizes only which I need.

**Comment by alcohol** [comment]
I am sorry, but by default packagist is included. I am not sure why it does not so for you on older versions. What you are seeing now is expected behaviour. If you do not want to mirror packagist, then you should explicitly disable the packagist repository. Can you please share which version you were running before the `composer update` ?

**Comment by stof** [comment]
@alcohol are you sure ? Satis used to disable Packagist by default (precisely to avoid mirroring it entirely)

**Comment by sokolnikov911** [comment]
`I am sorry, but by default packagist is included.` But I use satis about two years, and update it each time when deploy something. And just one week ago I had this problem.

**Comment by sokolnikov911** [comment]
> Can you please share which version you were running before the composer update ?

It was actual version of satis.

**Comment by alcohol** [comment]
@stof it has not for me for quite a while. Not sure why.. need to investigate now.

**Comment by alcohol** [comment]
So yeah, using latest composer it does seem to include packagist.org again by default.

**Comment by babwar** [comment]
Hello , i've found the trouble : 

on Composer\Satis\Console\Command\BuildCommand line 161 : 

unset(Config::$defaultRepositories['packagist']); 

now its  : unset(Config::$defaultRepositories['packagist.org']);

**Comment by alcohol** [comment]
Yeah I found that too. Unfortunately it is not really possible to make this change backwards compatible.

**Comment by stof** [comment]
@alcohol it is: https://github.com/composer/satis/pull/378

**Comment by alcohol** [comment]
@babwar should be solved now if you pull the latest version of satis.

**Comment by babwar** [comment]
Thanks a lot. It's working just fine.

**Comment by sokolnikov911** [comment]
Thank you guys, it works fine.
