### ISSUE TITLE
Trivial: last 2 lines of .gitattributes conflict

### ISSUE THREAD

**Issue by parsingphase** [composer/satis#391]
`*.json  text eol=lf whitespace=blank-at-eol,blank-at-eof,space-before-tab,tab-in-indent,tabwidth=4`
`*.json  text eol=lf whitespace=blank-at-eol,blank-at-eof,space-before-tab,tab-in-indent,tabwidth=2`

Would PR if I knew which was intended :)

**Comment by stof** [comment]
According to the current usage in the codebase, ``tabwidth=4`` should be used. Our JSON files are indented by 4 spaces.

**Comment by alcohol** [comment]
I usually use 2, but 4 is fine too.
