### ISSUE TITLE
Satis ignores "require" version constraints

### ISSUE THREAD

**Issue by thunderer** [composer/satis#397]
Hi, thanks for the excellent work on Composer, Packagist and Satis!

I have a little problem, though: even if I specify version requirements Satis still downloads all versions (including lower majors and below). My exact minimal reproducible `satis.json` is listed below, I have the latest version installed using `create-project` from current `dev-master`, and I don't have `require-all`.

I found issue #254 but I guess it is not related, as I want all versions, just constrained to the `require` values [as explained in the docs](https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md#setup).

Can you tell me why this is happening?

```
{
  "name": "PrivPkg",
  "homepage": "http://packages.tld",
  "repositories": [
    {"type": "vcs", "url": "https://github.com/symfony/symfony.git"}
  ],
  "require": {
    "symfony/symfony": "^3.2"
  }
}
```

**Comment by stof** [comment]
what do you mean by ``Satis still downloads all versions (including lower majors and below)`` ? As you register a VCS directly instead of relying on the Packagist metadata, it will indeed check all VCS tags and branches to build the repository metadata. But it should not be downloading the whole code for all versions.

**Comment by thunderer** [comment]
@stof You're right, Satis is indeed downloading *composer.json* for every version, but not the whole package. I expected it to ignore all versions that do not match `require` constraints, but I understand the behavior now.
