### ISSUE TITLE
Satis is not downloading dependencies

### ISSUE THREAD

**Issue by smarijic** [composer/satis#402]
Hi,

I'm not sure if I have configured satis properly but I found that Satis pulls only repositories I've specified but not their dependencies.
Here is configuration:

```
{
    "name": "Local Repo",
    "homepage": "http://repo.local:8000/",
    "repositories": [
        { "type": "vcs", "url": "http://hg/hg/eemanager-eentf"},
        { "type": "vcs", "url": "http://hg/hg/eemanager-eepxc"},
        { "type": "vcs", "url": "http://hg/hg/eemanager"}
        
    ],
    "require": {
        "ee/eemanager": "*",
        "ee/eemanager-eentf": "*",
        "ee/eemanager-eepxc": "*"
    },
    "archive": {
        "directory": "dist",
        "skip-dev": true
    },
    "require-all": false,
    "require-dependencies": true,
    "require-dev-dependencies": true
}
```

For example hg/hg/eemanager is a composer project which is hosted on our private repository which depends on laravel/laravel package, but I can't find that package in dist folder.

Any ideas on this one?

**Comment by stof** [comment]
In Satis, Packagist is not registered automatically (as it would be quite bad for ``require-all: true``). So you need to add it in the list of repositories too if you want to include dependencies coming from Packagist.

**Comment by alcohol** [comment]
If I am not mistaken, by default, we disable packagist. So if you want to include dependencies that are hosted on packagist, you have to add packagist as a repository.

**Comment by alcohol** [comment]
@stof beat me to it :+1:

**Comment by smarijic** [comment]
So If I add packagist as a repository will satis pull only dependencies that are needed, or will he create complete mirror of packagist?

**Comment by stof** [comment]
Only the needed ones, as you configured ``"require-all": false``.

Don't turn this setting on when adding Packagist. Satis is just not able to handle the millions of packages available on Packagist (unless you have a build server with TB of RAM, days to run each Satis build, and lots of disk space to store archives, and you turn on ``providers`` to avoid needing the same on systems using your Satis repo for ``composer update``)

**Comment by smarijic** [comment]
Ok, thanks.

So I added now

`{
            "type": "composer",
            "url": "https://packagist.org"
        },`

And when I run satis build, I'm getting some weird messages like:

`The pear-pear.php.net/net_growl 2.7.x requirement did not match any package
The pear-pear.php.net/pear_packagefilemanager 1.7.x requirement did not match any package
The pear-pear.php.net/pear_packagefilemanager2 1.0.x requirement did not match any package
The pear-pear.php.net/xml_serializer 0.20.x requirement did not match any package
The pear-pear.php.net/console_getopt ~1.3.0 requirement did not match any package
The zendframework/zend-locale 2.* requirement did not match any package
The zendframework/zend-translator 2.* requirement did not match any package
The pear-symfony/eventdispatcher 1.* requirement did not match any package
`

I'm pretty sure that none of packages are using any of these packages above, and the list is going on and on, this was just small sample.

**Comment by smarijic** [comment]
Ok, it started pulling dependencies.
Thanks, guys.
