### ISSUE TITLE
Make composer to look in my local repository first.

### ISSUE THREAD

**Issue by timurgafarov** [composer/satis#407]
I am using Satis to create local composer repository for Magento2 modules. Magento2 comes with pre-configured conposer.json file that has repo.magento.com in it out of the box. 

When I am adding my local repo by running this command

`composer config repositories.repo-name composer myrepo-website.com`

it adds it perfectly.

However when trying to require package it first looks in magento repo. Is there any way I can specify on the command line when running this command:

`composer require packagename/module-name:dev-master`

to look in my local repo first. The reason why this is a problem is because magento repo asks for authentication and you can not skip it unless you provide credentials. Alternitively is there a command that can set preference for which repo to look in first?

**Comment by alcohol** [comment]
Order of repository definitions matters. But composer will still search through all repositories regardless, because it could be that a repository that is defined later has a more recent version.

**Comment by curry684** [comment]
> more recent

Or in this case more likely "better fitting your prefer-stable configuration".

**Comment by timurgafarov** [comment]
Another thing that I noticed. When I try to install package of type "vcs" rather than type "composer", it will pull down package without prompting credentials from magento repository. It looks like composer prefers "vcs" type over "composer" type though "vcs" was last one on the list. Can you guys give a more explicit explanation of how composer decides on which repo's to check first. My understanding was that it just loops though each one, in the order in which they appear in composer.json file.

I think you should seriously consider adding functionality that will allow user to specify repository that he wants to pull from. The default behavior can still be to loop through all repositories unless a more specific one is provided.

In our case we can not tell our clients to remove Magento2 repository from composer.json file as it should be there. The end goal is to host and serve all of our commercial modules ONLY from our local repository.

Can you give a workaround? Is it possible to disable repository or change order of repos in composer.json with command line?

**Comment by curry684** [comment]
In the case of VCS it has to download the package every time because it needs to know what's in the `composer.json` to judge whether it's a valid candidate.

It then checks all repositories, because it has to, to be able to take configured preferences like `prefer-stable` and `minimum-stability` into account. It then in the end selects the most valid candidate, and if 2 candidates are equally good *then* it should prefer one in an earlier defined repository.

You can 'fix' the order by manually editing the composer.json file.

**Comment by timurgafarov** [comment]
curry684, thank you for your response,

Do you know if there is a preference given to type "vcs" when pulling packages? I don't see authentication prompts when I have a direct github repository path.

**Comment by curry684** [comment]
It's like Schrödinger's cat - we have to look into the repository to know whether it has changed, thereby giving the impression that we actually want to use it. We're really just peeking at the composer.json at that point.

Repository candidates are, in the end, only evaluated by their order of definition. Packagist is internally added as the last one by definition (though you can disable that) to ensure local copies are always preferred, *if allowed by resolver settings*.

**Comment by AnrDaemon** [comment]
This issue is not with satis at all. Can be safely closed.
