### ISSUE TITLE
Add new release

### ISSUE THREAD

**Issue by rpwashburn** [composer/satis#410]
Trying to use [satis-control-panel](https://github.com/realshadow/satis-control-panel), which is currently composering in "version": "1.0.0-alpha2" of Satis. 

As far as I can tell, this version is showing symptoms of [#377](https://github.com/composer/satis/issues/377) and was resolved with [#378](https://github.com/composer/satis/pull/378). It is trying to mirror all of packagist when I only want private repositories. 

Updating satis-control-panel to dev-master of Satis seems to fix this issue, but I would prefer if I could assign Satis to a fixed release version, that is not 1.0.0-alpha2 or dev-master.

**Comment by alcohol** [comment]
I just released `1.0.0-alpha3`.
