### ISSUE TITLE
Twig Exception mb_substr_count(): Unknown encoding "0" 

### ISSUE THREAD

**Issue by Iruwen** [composer/satis#413]
Did a git pull & composer update yesterday, now this happens at the end of an update:

> Writing web view
> 
> [Twig_Error_Syntax]
> An exception has been thrown during the compilation of a template ("mb_substr_count(): Unknown encoding "0"") in "index.html.twig".
> 
> [ErrorException]
> mb_substr_count(): Unknown encoding "0"

**Comment by alcohol** [comment]
Unable to reproduce.

**Comment by Iruwen** [comment]
I see, I ran update because I've been getting the message "_Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them._" for a while, also the main page says "_Updating Satis is as simple as running git pull && composer update in the Satis directory._"
I checked out the original composer.lock and ran composer install again, the error is gone now. Should I break it again so we can look into what's going on or just ignore the composer.json / composer.lock discrepancy until the latter is updated?

**Comment by alcohol** [comment]
Like I said, I just ran `composer update` on the latest master branch and was unable to reproduce your issue. So please, if you can find a way to reproduce your issue give us detailed steps so I can further look into this.

**Comment by Iruwen** [comment]
I'm able to break it again by simply doing this, is that of any help? Otherwise I'll just ignore the composer warning:

vcs:/var/www/satis$ git fetch origin
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/composer/satis
   a37a218..b935743  master     -> origin/master

vcs:/var/www/satis$ git reset --hard origin/master
HEAD is now at b935743 fix some mistakes/defaults in config example

vcs:/var/www/satis$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 26 updates, 0 removals
  - Updating symfony/polyfill-mbstring (v1.2.0 => v1.3.0): Loading from cache
  - Updating twig/twig (v1.26.1 => v2.3.2): Loading from cache
  - Updating symfony/debug (v3.1.5 => v3.2.8): Loading from cache
  - Updating symfony/console (v3.1.5 => v3.2.8): Loading from cache
  - Updating symfony/yaml (v3.1.5 => v3.2.8): Loading from cache
  - Updating sebastian/version (2.0.0 => 2.0.1): Loading from cache
  - Updating sebastian/recursion-context (1.0.2 => 2.0.0): Loading from cache
  - Updating sebastian/object-enumerator (1.0.0 => 2.0.1): Loading from cache
  - Updating sebastian/exporter (1.2.2 => 2.0.0): Loading from cache
  - Updating sebastian/environment (1.3.8 => 2.0.0): Loading from cache
  - Updating sebastian/comparator (1.2.0 => 1.2.4): Loading from cache
  - Updating phpunit/phpunit-mock-objects (3.4.0 => 3.4.3): Loading from cache
  - Updating phpunit/php-timer (1.0.8 => 1.0.9): Loading from cache
  - Updating phpunit/php-file-iterator (1.4.1 => 1.4.2): Loading from cache
  - Updating sebastian/code-unit-reverse-lookup (1.0.0 => 1.0.1): Loading from cache
  - Updating phpunit/php-token-stream (1.4.8 => 1.4.11): Loading from cache
  - Updating phpunit/php-code-coverage (4.0.1 => 4.0.8): Loading from cache
  - Updating webmozart/assert (1.1.0 => 1.2.0): Loading from cache
  - Updating phpdocumentor/type-resolver (0.2 => 0.2.1): Loading from cache
  - Updating phpspec/prophecy (v1.6.1 => v1.7.0): Loading from cache
  - Updating myclabs/deep-copy (1.5.4 => 1.6.1): Loading from cache
  - Updating phpunit/phpunit (5.6.1 => 5.7.19): Loading from cache
  - Updating composer/ca-bundle (1.0.4 => 1.0.7): Loading from cache
  - Updating symfony/filesystem (v3.1.5 => v3.2.8): Loading from cache
  - Updating symfony/finder (v3.1.5 => v3.2.8): Loading from cache
  - Updating symfony/process (v3.1.5 => v3.2.8): Loading from cache
Writing lock file
Generating autoload files

vcs:/var/www/satis$ php -d memory_limit=2G -d sys_temp_dir=/var/tmp /var/www/satis/bin/satis -vvv --no-ansi --no-interaction --skip-errors build /var/www/satis/repo/satis.json /var/www/satis/repo/
Reading /var/www/satis/vendor/composer/installed.json
Scanning packages
...
wrote packages to /var/www/satis/repo//include/all$fb9d8bcd70dce4de266616bc528107892bca89b0.json
Writing packages.json
Pruning include directories
Deleted /var/www/satis/repo//include/all$3caab4fcce46e464bd23cfa3406c5296b56bbdb3.json
Writing web view


  [Twig_Error_Syntax]
  An exception has been thrown during the compilation of a template ("mb_substr_count(): Unknown encoding "0"") in "index.html.twig".


Exception trace:
 () at /var/www/satis/vendor/twig/twig/lib/Twig/Environment.php:549
 Twig_Environment->compileSource() at /var/www/satis/vendor/twig/twig/lib/Twig/Environment.php:363
 Twig_Environment->loadTemplate() at /var/www/satis/vendor/twig/twig/lib/Twig/Environment.php:288
 Twig_Environment->render() at /var/www/satis/src/Builder/WebBuilder.php:61
 Composer\Satis\Builder\WebBuilder->dump() at /var/www/satis/src/Console/Command/BuildCommand.php:210
 Composer\Satis\Console\Command\BuildCommand->execute() at /var/www/satis/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /var/www/satis/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at /var/www/satis/vendor/symfony/console/Application.php:200
 Symfony\Component\Console\Application->doRun() at /var/www/satis/src/Console/Application.php:54
 Composer\Satis\Console\Application->doRun() at /var/www/satis/vendor/symfony/console/Application.php:124
 Symfony\Component\Console\Application->run() at /var/www/satis/bin/satis:26

  [ErrorException]
  mb_substr_count(): Unknown encoding "0"

Exception trace:
 () at /var/www/satis/vendor/twig/twig/lib/Twig/Compiler.php:182
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 mb_substr_count() at /var/www/satis/vendor/twig/twig/lib/Twig/Compiler.php:182
 Twig_Compiler->addDebugInfo() at /var/www/satis/vendor/twig/twig/lib/Twig/Node/Text.php:28
 Twig_Node_Text->compile() at /var/www/satis/vendor/twig/twig/lib/Twig/Node.php:82
 Twig_Node->compile() at /var/www/satis/vendor/twig/twig/lib/Twig/Node.php:82
 Twig_Node->compile() at /var/www/satis/vendor/twig/twig/lib/Twig/Compiler.php:82
 Twig_Compiler->subcompile() at /var/www/satis/vendor/twig/twig/lib/Twig/Node/Module.php:300
 Twig_Node_Module->compileDisplay() at /var/www/satis/vendor/twig/twig/lib/Twig/Node/Module.php:90
 Twig_Node_Module->compileTemplate() at /var/www/satis/vendor/twig/twig/lib/Twig/Node/Module.php:62
 Twig_Node_Module->compile() at /var/www/satis/vendor/twig/twig/lib/Twig/Compiler.php:71
 Twig_Compiler->compile() at /var/www/satis/vendor/twig/twig/lib/Twig/Environment.php:531
 Twig_Environment->compile() at /var/www/satis/vendor/twig/twig/lib/Twig/Environment.php:544
 Twig_Environment->compileSource() at /var/www/satis/vendor/twig/twig/lib/Twig/Environment.php:363
 Twig_Environment->loadTemplate() at /var/www/satis/vendor/twig/twig/lib/Twig/Environment.php:288
 Twig_Environment->render() at /var/www/satis/src/Builder/WebBuilder.php:61
 Composer\Satis\Builder\WebBuilder->dump() at /var/www/satis/src/Console/Command/BuildCommand.php:210
 Composer\Satis\Console\Command\BuildCommand->execute() at /var/www/satis/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /var/www/satis/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at /var/www/satis/vendor/symfony/console/Application.php:200
 Symfony\Component\Console\Application->doRun() at /var/www/satis/src/Console/Application.php:54
 Composer\Satis\Console\Application->doRun() at /var/www/satis/vendor/symfony/console/Application.php:124
 Symfony\Component\Console\Application->run() at /var/www/satis/bin/satis:26

build [--repository-url [REPOSITORY-URL]] [--no-html-output] [--skip-errors] [--stats] [--] [<file>] [<output-dir>] [<packages>]...

**Comment by stof** [comment]
May it be that you have `mbstring.func_overload` enabled on your system ? And that the override of `substr_count` in this case is broken because the mbstring function does not have the same signature ?
The code at the line of the error is *not* using `mb_substr_count` but `substr_count`.

You should disable `mbstring.func_overload`, as it causes issues (btw, Twig 2 dropped any attempt to support it, as PHP deprecated this feature in 7.2 anyway)

**Comment by alcohol** [comment]
Admittedly, I ran satis inside the docker container we build for it. So yea, look for differences in php.ini settings in your environment compared to the default settings used in the docker container. Also, are you using a custom template or not? Most likely @stof's answer hits the nail on the head.

**Comment by Iruwen** [comment]
Arr that's it, thank you. Somebody set this to 2, gonna have to figure out why. Sorry for the hassle.

**Comment by salsa-dev** [comment]
thanks for a hint on this. just bumped into with the following exceptions (from completely different project):

`Uncaught PHP Exception Twig_Error_Syntax: "A block must start with a tag name."`
`Uncaught PHP Exception Twig_Error_Syntax: "Unexpected token "end of template" of value "" ("end of statement block" expected)."`

disabling `mbstring.func_overload` fixes this (for "Googlers")

**Comment by petegore** [comment]
My `mbstring.func_overload` was at `6` ; it just put it at `0` and it works fine now.
