### ISSUE TITLE
GitLab + Docker Issue

### ISSUE THREAD

**Issue by DRogue1337** [composer/satis#415]
I'm new to docker so maybe this is just a docker issue I'm having.

I'm currently running gitlab with the official docker container with docker-compose and nginx reverse proxy.
I'm also running satis with the docker container.

**/etc/nginx/sites-available/gitlab**
```
upstream gitlab {
        server localhost:8080;
}

server {

        listen 80;

        server_name test.gitlab.code.ag;

        location / {
                proxy_pass http://gitlab/;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

}
```

Now when executing
```
sudo docker run --rm -it -v ~/docker/satis/build:/build composer/satis
```

I'm getting the error
```
[Composer\Downloader\TransportException]                                                                                                                             
  The "http://root@test.gitlab.code.ag/api/v3/projects/root%2Ftest" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name does not resolve  
  failed to open stream: php_network_getaddresses: getaddrinfo failed: Name does not resolve
```

![screenshot_20170505_152405](https://cloud.githubusercontent.com/assets/16617893/25747201/eabe73b8-31a6-11e7-9dc5-6b4f997591a7.png)

**Comment by andrewhowdencom** [comment]
That error means that the upstream server is not resolving. Check the `cat /etc/resolv.conf` in the container, to see if it prints something sane -- if you're on ubuntu, and you're mounting the host /etc/resolv.conf it'll attempt to connect to Ubuntus local copy of dnsmasq -- not available in the container (for example)

If that seems sane, exec into the host and run

```
getent hosts test.gitlabel.code.ag
```

See if that works

**Comment by DRogue1337** [comment]
I'm on a ubuntu vm. I'm not explicitly mounting the /etc/resolv.conf, but I think it does. I added a comment to the conf on my host and when running

```
docker run --rm -it -v ~/docker/satis/build/:/build -v ~/docker/satis/composer/:/composer composer/satis cat /etc/resolv.conf
```

it shows the edited config.

```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 10.0.2.3
#test
```

I tried adding `nameserver 127.0.0.1` to it. But now when running the container and checking the conf file, the added nameserver line isn't there but my previously added comment is. So I'm not sure what's happening right now.

Running `getent hosts test.gitlab.code.ag` returns the same one the host and the container:
```
127.0.0.1       test.gitlab.code.ag
```

**Comment by alcohol** [comment]
I do not think this is a Satis specific issue. But I will leave it open for. Perchance someone else will be able to help you figure out what is wrong exactly and how to resolve/fix :-)

**Comment by andrewhowdencom** [comment]
@DRogue1337  Docker adds its own DNS stuff I think., in addition tot he host resolv.conf. 
https://docs.docker.com/engine/userguide/networking/default_network/configure-dns/

Re. Your specific issue; `getent hosts test.gitlab.code.ag` should either return nothing (in which case things are broken) or a valid address -- something has indicated to the system resolver (`getent`)  that the address is localhost. This is a bit weird -- it's either gotta be:

- Resolving via `/etc/hosts`. 
- Resolving via DNS somehow at the 10.0.2.3

If you can apt-get install stuff, you could query 10.0.2.3 directly with 

```
dig @10.0.2.3 test.gitlab.code.ag
```

That would at least tell you where that's coming from

It's also a bit weird that it's the same in the host and the container.

I'd maybe try using something like 

DOCKER_OPTS="--dns=8.8.8.8" to drop out weird DNS servers in the mix? 

What's in `run.sh`?

**Comment by alcohol** [comment]
You mentioned you are using docker compose also, and that nginx runs in another container. Can you share your compose config? Are you linking the containers correctly?

**Comment by DRogue1337** [comment]
I have nginx installed **without** a container in my `bento/ubuntu-16.04` vm. I installed gitlab with this docker-compose config

**docker-compose.yml**
```
web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'test.gitlab.code.ag'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://test.gitlab.code.ag'
      registry_external_url 'http://test.gitlab.code.ag:4567'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '8080:80'
    - '44300:443'
    - '22000:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/gitlab/data:/var/opt/gitlab'
```

and I'm running the satis container with run.sh

**run.sh**
```
docker run --rm -it -v ~/docker/satis/build:/build -v ~/docker/satis/composer:/composer composer/satis
```

I tried running the above with `-e DOCKER_OPTS="--dns=8.8.8.8"` but it's the same error.

GitLab is reachable from my host via `test.gitlab.code.ag` and also from inside my vm via `localhost:8080 `and via `test.gitlab.code.ag` when adding it to the vm's `/etc/hosts`.

I tried linking the containers by adding `--link vagrant_web_1` to the command in run.sh, because that's the GitLab container's name:

```
CONTAINER ID        IMAGE                     COMMAND             CREATED             STATUS                    PORTS                                                                 NAMES
8dcb639b8faa        gitlab/gitlab-ce:latest   "/assets/wrapper"   29 minutes ago      Up 29 minutes (healthy)   0.0.0.0:22000->22/tcp, 0.0.0.0:8080->80/tcp, 0.0.0.0:44300->443/tcp   vagrant_web_1
```

When using `dig @10.0.2.3 test.gitlab.code.ag` I get this output:

![screenshot_20170508_173514](https://cloud.githubusercontent.com/assets/16617893/25811841/cc231cae-3414-11e7-8a72-7541b7d313d7.png)

**Comment by andrewhowdencom** [comment]
> When using dig @10.0.2.3 test.gitlab.code.ag I get this output:

You're def resolving it with /etc/hosts (or I don't understand how DNS resolution works). I don't understand why it's resolving in the container though -- presumably, that also has test.gitlab.code.ag in the containers /etc/hosts. 

Wait! I found it. So, you're setting the hostname in the gitlab container to `test.gitlab.code.ag`. Presumably, that creates the normal alias in /etc/hosts -- you can check this by changing your hostname, and checking whether the `getent hosts` command changes behaviour. Presumably, you ran the getent hosts command in the gitlab container, rather than the satis container -- try running it again in the satis container:

```
getent hosts test.getlab.code.ag
```

Fucking around now with another set of applications but setting the hostname, that seems to be what's happening:

```
$ docker exec -it dockercompose_db_1  /bin/bash
root@blorp:/# cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.18.0.2	blorp
root@blorp:/# getent hosts beepboop
root@blorp:/# getent hosts blorp   
172.18.0.2      blorp
root@blorp:/# 
```

The names resolve as you'd normally expect with host discovery, though

```
root@blorp:/# getent hosts db # This is the service node title; in your case, "web" for gitlab
172.18.0.2      db
root@blorp:/# getent hosts magento
172.18.0.3      magento
root@blorp:/# 
```

So, if you're using the normal package.json stuff it's probably

http://root@web/api/path/to/packages.json (or whatever, swap `test.gitlab.code.ag` for `web`)

Let me know how you goo!

**Comment by DRogue1337** [comment]
Ok. I'm a bit confused right now, but I got this part working and thank you so so much for your help @andrewhowdencom.

> Running getent hosts test.gitlab.code.ag returns the same one the host and the container:

I actually ran the command on my VM and the satis container, not the gitlab container.

But with just understanding half of what you said at the moment, I ran
```
docker exec vagrant_web_1 cat /etc/hosts
```
on my gitlab container and in there was this line
```
172.17.0.2      test.gitlab.code.ag test
```

So I tried setting the repository url in my `satis.json` file to `{ "type": "gitlab", "url": "http://root@test/root/test.git" }`. Swapping `test.gitlab.code.ag` with `test`.
And now satis is able to discover the gitlab instance.

I'm just getting a 404 now because it couldn't find the project via the api, dunno why yet. API Token and all is set up. Will dig around a bit and maybe open a new issue if I can't get it to work.

For now I'm just wondering how to change the hostname of my gitlab container so that it is `test.gitlab.code.ag` to the satis container and not just `test`(wherever that's coming from).
It's just strange that just the satis container can find the gitlab instance via `test` and my vm host can not.
![screenshot_20170509_111813](https://cloud.githubusercontent.com/assets/16617893/25843958/53e57300-34a9-11e7-91d8-54e4c7480eba.png)

**Comment by alcohol** [comment]
If you run named containers you can just link them and then docker will automatically add /etc/hosts entries based on the names you used (note: only in the container with the `--link` flag, not the container you link it to).

E.g.:

```
rob@localhost ~ > docker run --rm -it --name foo alpine sh

/ #
```
> switch to another terminal
```
rob@localhost ~ > docker run --rm -it --name bar --link foo alpine sh

/ # cat /etc/hosts

127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2      foo 53b27c345fac
172.17.0.3      3766dceb5e55

/ # ping foo

PING foo (172.17.0.2): 56 data bytes
64 bytes from 172.17.0.2: seq=0 ttl=64 time=0.175 ms
64 bytes from 172.17.0.2: seq=1 ttl=64 time=0.093 ms

--- foo ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.093/0.134/0.175 ms
```

**Comment by DRogue1337** [comment]
Ok, when setting the container_name to `test.gitlab.code.ag` I got a `connection refused` error. But I destroyed and upped the vm again and added more poxy headers. Whatever got it working.

Now I'm back to the 404, but I think that's a separate issue, because I'm also getting this when trying to connect to my account at gitlab.com.

Thank you, @andrewhowdencom and @alcohol!
