### ISSUE TITLE
Gitlab download master version and do not hash in the paramenter API v3

### ISSUE THREAD

**Issue by prhost** [composer/satis#417]
Example URL bug:

https://gitlab.com/api/v3/projects/agencia110%2Fmetastore-extension-cnova/repository/archive.zip?ref=3bcf2513c14858b7dd9d7d7c136409d6c7c9077b

This low url lowers the master version and not the commit hash passed in ref.

The url should look like this:
https://gitlab.com/agencia110/metastore-extension-cnova/repository/archive.zip?ref=3bcf2513c14858b7dd9d7d7c136409d6c7c9077b

**Comment by prhost** [comment]
https://github.com/composer/composer/issues/6369

please, update composer package.

**Comment by alcohol** [comment]
Should be fixed by 2ba7251a8e28e204933dd3d61b66dbaad09c303b.
