### ISSUE TITLE
Allow to re-build in browser

### ISSUE THREAD

**Issue by robsch** [composer/satis#421]
Would it make sense to have an re-build button on the generated overview homepage? Currently, one can only re-build on the command-line. Provided that a satis configuration already exists and the build was at least done once (so the configuration works) a re-build should work without any problems. 

Could be for the whole satis-repo or for each vcs-repos (package) individually. To make the generation safe it could be done into another temporary directory, which gets renamed as the last step.

This would be just an alternative to a cron-job or using a repository hook or whatever.

**Comment by andrewhowdencom** [comment]
I had plans at one point to implement this; can just make a HTTP request somehow in that case when CI finishes on a package / git hook.

**Comment by stof** [comment]
Satis itself generates a static website. So building this in Satis itself would be hard. I suggest building this as a wrapper on top of Satis itself.

**Comment by robsch** [comment]
True. Although it's a small button, it would mean a bigger conceptual change, I guess. At least satis/composer is about web development, so IMO it could be considered.

**Comment by andrewhowdencom** [comment]
@robsch  A quick and dirty solution is to have a process invoker like https://github.com/adnanh/webhook/blob/master/README.md

**Comment by robsch** [comment]
The web folder is in a web accessible folder and it is very likely that the web server has php enabled. So shouldn't it be easy to add a php file there that executes the build anyhow? (Sorry if that sounds stupid and naive).

**Comment by MatthiasKuehneEllerhold** [comment]
The user of the PHP process must be the same as the one running the cronjob. Because you'd need access to the same credentials (e. g. github auth credentials, SSH keys, ...) and it needs write access to the public directory and to the "include" and "dist" directories. 

So you'd pretty much need a PHP-FPM installation with a separate pool for satis (to switch the user). Or (if you want to use apache2 + mod_php) you could give www-data sudo-rights to execute the cronjob as another user.

**Comment by robsch** [comment]
Well, seems to more complicated than I thought. Hm... it would be a nice feature at least.

Feel free to close the issue if it is not (easily) realizable.

**Comment by ramunasd** [comment]
Actually there is already satis based applications which does what You want, @robsch .

One example https://github.com/ludofleury/satisfy with webhooks as upcoming feature.

**Comment by alcohol** [comment]
That's a good example. Closing this issue btw as it will not be solved in Satis itself :-)
