### ISSUE TITLE
Partial Updates with Docker

### ISSUE THREAD

**Issue by Morgy93** [composer/satis#426]
Hello,

is it possible to do partial updates with the docker build?
https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md#partial-updates

Maybe something like:

`docker run --rm -it -v /build:/build -e PACKAGE='foo/bar' composer/satis`

**Comment by alcohol** [comment]
Why not just do it as described in the documentation?

```
docker run --rm -it -v /build:/build composer/satis \
  bin/satis build /build/satis.json /build/web this/package that/other-package
```

**Comment by Morgy93** [comment]
Well, I didn't know that you could run this command by just adding it there.
That should do it then, thank you!

**Comment by alcohol** [comment]
The default command being run can be found here: https://github.com/composer/satis/blob/master/Dockerfile#L47

But you can pass whatever you want yourself :-)
