### ISSUE TITLE
Mirror without using dist

### ISSUE THREAD

**Issue by Morgy93** [composer/satis#428]
Hello,

is it possible to mirror all the packages while still sticking to the source?
I'd like to mirror the packages now, but don't want them to be public and easy downloadable, so it just serves some "backup" purpose.
I know there's a security and authentication feature, but I like the way it's running right now. (Just want to mirror for backup purpose)

**Comment by PatrickRose** [comment]
Just run satis on a non-public machine?

**Comment by PatrickRose** [comment]
To expand - you don't have to use satis in your application code so you continue to use things as they were but you've got a backup.

I'd suggest *not* doing that though and just protect your server.

**Comment by Morgy93** [comment]
Yeah I talked to my colleagues about it and we're now going for dist instead of source for performance reasons.
That means I have to protect the server anyway .. 

Thanks for your reply!
