### ISSUE TITLE
How to silence Satis?

### ISSUE THREAD

**Issue by EgbertW** [composer/satis#430]
I'm running Satis in a cronjob every 15 minutes, using a command>

`bin/satis repositories.json /var/www/composer/`

However, this sends me an e-mail every 15 minutes which I don't want - I prefer only to get e-mails if something does not go ok.

So I tried redirecting it to /dev/null, by appending > /dev/null to the command.

When run from the command line this indeed does not give any output. However, the cronjob keeps sending me mails, containing:

> Reading composer.json of REPO1 (master)                   Reading composer.json of REPO2 (master)                     Reading composer.json of REPO3 (master)

Which is weird because this is not even output at all when running from the command line, while the regular output from the command line (Scanning packages, creating local downloads) is supressed.

The message itself seems to originate in vendor/composer/composer/src/Composer/Repository/VcsRepository.php

Any clue on why this message doesn't want to be suppressed, and why it doesn't show up in commad line execution?

Is there any option to pass to satis to stop it from generating output, unless errors occur?

I also tried 2>&1 > /dev/null to redirect STDERR to /dev/null as well, but that doesn't help, and I don't actually want to redirect STDERR.

**Comment by alcohol** [comment]
A lot of info is output on stderr, because this is the CLI destination for both errors but also informational/debugging output. stdout is reserved for output that is classified as data and such, which can be fed/piped into other applications.

I would suggest installing `chronic` (commonly available in the system package called `moreutils`) which serves exactly this use-case.

http://manpages.ubuntu.com/manpages/xenial/man1/chronic.1.html

**Comment by EgbertW** [comment]
Thanks! Chronic indeed seems to work. Adding it to my internal library of useful utilities :+1: 

I still don't get why 2>&1 > /dev/null doesn't work, though, and why the regular output differs from the output in the cronjob.

Anyway, this saves me a lot of e-mails, thanks!

**Comment by alcohol** [comment]
You're welcome. About the redirection, I'm not sure cause I did not take a lot of time to look into it, but it can be tricky from time to time to get it right.

**Comment by PatrickRose** [comment]
You probably want to swap your redirect around and do 

`satis-command 1>/dev/null 2>&1`

Redirecting stderr after stdout doesn't work.

Doesn't satis have a --quiet option you can use?

**Comment by MatthiasKuehneEllerhold** [comment]
Redirecting will only take current values into effect!
`satis-command 2>&1 1>/dev/null`
* will first redirect stderr to the current stdout (which is your terminal)
* and then will redirect stdout to /dev/null
Which means your stderr will still be redirected to your terminal!

`satis-command 1>/dev/null 2>&1` 
* will first redirect stdout to /dev/null
* and then will redirect stderr to the current stdout (which is /dev/null)
This will silence everything.

You really should use cronic though! See http://habilis.net/cronic/

**Comment by EgbertW** [comment]
Weird, I use that same sequence for various cronjobs and never had issues. Anyway, I'm using Chronic now which does the job nicely!
