### ISSUE TITLE
Getting a Twig runtime error when generating the web view

### ISSUE THREAD

**Issue by stickybeatz** [composer/satis#433]
I'm getting the following error when trying to update my satis packages:

`[Twig_Error_Runtime]
An exception has been thrown during the rendering of a template ("count(): Parameter must be an array or an object that implements Countable").`

I tried clearing the composer cache, but that didn't help. Not sure where else to look...

**Comment by stickybeatz** [comment]
ran composer update and now it works again...

**Comment by alcohol** [comment]
Make sure you install dependencies as they are listed in the `composer.lock` file. Running `composer update` means you potentially deviate from a known working set of dependencies, and we cannot support you in such a scenario.
