### ISSUE TITLE
Memory blow up

### ISSUE THREAD

**Issue by cxj** [composer/satis#437]
Satis consumes all possible memory while generating the HTML web page output for my repositories.  

```sh
147 ~/phppkg> satis build satis.json . > build.log
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 430080 bytes) in ~/satis/vendor/twig/twig/lib/Twig/Template.php on line 426
```

The contents of the web page get spewed to `stdout` instead of `index.html`, as well.  

```html
...
Dumping 'psr/http-message'.
Writing packages.json
Pruning include directories
Writing web view
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex,nofollow" />
...
```

Using a fresh install of Satis as of 22 October 2017:
```sh
148 ~/phppkg> satis --version
Satis 1.0.0-dev
154 ~/satis> git graph | head
* f66ff72 (HEAD -> master, origin/master, origin/HEAD, composer/master) Fix selecting alias instead of package (#432)
* 1ce9262 drop hhvm, make trusty explicit
...
```

This is used daily and was working a couple weeks ago.  My guess is it has something to do with handling the ever increasing numbers of commits and tagged revisions in my repositories.

**Comment by cxj** [comment]
I've poked at this a bit.  I turned off HTML generation.  That worked for a while.  But it began failing again after a couple of commits.  It blows up on the json_encode() in the following code is:
```php
  public static function encode($data, $options = 448)
    {
        if (PHP_VERSION_ID >= 50400) {
            $json = json_encode($data, $options);
            if (false === $json) {
                self::throwEncodeError(json_last_error());
            }
```

**Comment by cxj** [comment]
```sh
$ php -v
PHP 7.1.4 (cli) (built: May  9 2017 18:22:28) ( NTS )
```

**Comment by alcohol** [comment]
Your limit is give or take 128mb. I am sorry, but that is an incredibly low limit considering Composer (the core component of Satis) itself requires roughly 1gb to be available at least.

**Comment by cxj** [comment]
Thanks for the information, Rob.  I had no idea that Composer needed so much memory.  Would you accept PRs to the documentation to include some suggestions about memory usage?
