### ISSUE TITLE
Tag last working version for PHP 5.6

### ISSUE THREAD

**Issue by kelsey9649** [composer/satis#440]
I pulled for my satis instance (which is on a PHP 5.6 server) and it stopped working. Last commit working for 5.6 is f66ff72ce4e788e95827404888fd53b3c9d29f82. I've checked out against this commit. It might be good for users if you tag this commit as the last working version for PHP 5.6, but it is simply a suggestion. Thanks!

**Comment by alcohol** [comment]
I am confused. If you pull the latest version and run composer install, it should notify you that your PHP version does not match the requirements?

**Comment by kelsey9649** [comment]
It does. It would just be handy to have the last commit that works with 5.6 tagged for easy reference. While the adoption of ^7.0 is really great there are some that move a little slower than the crowd.

**Comment by alcohol** [comment]
Is the docker container variant not a solution for you? That way you do not have to support any php version on your host system.

**Comment by Benoit-amo** [comment]
My 2 cents. 

On our instance with PHP 5.6, after a `git pull && composer install --no-dev`, this is the commit 5ec3b134e99df33fa3259850e235dc4f63112fc6 which broke the static file generation.
Removing off the ` || ^2.0` of the Twig package declaration made Satis work again.

**Comment by richardselby** [comment]
Because PHP is set to 7.0 in composer.json, checking out the latest version of satis and running `composer install` will install all packages, even on a machine running 5.6. There's no warning that your PHP version does not satisfy the requirement.

**Comment by alcohol** [comment]
You should read up on https://getcomposer.org/doc/06-config.md#platform

**Comment by richardselby** [comment]
I know about the setting, that's why I realised I was having issues. It seems odd to me to have this as a default, though - as I mentioned, this allows installations on incompatible systems.

**Comment by alcohol** [comment]
I guess that is a matter of interpretation. I think the requirements speak for themselves.

**Comment by alcohol** [comment]
I tagged 1.0.0 as the first (and last) stable for 5.6.

I also made the 1.x branch based of that last commit, so that at the very least, we can still easily fix critical bugs/security issues.

Master is now aliased as 2.0-dev.
