### ISSUE TITLE
Make a stable non-alpha release

### ISSUE THREAD

**Issue by wiardvanrij** [composer/satis#441]
I think there should be at least 1 stable non-alpha release available. So many people use this and it is weird to see it running in alpha versions or 1.0.0-**dev**

**Comment by dasginganinja** [comment]
+1

**Comment by alcohol** [comment]
I forgot to close this. But a `1.0.0` tag has existed since August 10.

**Comment by wiardvanrij** [comment]
1.0.0
@alcohol alcohol released this an hour ago ..  not August 10, 2017.. 

but yea thanks.

**Comment by alcohol** [comment]
That's just the "github release". The tag (which is used by packagist.org) is much older. But I figured people might be confused by the github UI, and thus not notice that release is not the same as tags, so I decided to add a release for the tag.

- https://github.com/composer/satis/releases
- https://github.com/composer/satis/tags
