### ISSUE TITLE
Satis doesn't support stability per package

### ISSUE THREAD

**Issue by avplab** [composer/satis#442]
I am not sure this is an issue, but I couldn't find any official documentation where it's described. I would like to have `minimum-stability: stable` option configured for all packages, but also be able to provide an exception for specific package(I have to download a `-rc1` package). But `@RC` doesn't work in case of satis. After the source code [investigation](https://github.com/composer/satis/blob/master/src/PackageSelection/PackageSelection.php#L161)
 I found out that stability flags are not supported intentionally(so I suppose it's not an issue). Which alternative could be provided here?

**Comment by stof** [comment]
@alcohol please close this issue, as it has been implemented

**Comment by avplab** [comment]
Thank you

**Comment by alcohol** [comment]
Sorry, I'm used to using the #closes annotation in commit messages myself :sweat_smile:
