### ISSUE TITLE
Accessing 192.168.123.102 over http which is an insecure protocol.

### ISSUE THREAD

**Issue by doantheanh172tb** [composer/satis#444]
my issue with:  composer update

Can not download package between 2 computers

Loading composer repositories with package information
Warning: Accessing 192.168.123.102 over http which is an insecure protocol.

  [Composer\Downloader\TransportException]
  The "http://192.168.123.102:88/packages.json" file could not be downloaded:
   failed to open stream: No connection could be made because the target mach
  ine actively refused it.

please help me,
tks all!

**Comment by PatrickRose** [comment]
This looks like you have a firewall or something preventing access and it's not a satis issue?

**Comment by curry684** [comment]
The warning comes from Composer for all insecure sources, and has no relationship whatsoever with Saris.

**Comment by curry684** [comment]
The error is just a network issue. Check your firewalls indeed.
