### ISSUE TITLE
NO_PROXY (uppercase) on windows is not supported

### ISSUE THREAD

**Issue by sunlix** [composer/satis#453]
Here there,

I've saw that the uppercase variant of the `NO_PROXY` env var is not supported, like it was before composer < 1.6.0
Could this be implemented to satis too?

I would really appreciated. :)

**Comment by alcohol** [comment]
Sorry, can you elaborate?

Satis uses Composer for a lot of the heavy lifting. So if you are saying that Composer 1.6.0 supports this, then we should simply update our dependency on `composer/composer` in Satis.

**Comment by sunlix** [comment]
Ah yeah, that sounds logically. :D
Just updated satis' composer dependency to 1.6.2 and it just works. :)
Should I send a Pull Request?

**Comment by alcohol** [comment]
Sure, go ahead.
