### ISSUE TITLE
requirement did not match any package

### ISSUE THREAD

**Issue by zengmm** [composer/satis#461]
**satis.json**
```
{
    "name": "Private Repository",
    "homepage": "http://satis.test",
    "repositories": [
        {"type": "vcs", "url": "http://ip:port/private-composer/composer-lib.git"}
    ],
    "require-all": true,
    "config": {
        "secure-http": false
    }
}
```
**error**
```
The contao-legacy/bit3basics * requirement did not match any package      
The contao-legacy/diffiehellman * requirement did not match any package
The contao-legacy/hidepagetitle * requirement did not match any package
The contao-legacy/phpseclib * requirement did not match any package
The contao-legacy/ziparchivecto * requirement did not match any package
The crunchy/crunchysignup * requirement did not match any package
The dayax/collections * requirement did not match any package
The ellicom/mailgun * requirement did not match any package
The ellicom/markdown * requirement did not match any package
The google/adwords * requirement did not match any package
The henrikbjorn/flint * requirement did not match any package
The henrikbjorn/raekke * requirement did not match any package
```
**command**
```
composer create-project composer/satis:dev-master --keep-vcs
php bin/satis build satis.json web/
```

**Comment by alcohol** [comment]
Not a lot of information available.

But it looks like you are using a private repository, and by default Satis will also try to mirror/proxy all dependencies. Obviously those dependencies are not available in your private repository.

Solution(s):

1) enable packagist.org as a repository,
2) disable mirroring of dependencies.

**Comment by zengmm** [comment]
Handling private packages
https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md
Composer version 1.4.2

**satis.json**

{
    "name": "Private Repository",
    "homepage": "http://satis.test",
    "repositories": [
        {"type": "vcs", "url": "http://ip:port/private-composer/composer-userlib.git"}
    ],
    "require-dependencies": false,
    "require": {
        "private-composer": "dev-master"
    },
    "config": {
        "secure-http": false
    }
}

**command**

php bin/satis build satis.json web/

**error info**

Scanning packages
Warning: Accessing 58.210.111.196 over http which is an insecure protocol.
The private-composer dev-master requirement did not match any package     
Writing packages.json
Pruning include directories
Writing web view

**Comment by alcohol** [comment]
It is difficult to communicate like this.

See https://composer.github.io/satis/config for a simple configuration example.

**Comment by zengmm** [comment]
thanks! it’s my mistake.
i have to define the correct private packages in the `require` block

**Comment by Xuzan9396** [comment]
![image](https://user-images.githubusercontent.com/24741439/38033216-2075a652-32d2-11e8-86b5-7fd752b1164d.png)
@zengmm  How does this work?

**Comment by zengmm** [comment]
@Xuzan9396 the key in the `require` block is the namespace of php file
