### ISSUE TITLE
Gitlab subgroup url is rewritten wrong

### ISSUE THREAD

**Issue by Erikvv** [composer/satis#466]
I host a project at the following location:

    { "type": "gitlab", "url": "https://gitlab.polderknowledge.nl/polderknowledge/audit/test-project.git"},

From the verbose logging I can see satis build tries to access this url:

https://gitlab.polderknowledge.nl/polderknowledge/api/v3/projects/audit%2Ftest-project

However it should be this one:

https://gitlab.polderknowledge.nl/api/v3/projects/polderknowledge%2Faudit%2Ftest-project

**Comment by alcohol** [comment]
This is handled by internal components from Composer. So you should probably file a bug with `composer/composer` if you believe you've found one.

**Comment by Erikvv** [comment]
Ok thanks.

**Comment by Erikvv** [comment]
According to the issues this is fixed in the 1.5 release of composer

**Comment by alcohol** [comment]
Which version of Satis are you using?

**Comment by stof** [comment]
@alcohol the 1.0 tag of Satis was using Composer 1.4.2. Satis has been updated to newer Composer versions in master, but this is not released

**Comment by alcohol** [comment]
Yeah because master is definitely not BC with 1.x anymore. I would highly recommend just running master (from source or in Docker).

**Comment by alcohol** [comment]
However, we can accept PR's on the 1.x branch to update the `composer.lock` file with the latest supported releases for that branch, and I can tag additional 1.x releases from that branch.
