### ISSUE TITLE
Support for Gitlab API v4

### ISSUE THREAD

**Issue by Wirone** [composer/satis#486]
Satis v1.0.0 does not support Gitlab API v4. If repository type is set to `gitlab` and build command is run, Gitlab returns `410 Gone` HTTP code (we have 11.0.1 on own server).

Solution: Update `composer/composer` to at least [1.5](https://github.com/composer/composer/releases/tag/1.5.0), but on my local Satis instance I've updated to 1.7.0 and it's working.

We need this to serve `dist` packages (Satis takes URLs from Gitlab API) without losing ability to restrict downloading packages only with permissions to repository. `archive` option in Satis is not a solution because it exposes packages for downloading without checking access rights.

**Comment by Wirone** [comment]
@alcohol I've tested it locally on my Satis instance. I've changed constraint to `^1.7` and run `composer update composer/composer`. Now Satis is listing my packages with `dist` section containing URL to Gitlab's API v4 resource, from `packages.json`'s include file:

```
"source": {
    "type": "git",
    "url": "git@gitlab.tld:foo/bar.git",
    "reference": "0f33db9260a02a6ab92eca11f48eaee83a9bdba6"
},
"dist": {
    "type": "zip",
    "url": "https://gitlab.tld/api/v4/projects/foo%2Fbar/repository/archive.zip?sha=0f33db9260a02a6ab92eca11f48eaee83a9bdba6",
    "reference": "0f33db9260a02a6ab92eca11f48eaee83a9bdba6",
    "shasum": ""
}
```

Those resources are accessible and files are downloadable, also returns 404 when user is not logged in.

The only thing that I did not test yet is downloading those packages from project having those in `require`, but it should work while dist URLs are present and valid.

**Comment by Wirone** [comment]
@alcohol I found one issue with `composer/composer` 1.7.0: when cache path is configured in `satis.json` like:

```
"config": {
    "cache-dir": "/var/cache/composer"
}
```

Gitlab API paths are malformed in a weird way. I have for example:

```
"repositories": [
    { "type": "gitlab", "url": "https://gitlab.tld/foo/bar" }
]
```
and when running `bin/satis build` I got: `Skipping Exception 'The "https:///api/v4/projects/%2Fbar" file could not be downloaded: failed to open stream: operation failed'.` - domain and vendor name is missing. I've tested it with `/var/cache/composer` (the path we've been using for a long time), I've cleared whole directory, then I've changed to `/home/user/.composer/cache`, without success. I had to remove `cache-dir` from config and it's working, our packages are listed with working DIST files.

It doesn't make sense for me (cache dir related to API URLs?), but it works this way :)

For reference, my installed packages after updating `composer/composer`.
```
$ composer show

composer/ca-bundle                 1.1.1   Lets you find a path to the syst...
composer/composer                  1.7.0   Composer helps you declare, mana...
composer/semver                    1.4.2   Semver library that offers utili...
composer/spdx-licenses             1.4.0   SPDX licenses list and validatio...
composer/xdebug-handler            1.1.0   Restarts a process without xdebug.
doctrine/instantiator              1.0.5   A small, lightweight utility to ...
justinrainbow/json-schema          5.2.7   A library to validate a json sch...
mikey179/vfsStream                 v1.6.5  Virtual file system to mock the ...
myclabs/deep-copy                  1.7.0   Create deep copies (clones) of y...
phpdocumentor/reflection-common    1.0.1   Common reflection classes used b...
phpdocumentor/reflection-docblock  3.3.2   With this component, a library c...
phpdocumentor/type-resolver        0.4.0  
phpspec/prophecy                   1.8.0   Highly opinionated mocking frame...
phpunit/php-code-coverage          4.0.8   Library that provides collection...
phpunit/php-file-iterator          1.4.5   FilterIterator implementation th...
phpunit/php-text-template          1.2.1   Simple template engine.
phpunit/php-timer                  1.0.9   Utility class for timing
phpunit/php-token-stream           1.4.12  Wrapper around PHP's tokenizer e...
phpunit/phpunit                    5.5.4   The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       3.4.4   Mock Object library for PHPUnit
psr/log                            1.0.2   Common interface for logging lib...
sebastian/code-unit-reverse-lookup 1.0.1   Looks up which function or metho...
sebastian/comparator               1.2.4   Provides the functionality to co...
sebastian/diff                     1.4.3   Diff implementation
sebastian/environment              2.0.0   Provides functionality to handle...
sebastian/exporter                 1.2.2   Provides the functionality to ex...
sebastian/global-state             1.1.1   Snapshotting of global state
sebastian/object-enumerator        1.0.0   Traverses array structures and o...
sebastian/recursion-context        1.0.5   Provides functionality to recurs...
sebastian/resource-operations      1.0.0   Provides a list of PHP built-in ...
sebastian/version                  2.0.1   Library that helps with managing...
seld/jsonlint                      1.7.1   JSON Linter
seld/phar-utils                    1.0.1   PHAR file format utilities, for ...
symfony/console                    v3.4.14 Symfony Console Component
symfony/debug                      v3.4.14 Symfony Debug Component
symfony/filesystem                 v3.4.14 Symfony Filesystem Component
symfony/finder                     v3.4.14 Symfony Finder Component
symfony/polyfill-ctype             v1.8.0  Symfony polyfill for ctype funct...
symfony/polyfill-mbstring          v1.9.0  Symfony polyfill for the Mbstrin...
symfony/process                    v3.4.14 Symfony Process Component
symfony/yaml                       v3.4.14 Symfony Yaml Component
twig/twig                          v1.35.4 Twig, the flexible, fast, and se...
webmozart/assert                   1.3.0   Assertions to validate method in..
```

**Comment by morsok** [comment]
Just had the same issue with the url not having the host, but i'm not using cache-dir so I didn't managed to make it work, i'm trying adding thoses repo as git and not gitlab for the moment.

**Comment by stof** [comment]
the issue here is that Satis 1.0.0 is 11 months old. We have (currently) 107 commits in master after that. And in particular, Composer got updated to newer versions.
