### ISSUE TITLE
Missing directories in package zip 

### ISSUE THREAD

**Issue by vaxul** [composer/satis#492]
Composer version 1.7.1
Satis Version 1.0.0

satis.json
```json
{
	"name": "Composer-Package-Repository",
	"homepage": "https://packages.example.org",
	"repositories": [
		{
			"type": "vcs",
			"url": "ssh://git@stash.medienwerft.de:7999/mwcp/satis-test.git"
		}		
	],
	"archive": {
		"directory": "dist",
		"format": "zip",
		"skip-dev": true
	},
	"require": {
		"medienwerft/satis-test": "*"
	}
}
```

For testing purpose I created a simple (temporary public) test-repository:
https://stash.medienwerft.de/projects/MWCP/repos/satis-test/browse

This example package has an directory tree like a common custom TYPO3 base distribution. This includes a folder for a custom extension in /web/typo3conf/ext/project/.

The odd thing is, that after Satis zipped the [v0.2 package](https://stash.medienwerft.de/projects/MWCP/repos/satis-test/browse/web/typo3conf/ext/project), in [medienwerft-satis-test-v0.2-8afd44.zip](https://github.com/composer/satis/files/2285914/medienwerft-satis-test-v0.2-8afd44.zip) only the folder down to /web/typo3conf/ are included in the zip. The folder /web/typo3conf/ext/project/ is missing in the zip.

In the previous [v0.1 package](https://stash.medienwerft.de/projects/MWCP/repos/satis-test/browse/Testfolder/Testsubfolder/Testsubsubfolder?at=refs%2Ftags%2Fv0.1) within [medienwerft-satis-test-v0.1-c02bb4.zip](https://github.com/composer/satis/files/2285915/medienwerft-satis-test-v0.1-c02bb4.zip) the folders /Testfolder/Testsubfolder/Testsubsubfolder/ is included in the zip.

Could someone explain me the key difference between the Satis-handling of v0.1 and v0.2?

Best regards!

**Comment by vaxul** [comment]
Any idea how I could manage it to nail the problem down? I'm currently clueless.

**Comment by alcohol** [comment]
Probably related to your `.gitignore` rules.

**Comment by vaxul** [comment]
Thanks for the hint. With this I found https://github.com/composer/satis/issues/204#issuecomment-186279357

The problem are the trailing slashes for folders for the excludes rules in the .gitignore file.

**Wrong**
```
# TYPO3
/vendor
/web/*

# Project
!/web/typo3conf
/web/typo3conf/*
!/web/typo3conf/AdditionalConfiguration.php
!/web/typo3conf/realurl_conf.php
!/web/typo3conf/ext
/web/typo3conf/ext/*
!/web/typo3conf/ext/project
```

**Working**
```
# TYPO3
/vendor
/web/*

# Project
!/web/typo3conf/
/web/typo3conf/*
!/web/typo3conf/AdditionalConfiguration.php
!/web/typo3conf/realurl_conf.php
!/web/typo3conf/ext/
/web/typo3conf/ext/*
!/web/typo3conf/ext/project/
```

With this the Testversion 0.3 works as expected.

But I've not found a reason. Is this a Satis- or Composer-Bug?

**Comment by alcohol** [comment]
Honestly, not sure.
