### ISSUE TITLE
Exception on build with repository filter

### ISSUE THREAD

**Issue by ramunasd** [composer/satis#493]
satis throws exception when running `build` with option `--repository-url` and either `require-dependencies` or `require-dev-dependencies` enabled.

```
PHP Warning:  Uncaught ErrorException: Object of class Composer\Repository\VcsRepository could not be converted to string in .../vendor/composer/satis/src/PackageSelection/PackageSelection.php:210
```

**Comment by alcohol** [comment]
Are you on the latest version?

**Comment by ramunasd** [comment]
Sorry, forgot to mention details.
From `composer show`:
```
composer/composer                    1.7.2              Composer helps you declare, manage and install dependencies of PHP projects, ensuring you have the right stack everywhere.
composer/satis                       dev-master 880621d Simple Repository Generator
```

Error occurs when array_diff() is called with two collections of repositories at:
https://github.com/composer/satis/blob/master/src/PackageSelection/PackageSelection.php#L210

**Comment by alcohol** [comment]
@ph-fritsche since you wrote this change, do you have time to look into this?

**Comment by ph-fritsche** [comment]
I'm on it

**Comment by ph-fritsche** [comment]
I'm not sure if GitHub notifies of the commits referencing an issue... and the master here is ahead now
Do you want me to rebase and/or open a separate pull request?

**Comment by alcohol** [comment]
I did not get a notification, no. I would prefer a rebased PR if it is not too much trouble :-)

**Comment by alcohol** [comment]
Merged, can you let us know if this resolved your issue @ramunasd ?

**Comment by ramunasd** [comment]
works now, many thanks @alcohol @ph-fritsche
