### ISSUE TITLE
Satis fails if zip extension is not available

### ISSUE THREAD

**Issue by aminebenkeroum** [composer/satis#503]
Hey I was trying to run Satis on my server, but there is a problem 

`Creating local downloads in '/space/www//data/current/www-docs//dist'
Dumping 'XXX'.
  - Installing XXX (1.34.1): Executing command (CWD): git --version
Cloning 828c1001ded133dcb79f1ccc94c21ef1d97a7755
Executing command (CWD): git clone --no-checkout 'git@bitbucket.xxx.git' '/tmp/composer_archive5baa3d740acdb' && cd '/tmp/composer_archive5baa3d740acdb' && git remote add com
poser 'git@bitbucket.org:xxx.git' && git fetch composer
Executing command (/tmp/composer_archive5baa3d740acdb): git branch -r
Executing command (/tmp/composer_archive5baa3d740acdb): git checkout '1.34.1' --
Executing command (/tmp/composer_archive5baa3d740acdb): git reset --hard '828c1001ded133dcb79f1ccc94c21ef1d97a7755' --

In Filesystem.php line 274:

  [ErrorException]
  copy(/tmp/composer_archive5baa3d7cb0c50.zip): failed to open stream: No such file or directory
`

The archive folders exists sometimes but there are no zip archives.

Any idea? Thank you.

**Comment by alcohol** [comment]
Need more information about host, OS, environment, etc.

**Comment by aminebenkeroum** [comment]
- Debian GNU/Linux 8.5 (jessie)
 - Linux 3.16.0-4-amd64 x86_64
 - Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
     * 1 CPU with 1 core(s)
 - Memory: 4057636kB
 - Swap  : 499708kB

Thanks

**Comment by alcohol** [comment]
I need a satis.json to reproduce the problem.

**Comment by aminebenkeroum** [comment]
@alcohol The json file contains private repos, but its something like this:

`{
    "name": "K",
    "homepage": "https://.....com",
    "archive": {
        "directory": "dist",
        "format": "zip",
        "skip-dev": false
    },
    "repositories": [
	{
            "type": "vcs",
            "url": "git@bitbucket....../k.git"
        }
   ],
    "require-all": true,
    "require": {
        "k/installer": "*",
        "k/plugin-post-type-event": ">=1.0.1",
        "k/plugin-blog-post-type": "*",
        "k/plugin-spacedust": "~1.0.9",
        "k/theme-k": ">=1.45",
        "k/tool-video-importer": ">=0.9.1"
    }
}`

**Comment by alcohol** [comment]
I'm sorry, but if I cannot reproduce the issue I cannot debug it, and thus I simply cannot help you any further.

**Comment by aminebenkeroum** [comment]
I hadn't a zip extension installed

**Comment by alcohol** [comment]
Weird, would have expected a more specific error in that case.. 🤔

**Comment by hannius** [comment]
Do you have solved the problem of "[ErrorException] copy(/tmp/composer_archive5baa3d7cb0c50.zip): failed to open stream: No such file or directory", I have the same question, could you tell me how to figure out that problem?

**Comment by aminebenkeroum** [comment]
Install the Zip extension on your instance
