### ISSUE TITLE
streamline the UI

### ISSUE THREAD

**Issue by staabm** [composer/satis#504]
the satis web UI uses a lot of room for the "repository-config" section. this information is only required on the initial setup of your composer workflow.

IMO we could e.g. collapse this area by default and expand it on click of the `Add this Satis repository to your composer.json` label.

bottom-line: the most important information - the package-list and its releases - do not use the most space of the website (above the fold).

wdyt?

**Comment by alcohol** [comment]
Sounds like a good improvement :+1:

**Comment by staabm** [comment]
> Thats what the HTML element "details" does by itsel

correct. it requires a polyfill to work in all browsers though.

therefore I figured its easier with this few lines of code.
