### ISSUE TITLE
Packages dump - minify option

### ISSUE THREAD

**Issue by cfv1000** [composer/satis#510]
Hello,

When the JSON files are written (like the includes/all$%sha%.json) file are written, the content is generated with JSON_PRETTY_PRINT.

Would it be accepted to submit for merging a version where this can be removed with a command flag? 

```php
php bin/satis satis.json --no-html-output --no-pretty-print web
```
Results 
![image](https://user-images.githubusercontent.com/3073353/46965728-53989780-d0b4-11e8-987d-dc4ef3430838.png)

The file size is reduce with 40-50% depending on the repositories. 
On the given example ( only composer/satis ) was given in config, but the difference is from 17kb to 9kb
On larger configurations, this will translate in better transfer speed.

Waiting for approval for implementation

**Comment by alcohol** [comment]
Filesize on disk will probably not make that much of a difference. Most webservers will gzip the response, so in the end the difference between what you would have to download in either scenario is much smaller.

But, I will not say no to a PR that implements this feature. If you (or someone else) submits it, I will merge it :-)

**Comment by cfv1000** [comment]
In production, we have a setup without "provision": true. The output file is 15MB. By minifying the json, the size is reduced to 6-7MB. 
This should also translate in transfer speed when running composer update / composer install commands.

PS: We will also enable "provision", of course. :) 
I'll start working on the feature soon enough.

**Comment by staabm** [comment]
> The output file is 15MB. By minifying the json, the size is reduced to 6-7MB.

Did you try that with gzip or brotli enabled? I would guess that the diff gets a lot smaller

**Comment by cfv1000** [comment]
Compressing the transfers is not the same as minifying the transferred data. 
I'd like to point out that this is not a bug report - i know we can gzip, use web servers settings(to cache for instance), use provision, use all kind of methods to speed up our transfers. 

One of those things is data optimization pre-transfer - like minification.

**Comment by staabm** [comment]
> Compressing the transfers is not the same as minifying the transferred data.

Thats right, but the resulting file size might be similar
