### ISSUE TITLE
Display git tags in web interface

### ISSUE THREAD

**Issue by tfmm** [composer/satis#514]
I'm looking to be able to display the tags from the git repositories in the web interface. I was wondering if this data was pulled in already, and if so, how I might be able to add it to the twig template.

**Comment by alcohol** [comment]
Can you share a screenshot of what you currently get? Because tags should already be in there..

**Comment by SvenRtbg** [comment]
Tags that are versions. Not any tags, I assume.

**Comment by tfmm** [comment]
Odd, so they are showing up now after re-building for the 5th time, not sure why they weren't showing up before, my mistake, I'll close this out.
