### ISSUE TITLE
hardcoded link to root

### ISSUE THREAD

**Issue by glensc** [composer/satis#522]
https://github.com/composer/satis/blob/6d7ba9292ce6d9ac26af9c21c147cdb063e4584d/views/index.html.twig#L22-L24

```twig
            <a href="/">
                <h1>{{ name|default('Composer repository') }}</h1>
            </a>
```

imho there's config key `homepage` which should be used here, instead of hardcoding.

**Comment by glensc** [comment]
for example, i have satis repo online in this url:
- https://eventum.github.io/composer/

and the link leads to:
- https://eventum.github.io/

where is nothing present, just 404

imho the `homepage` key should be used there:
- https://github.com/eventum/composer/blob/d3e2db40a7fdb879f46b275060de80cfff59238a/satis.json#L4

**Comment by glensc** [comment]
the `a href="/"` was added in:

- https://github.com/composer/satis/commit/820c7cda9002f69d8fb2b7edf984ec29e2dbf8d3
- via https://github.com/composer/satis/pull/401

**Comment by alcohol** [comment]
Feel free to submit a PR
