### ISSUE TITLE
Deprecation warning for name attribute in satis.json

### ISSUE THREAD

**Issue by tburschka** [composer/satis#526]
The name in the satis.json is treated like a repository and so a deprecation warning is thrown during build:

```
Deprecation warning: Your package name Satis Repository is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.
```

**Comment by olafnorge** [comment]
Hi @alcohol any update on the issue?

**Comment by alcohol** [comment]
This is related to a change in Composer, and as such not really something we can fix here.

**Comment by konstantinosbotonakis** [comment]
Had the same issue.
My satis package name was something like this:
**My Repo**

changed it to:
**konstantinos/myrepo**

and it worked.

Change:
File: satis.json

```
{
  "name": "konstantinos/myrepo",

...
```

**Comment by alcohol** [comment]
Similar to #656 but the latter is more up to date since we updated to Composer v2.
