### ISSUE TITLE
Information about require-all

### ISSUE THREAD

**Issue by rjvandoesburg** [composer/satis#536]
Hello,

So after updating from version 1.0.0 (after a long overdue wait) I found some things have changes.
One of which is `require-all`, now I don't fully understand this. If I set this to `true` am I going to get a full clone of all packages required by my packages (recursive)? I am asking because yesterday I tried this and leaving it for about 3 hours I got an exception so still don't know what it does.

Or am I creating a complete clone of Packagist, at this point I don't know.
If I set `require-all` to `false` it is done in a jiffy and when requiring packages from satis those will be downloaded from satis and the rest from other repositories (packagist) correct?

I hope someone can shed some light on this subject as it is confusing me :(

Cheers!

**Comment by alcohol** [comment]
> selects all versions of all packages in the repositories you defined

If you have not disabled packagist as a repository source, then yes, it will attempt to mirror packagist, which is probably a terrible idea.

**Comment by rjvandoesburg** [comment]
Ah, so by setting packagist as `false` in the config I no longer need to add the `require` section in the config.

I just tried and by doing that I do get the expected result. Thanks!
