### ISSUE TITLE
Missing dependency versions after re-installing on new server

### ISSUE THREAD

**Issue by courtney-miles** [composer/satis#539]
I have have had to recently re-install Satis on a new server.  As a part of that I copied the `satis.json` file to the new installation and ran the build to fetch all the packages.

However, it did not download all past versions of dependencies, such that our `composer.lock` file wants a slightly older version of a dependency and Satis does not have it.

For example, in satis.json we have `"doctrine/orm": ">=2.5"`, and it has downloaded all those versions.  However, where `doctrine/dbal` is a dependency of `doctrine/orm`, it has only downloaded `v2.9.2`, `v2.6.3`, `v2.6.0`, `v2.5.13`, `v2.5.0`, and not any other version -- our `composer.lock` file requires `v2.8.0`.

I'm guessing Satis does not download all possible versions that match a dependency because that could become huge.

So is there a file from the old server that I could grab and copy to the new server to prompt it to download all the versions it previously hosted from the old server?

Note that I deliberately want to grab fresh copies of all packages, rather than copy them from the old server -- but let me know if grabbing them from the older server is the only way.

**Comment by alcohol** [comment]
Can you try setting `require-dependency-filter` to `false` in your `satis.json`?

**Comment by courtney-miles** [comment]
> Can you try setting `require-dependency-filter` to `false` in your `satis.json`?

Thank you -- that grabbed them all. It has saved me from having to add explicit second-level dependencies to `satis.json`.

Is this an undocumented feature?  I was Googling to find exactly what it did but couldn't find anything.

**Comment by alcohol** [comment]
It was a change introduced a while ago, but not really documented yet (because we pretty much have no documentation at all).

**Comment by courtney-miles** [comment]
> because we pretty much have no documentation at all

I understand :D  Thanks very much for your assistance.
