### ISSUE TITLE
Installation with docker as described in Readme does not work

### ISSUE THREAD

**Issue by Tweetdezweet** [composer/satis#545]
I followed the instructions in the readme to run Satis as a docker image but I only get the following output:
```

[WARN  tini (7)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
File not found: /build/satis.json
```

I am running Debian with php7.0 installed through apt-get and composer installed locally not globally, is the issue that I haven't done a system wide install of composer?

Any help is greatly appreciated.

**Comment by alcohol** [comment]
The issue is quite clear form the output:

```
File not found: /build/satis.json
```

Can you share the **exact** command that you ran?
And in what directory and which files/folders existed in said directory?

**Comment by Tweetdezweet** [comment]
I ofc understand from the output that there is no satis.jon file, but since there is no mention of creating such a file in the readme and having followed the instructions in the Readme I have no indication as where to look for the cause of this missing file.

## Run as Docker container

Pull the image:

``` sh
docker pull composer/satis
```

Run the image (with Composer cache from host):

``` sh
docker run --rm --init -it \
  -u $(id -u):$(id -g) \
  -v $(pwd)/build:/build \
  -v "${COMPOSER_HOME:-$HOME/.composer}:/composer" \
  composer/satis
```

These are the commands I ran, copy pasted them from the readme to avoid typos.

I ran it in the folder /home/me/satis_folder which at that point only contained composer.phar which is executable.

**Comment by alcohol** [comment]
Oh dear, that documentation seems wrong. I assume your `satis.json` is located at `/home/me/satis_folder/satis.json`. The example however only mounts `/home/me/satis_folder/build` on top of `/build` inside the docker container. The default command that we run in the container expects that your project root directory is mounted at `/build`. So that should just be `-v $(pwd):/build`.

**Comment by alcohol** [comment]
Maybe we should also explicitly state in the README.md that running satis without a `satis.json` does not work, or provide some example as a first step.

**Comment by Tweetdezweet** [comment]
that would be really great, as someone who has zero prior knowledge about Satis it's hard to figure things out

I was able to get Satis working a few minutes before you first replied but not in a docker container and using the steps from the documentation link in the readme.

But even that documentation assumes the reader already has quite bit of knowledge about the project.
Since I will have to document the use of Satis for my colleagues anyway, I might be able to share some things/insights from a "noob perspective" that can help improve documentation (direct contribution is not possible without an experienced Satis user/developer proof reading it).

Where would be the appriopate place to share or send this to?

Thank you for looking into this!

**Comment by alcohol** [comment]
Pull requests are more than welcome. There is a start on some new documentation that can be found in the `docs/` folder in this repository. The output of that can be found [here](https://composer.github.io/satis/).

**Comment by Tweetdezweet** [comment]
Great! Thanks again, I will close the issue :)
