### ISSUE TITLE
Small formatting glitch in the HTML page

### ISSUE THREAD

**Issue by g-rusev** [composer/satis#562]
Hello,

There is a small time formatting issue on the SATIS auto generated HTML page. See the image below.

For some period, it shows: 

 **Last updated: 7about hours ago** 

Better will be:

 **Last updated: about 7 hours ago**

Not critical, but annoying :)

![image](https://user-images.githubusercontent.com/13536076/65707917-24492380-e096-11e9-9405-be669cf594e0.png)

**Comment by alcohol** [comment]
As far as I can tell, the compiled output from webpack breaks the locale template strings (the placeholder is dropped from all of them). Therefor the value of N is always prefixed to the string.
