### ISSUE TITLE
Composer gives wrong chmod if packages come from Satis

### ISSUE THREAD

**Issue by a-camacho** [composer/satis#577]
**Describe the bug**

We are using SATIS to have a private repository of packages. We get the packages from gitlab tags. It works like a charm, but we observed something very weird : when installing a package with composer, that comes from Satis, composer gives the wrong chmod to files. It gives CHMOD 666 instead of 644.

What is weird is that if we get the .zip or .tar file from Satis, and unzip it manually somewhere on a machine (os x or linux) there is no problem : files are chmod'ed with 644.

**To Reproduce**
As our repository is private, I can't give your the exact command to reproduce error publicly. But I could give it privately.

```composer create-project company/product-name destination-folder --repository=https://repository.our-company.com```

PS: Composer is installed without any custom configuration.

**Outcome**
I can upload it, but no information about permissions in logs.

**Expected behavior**
I would expect composer to download .zip or .tar file from SATIS, and unzip it in defined directory using **classic** permissions or the ones that should be inherited from server configuration.

**Additional context**
Debian Linux server - 10 Buster
Also tested on various Mac OS X machines.

**Comment by alcohol** [comment]
It entirely depends on your environment. Most likely you are dealing with zip archives since they most often tend to have difficulty handling permissions.

In the case of zip archives, Composer will try to use the `unzip` binary first, and fallback to the `ZipArchive`. The latter does not handle permissions well at all to my recollection. So make sure your environment has `unzip` installed.

**Comment by a-camacho** [comment]
We used zip and tar archives. Both gave us the same error.
In linux servers and in mac os x machine, I have zip AND unzip installed.

Packages are still installed with wrong permissions. 

If i use "--prefer-source" parameter in composer, it uses git reposity and not zip/tar files and there is of course no permissions problems.

Do you have any idea where I could continue debugging this ?
Thanks a lot.

**Comment by stof** [comment]
There is an issue where archives generated by Composer (which is what Satis exposes) don't store the proper permissions (and so even with unzip being able to apply them when unzipping, the info is already lost in the archive). There is an open PR fixing this at https://github.com/composer/composer/pull/8331

**Comment by alcohol** [comment]
@stof that doesn't really explain the following though:

> What is weird is that if we get the .zip or .tar file from Satis, and unzip it manually somewhere on a machine (os x or linux) there is no problem : files are chmod'ed with 644.

**Comment by alcohol** [comment]
I'm a bit puzzled as to where it exactly goes wrong then though. It sounds like you have the right tools in the right place. Perhaps we're simply missing a crucial step in the information provided here. That is the downside of private repositories/projects. We simply can't see all the details :-(
