### ISSUE TITLE
New relase

### ISSUE THREAD

**Issue by mvorisek** [composer/satis#581]
The last release is 2 years old. Can next release be made?

**Comment by alcohol** [comment]
I don't really see the point. Satis doesn't do any meaningful versioning. A release wouldn't represent anything other than a fixed point in time. There is no semver, no roadmap, no changelog. Current master branch is the current version. Older versions are basically not supported. If you want to run Satis, checkout the master branch (or the `latest` tag of the Docker container, it's updated constantly).

**Comment by mvorisek** [comment]
> Current master branch is the current version.

Thanks for the info that master is considered as current **stable** version.

**Comment by alcohol** [comment]
That is not what I said :sweat_smile: 

It should be stable, hopefully. But no promises can be made.
