### ISSUE TITLE
PHP version documentation outdated

### ISSUE THREAD

**Issue by moztech** [composer/satis#582]
https://getcomposer.org/doc/00-intro.md
The documentation states PHP version 5.3.2+ is required
`Composer requires PHP 5.3.2+ to run`

However the default installation is via composer and requires PHP 7.2+
https://github.com/composer/satis/blob/master/composer.json
```    
"require": {
        "php": "^7.2",
```

Actual behaviour on a stock CentOS 7 box:
```
$ composer create-project composer/satis:dev-master
[InvalidArgumentException]
Could not find package composer/satis with stability stable in a version installable using your PHP version 5.4.16.
```

If the documentation could be updated to mirror the composer.json file it should prevent others following me into building a CentOS 7 server defaulting to PHP 5.4 which can't then install composer.
If the docs were within the project I'd happily have issued a PR but don't believe that to be the case.

**Comment by alcohol** [comment]
Somewhat related to #403 - having the documentation in another repo right now does not make much sense.

**Comment by SvenRtbg** [comment]
Composer still runs with PHP 5.3.2, but Satis does not. Updating the Composer docs for a Satis issue is wrong.
