### ISSUE TITLE
GitHub is deprecating auth via query param -- Composer 1.9.3 has a fix

### ISSUE THREAD

**Issue by azito122** [composer/satis#593]
**Describe the bug**
GitHub is deprecating the ability to authenticate via query parameter: https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters
This causes warnings to be sent by GitHub, and eventually will break.

**To Reproduce**
Attempt to use Satis for any private repository, auth with a token, and the token user will receive an email warning about the deprecation.

**Expected behavior**
That Satis will use the correct method of auth, and not create warnings.

See this issue (https://github.com/composer/composer/issues/8586) for a discussion of the Composer side of this. It seems like updating the internal Composer version to 1.9.3 may be sufficient to resolve this problem.

**Comment by alcohol** [comment]
PRs are welcome

**Comment by marcovtwout** [comment]
If I understand correctly this issue is possibly fixed by https://github.com/composer/satis/pull/585

**Comment by alcohol** [comment]
Yes, unless this issue is similar to #600 
But closing either way
