### ISSUE TITLE
Upgrade to composer 2.0 format

### ISSUE THREAD

**Issue by GromNaN** [composer/satis#594]
**Is your feature request related to a problem? Please describe.**
Composer 2.0 is being actively developed, providing a new repository format.
https://github.com/composer/composer/blob/master/UPGRADE-2.0.md#for-composer-repository-implementors 

**Describe the solution you'd like**
The upgrade can be done in several steps:

- [x] #645 Upgrade dependency to `"composer/composer": "^2.0"` and `"composer/semver": "^2.0"`. ~(`dev-master` while development is not completed)~. And adapt code to all the breaking changes. 
-  [x] #596 Create a new `Builder` to generate the `/p2/%package%.json` files for each package, and add the `"metadata-url": "/p2/%package%.json"` to the main `packages.json`.
-  [ ] Add an option to minify with `Composer\Util\MetadataMinifier::minify()`.
-  [x] Add an option to dump a restrictive list of packages in `"available-packages": [...]`
-  [x] Add the [`providers-api`](https://github.com/composer/composer/blob/master/UPGRADE-2.0.md#providers-api).

**Additional context**
Maybe @naderman, @Seldaek or @alcohol already planned to upgrade Satis on their own ?

**Comment by stof** [comment]
Development on Satis is mostly done by the community. So contributions are welcome

**Comment by alcohol** [comment]
Yeah I have to second what @stof said. We don't actively develop Satis ourselves. It depends entirely on community contributions.

**Comment by designermonkey** [comment]
Satis without Composer v2 support no longer works for github authentication as the token format has changed. Please see here: https://github.com/composer/composer/issues/9907

I'm leaving this here so it's recorded somewhere, not to poke at the maintainers.

**Comment by stof** [comment]
Composer 1 also supports the new github token format. But you need to use an uptodate composer 1.

**Comment by designermonkey** [comment]
Noted. I don't know why composer on my satis server isn't updating to the latest v1 version.

**Comment by alcohol** [comment]
> Noted. I don't know why composer on my satis server isn't updating to the latest v1 version.

What version (or commit ref) of satis are you running?

**Comment by designermonkey** [comment]
It's an ansible thing, not the fault of this repo. Not to worry about it here :)

**Comment by kvelaro** [comment]
Hi there, @alcohol 
We have annoying warning from packagist, and it seems in near feature we will face unpleasant problem.

Warning from Packagist: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/ 

So, maybe its a stupid question but: Will satis with composer v2 come to the world?

**Comment by stof** [comment]
@kvelaro see the comment on https://github.com/composer/satis/pull/645#issuecomment-825532299

**Comment by Deamon** [comment]
Hi, 
I'm work on the minification. 

I started to look at the code but I don't understand what should be minified.

all output files ? 
all files in p2 folder, include directory and package.json ?
only something inside ?

**Comment by Deamon** [comment]
Hi @GromNaN,
since #657 is now merged, I think this task list is now complete!

**Comment by GromNaN** [comment]
Thank you @Deamon

**Comment by Deamon** [comment]
You're welcome @GromNaN, 

do you think that we can have a tag for the v2 version now ? at least an alpha or rc ?

**Comment by alcohol** [comment]
I don't really tag Satis anymore. Most users either run the Docker containers or the master branch. Since Satis is not a library or dependency for other applications, the purpose of tagging also makes less sense to me from a project perspective. What benefit would tags give you?

**Comment by designermonkey** [comment]
The benefit would be knowing what version we were using, for example, if my employer wanted to ensure we used the latest version 1, but not version 2.

**Comment by alcohol** [comment]
We have branches for that.
