### ISSUE TITLE
Update json schema with default values

### ISSUE THREAD

**Issue by Ilyes512** [composer/satis#598]
**Is your feature request related to a problem? Please describe.**

Currently the json schema (https://github.com/composer/satis/blob/master/res/satis-schema.json) does not contain the default values (ie output-html is `true` by default).

**Describe the solution you'd like**

Add the default values to the schema. (https://json-schema.org/understanding-json-schema/reference/generic.html).

**Comment by alcohol** [comment]
Please feel free to submit a PR :+1:
