### ISSUE TITLE
SSH keys not being used in docker

### ISSUE THREAD

**Issue by mabasic** [composer/satis#599]
**Describe the bug**
When I use the docker image to run satis and I use the `-n` flag to tell satis to use SSH keys I get:

```
Failed to clone the git@github.com:xxx/yyy.git repository, try running in interactive mode so that you can enter your GitHub credentials.
```

And

```
In Git.php line 381:

Failed to execute git clone --mirror 'git@github.com:xxx/yyy.git' '/composer/cache/vcs/git-github.com-xxx-yyy.git/'
```

I have tried mounting the SSH keys in the container with:

```
--volume ~/.ssh/id_rsa:/root/.ssh/id_rsa --volume ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
```

But nothing changes, I still get the same error.

 My question is, has anyone managed to workaround this or is everyone just using the GitHub access token?

I have searched the issues on this repository for a solution, but nothing worked. I've also searched the Internet for a solution, but it seems that there is not much about Satis to be found there.

Is the `.ssh` location in the image `/root/.ssh` or is it somewhere else?

**To Reproduce**
```
docker run --rm --init -it \
      --user $(id -u):$(id -g) \
      --volume $(pwd):/build \
      --volume "${COMPOSER_HOME:-$HOME/.composer}:/composer" \
      --volume ~/.ssh/id_rsa:/root/.ssh/id_rsa --volume ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub \
      composer/satis build ./satis.json ./web -n
```

**Outcome**
```
Loading config file /composer/config.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/build): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Scanning packages
Downloading https://api.github.com/repos/xxx/yyy
Executing command (CWD): git config github.accesstoken
Executing command (CWD): git clone --mirror 'git@github.com:xxx/yyy.git' '/composer/cache/vcs/git-github.com-xxx-yyy.git/'
Executing command (CWD): git config github.accesstoken
Executing command (CWD): git --version
Failed to clone the git@github.com:xxx/yyy.git repository, try running in interactive mode so that you can enter your GitHub credentials

In Git.php line 381:

  [RuntimeException]
  Failed to execute git clone --mirror 'git@github.com:xxx/yyy.git' '/composer/cache/vcs/git-github.com-xxx-yyy.git/'
```

**Expected behavior**
I expected it to just work.

**Comment by alcohol** [comment]
What is your host OS?

**Comment by mabasic** [comment]
> 
> 
> What is your host OS?

Ubuntu 18.04

**Comment by alcohol** [comment]
Recommend you use an approach as documented here: https://github.com/docker-library/docs/tree/master/composer#private-repositories--ssh-agent

**Comment by mabasic** [comment]
> 
> 
> Recommend you use an approach as documented here: https://github.com/docker-library/docs/tree/master/composer#private-repositories--ssh-agent

Already tried, I get the same output error.

**Comment by alcohol** [comment]
So you are saying that you literally ran these commands?

```
# enable and export ssh-agent ENV values
eval $(ssh-agent)
# run satis
docker run --rm --init --interactive --tty \
  --volume $(pwd):/build \
  --volume "${COMPOSER_HOME:-$HOME/.composer}:/composer" \
  --volume $SSH_AUTH_SOCK:/ssh-auth.sock \
  --volume /etc/passwd:/etc/passwd:ro \
  --volume /etc/group:/etc/group:ro \
  --env SSH_AUTH_SOCK=/ssh-auth.sock \
  --user $(id -u):$(id -g) \
  composer/satis build ./satis.json ./web -n
```

**Comment by mabasic** [comment]
Previously, I ran the command without this part:

```
--volume /etc/passwd:/etc/passwd:ro \
--volume /etc/group:/etc/group:ro \
```

This time I ran it with that part, and it worked ❤️. Thank you.

Now, how do I get rid of the authenticity prompt that asks me to enter yes or no every time?

**Comment by stof** [comment]
you might need to mount the known-hosts file as well.

**Comment by mabasic** [comment]
> 
> 
> you might need to mount the known-hosts file as well.

I've tried with:

```
--volume ~/.ssh/known_hosts:/root/.ssh/known_hosts
```

but I still get the prompt. Is `/root/.ssh` the right place?

**Comment by alcohol** [comment]
The container does not run as root user, so no that is not the right place. But it should not be necessary if you use the ssh-agent since it should use the known hosts file from your host OS.

**Comment by mabasic** [comment]
> 
> 
> The container does not run as root user, so no that is not the right place. But it should not be necessary if you use the ssh-agent since it should use the known hosts file from your host OS.

Under what user does the container run?

This is my procedure before running the command:

```
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa_xxx
```

And then I run the command.

**Update**: After logging out and back in to the server, the command worked without a prompt. 

Thank you all for your help ❤️ 

Going to close the issue now, hope this helps somebody else.

**Comment by mabasic** [comment]
Quick question. How do you run this docker command every hour?

I tried using cron like so:

```
0 * * * * docker run --rm --init -it --user $(id -u):$(id -g) --volume $(pwd):/build --volume "${COMPOSER_HOME:-$HOME/.composer}:/composer" --volume $SSH_AUTH_SOCK:/ssh-auth.sock --volume /etc/passwd:/etc/passwd:ro --volume /etc/group:/etc/group:ro --env SSH_AUTH_SOCK=/ssh-auth.sock composer/satis build ./satis.json ./web -n >> ./cron.log
```

I can see the command being executed by cron in `/var/log/syslog`, and the file `cron.log` is being created, but it is empty and the command makes no change to the `/web` output directory.

 When I run the docker command manually `cron.log` has output:

```
Scanning packages
Wrote packages to ./web/p2/xxx/yyy.json
Wrote packages to ./web/p2/xxx/yyy~dev.json
Writing packages.json
Pruning include directories
Writing web view
```
Any ideas?

I have tried debugging with:

```
* * * * * docker run hello-world >> hello.log
```

Which runs just fine and creates output text in `hello.log`.

What am I missing?

**Comment by alcohol** [comment]
Aside from removing the `-it`, you might also want to make sure that `cron` runs this job with the right user in order to avoid permission issues.
