### ISSUE TITLE
Satis uses .gitignore file to exclude files from it's compressed package  

### ISSUE THREAD

**Issue by Thijzer** [composer/satis#601]
**Describe the bug**
Satis uses .gitignore file to exclude files from it's compressed package.
Sometimes your git source has tracked files that are now excluded.
We don't want this as it might generate unwanted scenario's with archives.
Also for example in github releases or packagist releases that behavior is not replicated.

**To Reproduce**
Provide configuration file(s) and the exact command that you invoked.

**Outcome**
If applicable, please provide detailed verbose output (`-vvv`) of the command.

**Expected behavior**

**Additional context**

**Comment by alcohol** [comment]
We use the archive manager from Composer.

I could be mistaken, but possibly setting the archive "ignore-filters" value to `true` would make it ignore filters such as `.gitignore` ( https://composer.github.io/satis/config#archive ).

**Comment by hexus** [comment]
I can confirm, setting `"ignore-filters": true` to true circumvents this. I ran into this same issue earlier this year.
