### ISSUE TITLE
need advice on 

### ISSUE THREAD

**Issue by davidtisn** [composer/satis#604]
Hi I was wondering if any one can help me with this issue that has plagued me all day. I have a composer.json that looks like this:

```{
    "name": "magento/project-enterprise-edition",
    "description": "eCommerce Platform for Growth (Enterprise Edition)",
    "type": "project",
    "license": [
        "proprietary"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "require": {
        "isn/shipping": "^1.0.0",
        "magento/extension-b2b": "^1.1",
        "magento/product-enterprise-edition": "2.3.4"
    },
    "minimum-stability": "stable",
    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "isn": {
            "type": "composer",
            "url": "https://github.com/integrated-supply-network/core/"
        }
    },
    "extra": {
        "magento-force": "override"
    }
}
```

In the Github repository for https://github.com/integrated-supply-network/core/, I have a packages.json generated by satis. However when I try to install with composer, I get an exception and a 404 that the file could not be found:

```Using GitHub token authentication
Downloading https://github.com/integrated-supply-network/core/packages.json

                                                                                                                               
  [Composer\Downloader\TransportException]                                                                                     
  The "https://github.com/integrated-supply-network/core/packages.json" file could not be downloaded (HTTP/1.1 404 Not Found)  
                                                                                                                               

Exception trace:
 () at phar:///usr/local/bin/composer.phar/src/Composer/Util/RemoteFilesystem.php:441
```

I do have an auth.json with my access token in it, but if I make my repository public it works fine (although with a 406 error, something about packages.json not formatted correctly). Also, if I put make my repository url: 

```
https://raw.githubusercontent.com/integrated-supply-network/core/master/include/all%2463f61a3d5b39c7c135d842ba7153aea45e30ebe3.json?token=AOGZ12N7JRLXD2RMPOPFYL264PQE4
```

then it works.

**Comment by kevindierkx** [comment]
I believe GitHub simply returns a 404 on unauthenticated requests, that being said I'm 100% sure compose actually uses the auth.json for repositories like you would expect.

Personally I've used something similar like this with basic-auth credentials added to the composer repository URL. `https://user:token@url`

More information: https://developer.github.com/v3/auth/

**Comment by robrecord** [comment]
You could also try this:
```
composer config --global --auth github-oauth.github.com <my-token>
```

**Comment by stof** [comment]
Well, hosting a stais repository in a github repository won't work if you just specify `https://github.com/integrated-supply-network/core`, because `https://github.com/integrated-supply-network/core/package.json` will **not** be the github URL allowing to access the content of the `package.json` file.

**Comment by davidtisn** [comment]
I solved it by adding the key for raw.githubusercontent.com to the auth.json:

`{
   "http-basic": {
      "repo.magento.com": {
         "username": "38e6c94eaa4a6be433a3957a431041f0",
         "password": "c8f8decef6c1b26689a1dab74ab26211"
      }
   },
   "github-oauth": {
      "raw.githubusercontent.com": "07128dab0b0be32805c651ac76cefb57edcdcd9c",
      "github.com": "07128dab0b0bf32805d651ac76cefb57edcdcd9c"
   }
}
`

Here is the composer.json:

`    "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        },
        "isn": {
            "type": "composer",
            "url": "https://raw.githubusercontent.com/integrated-supply-network/packages/master/packages.json"
        }
    },`
