### ISSUE TITLE
Q: Is it possible to filter packages on type?

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [composer/satis#609]
I'm not interested to have projects in satis, is it somehow possible to filter these based on composer.json's type (filter out projects)?

A little more background info: We have a webhook on github company, so every repository is being reported to satis. Currently if satis doesn't find a composer.json it's not added, I would like to have this done also for composer where type is project.

**Comment by alcohol** [comment]
Believe this was resolved with #617
