### ISSUE TITLE
[Bug] Tag metadata not well supported

### ISSUE THREAD

**Issue by Gounlaf** [composer/satis#611]
**Describe the bug**

Hi,

I have an issue with semver specs: build metadata (https://semver.org/#spec-item-10) are not well supported.

**To Reproduce**

Steps to reproduce :
- Create a tag like `v1.0.0+metadata-test-1`
- Make satis refresh repos ; you will have the tag correctly
- Create a tag like `v1.0.0+metadata-test-2`
- Make satis refresh repos ; you will have `v1.0.0+metadata-test-1` but not `v1.0.0+metadata-test-2`
- Delete tag `v1.0.0+metadata-test-1`
- Make satis refresh repos ; you will have `v1.0.0+metadata-test-2`

More disturbing: only the "last created" tag is found;
- Create a tag like `v1.0.0+metadata-test-1` ; OK
- Create a tag like `v1.0.0+metadata-test-2` ; NOT FOUND
- Delete tag `v1.0.0+metadata-test-1`; `v1.0.0+metadata-test-2` Found
- Re-push `v1.0.0+metadata-test-1` ; still not found ;only `v1.0.0+metadata-test-2`

**Expected behavior**

Both `v1.0.0+metadata-test-1` and `v1.0.0+metadata-test-2` should be displayed/listed.

I can reproduce a project example if needed.

Thanks,

Regards.

**Comment by alcohol** [comment]
Does #613 solve this?

**Comment by Gounlaf** [comment]
> Does #613 solve this?

Hi @alcohol,

Yes. I've opened the PR #613 to fix this bug.

**Comment by alcohol** [comment]
Thanks
