### ISSUE TITLE
Enable zip extension in PHP

### ISSUE THREAD

**Issue by clockworkgeek** [composer/satis#621]
**Describe the bug**
When using the Docker image to build, and when including artifacts, there is an error "The artifact repository requires PHP's zip extension"

**To Reproduce**
- Add some definition like this in `satis.json`:
  ```json
    "repositories": [
        {
            "type": "artifact",
            "url": "zips"
        },
    ]
  ```
- Run docker command as instructed:
  ```sh
    docker run --rm --init -it \
      --user $(id -u):$(id -g) \
      --volume $(pwd):/build \
      --volume "${COMPOSER_HOME:-$HOME/.composer}:/composer" \
      composer/satis build
  ```
**Outcome**
```
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/build): git branch -a --no-color --no-abbrev -v
Executing command (/build): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/build): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/build): hg branch
Executing command (/build): fossil branch list
Executing command (/build): fossil tag list
Executing command (/build): svn info --xml

In ArtifactRepository.php line 37:
                                                        
  [RuntimeException]                                    
  The artifact repository requires PHP's zip extension  
                                                        

Exception trace:
  at /satis/vendor/composer/composer/src/Composer/Repository/ArtifactRepository.php:37
 Composer\Repository\ArtifactRepository->__construct() at /satis/vendor/composer/composer/src/Composer/Repository/RepositoryManager.php:146
 Composer\Repository\RepositoryManager->createRepository() at /satis/vendor/composer/composer/src/Composer/Repository/RepositoryFactory.php:163
 Composer\Repository\RepositoryFactory::createRepos() at /satis/vendor/composer/composer/src/Composer/Repository/RepositoryFactory.php:109
 Composer\Repository\RepositoryFactory::defaultRepos() at /satis/vendor/composer/composer/src/Composer/Package/Loader/RootPackageLoader.php:176
 Composer\Package\Loader\RootPackageLoader->load() at /satis/vendor/composer/composer/src/Composer/Factory.php:351
 Composer\Factory->createComposer() at /satis/vendor/composer/composer/src/Composer/Factory.php:576
 Composer\Factory::create() at /satis/src/Console/Application.php:60
 Composer\Satis\Console\Application->getComposer() at /satis/src/Console/Command/BuildCommand.php:175
 Composer\Satis\Console\Command\BuildCommand->execute() at /satis/vendor/symfony/console/Command/Command.php:258
 Symfony\Component\Console\Command\Command->run() at /satis/vendor/symfony/console/Application.php:920
 Symfony\Component\Console\Application->doRunCommand() at /satis/vendor/symfony/console/Application.php:266
 Symfony\Component\Console\Application->doRun() at /satis/src/Console/Application.php:49
 Composer\Satis\Console\Application->doRun() at /satis/vendor/symfony/console/Application.php:142
 Symfony\Component\Console\Application->run() at /satis/bin/satis:60

build [--repository-url [REPOSITORY-URL]] [--repository-strict] [--no-html-output] [--skip-errors] [--stats] [--] [<file> [<output-dir> [<packages>...]]]
```

**Expected behavior**
Tool should scan stated folder for zip files and build normally.

**Additional context**
It is not necessary to have any zip files present. The most probable cause is `extension=zip.so` is missing from `php-cli.ini`

**Comment by clockworkgeek** [comment]
This sort of thing could have been caught by automated testing. I see there are tests available but don't see any of them mention artifacts at all.

**Comment by stof** [comment]
the thing is, Satis does not require you to use artifact repositories.
But if your config file uses them, Composer itself indeed requires the zip extension.

**Comment by clockworkgeek** [comment]
Thanks for replying quickly. This was fixed previously in #411 and #520 so I assumed it would be an obvious fix again.

**Comment by alcohol** [comment]
Should be an easy fix yes, though I was under the impression Composer would just use the system native zip binary if it was available.

**Comment by clockworkgeek** [comment]
I hadn't considered that. Maybe it's an upstream problem since the class `Composer\Repository\ArtifactRepository` starts with this:

```php
    public function __construct(array $repoConfig, IOInterface $io)
    {
        parent::__construct();
        if (!extension_loaded('zip')) {
            throw new \RuntimeException('The artifact repository requires PHP\'s zip extension');
        }
```
...it clearly isn't using the native zip here whereas we know that native zip can be used for extracting downloaded packages.

**Comment by alcohol** [comment]
Can't fix that here though, so including the zip extension for this scenario. Perhaps an issue/PR could be submitted upstream though.

**Comment by clockworkgeek** [comment]
I believe your Dockerfile extends [this Dockerfile](https://github.com/composer/docker/blob/master/1.10/Dockerfile) which already includes a line equivalent to `docker-php-ext-install zip` so I'm not sure where the problem actually comes from. Anyway, thanks for listening and fixing.

**Comment by alcohol** [comment]
No it extends that one only during the build stage (it's a [multistage Dockerfile](https://docs.docker.com/develop/develop-images/multistage-build/)). It extends the official PHP image for the final stage.
