### ISSUE TITLE
Error issue

### ISSUE THREAD

**Issue by barbierp35** [composer/satis#623]
Sorry it's an error, you can delete this issue please.
Thanks

**Comment by stof** [comment]
@barbierp35 issues cannot be deleted on github (at least not without reaching their support). So please close it instead.

**Comment by WebAndCow** [comment]
Sorry but I can't close this issue. I don't have the button. "You need to be a collaborator on a repo to close an issue".
It's only the owner who can delete this issue ?

**Comment by barbierp35** [comment]
@stof Sorry but I can't close this issue. I don't have the button. "You need to be a collaborator on a repo to close an issue".
It's only the owner who can delete this issue ?
