### ISSUE TITLE
Deprecation notice for dependency (justinrainbow/json-schema)

### ISSUE THREAD

**Issue by rtm-ctrlz** [composer/satis#629]
Recently started getting deprecation notice:
```
+ /satis/bin/satis build --no-interaction --stats /composer/satis.json /out
Deprecation Notice: Array and string offset access syntax with curly braces is deprecated in /satis/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriResolver.php:112
Scanning packages
...
```
There is no errors and everything is working as expected.

I'm using docker image `composer/satis` and made a short test:
```
$docker run \
  --rm \
  composer/satis \
  sh -c \
      'php -v; \
       /satis/bin/satis -V; \
       php -l /satis/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriResolver.php'

PHP 7.4.14 (cli) (built: Jan 16 2021 00:10:32) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

Satis 2.0.0-dev

Deprecated: Array and string offset access syntax with curly braces is deprecated in /satis/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriResolver.php on line 112
No syntax errors detected in /satis/vendor/justinrainbow/json-schema/src/JsonSchema/Uri/UriResolver.php
```

<details>
    <summary>check docker image to be actual</summary>

    # check current date
    $ date
    Tue 26 Jan 2021 08:40:48 PM UTC

    # try to pull image
    $ docker pull composer/satis
    Using default tag: latest
    latest: Pulling from composer/satis
    Digest: sha256:05d3a3af637b838066a6add2713d270c6b0a19f6ad88ff5b1d3ec7e6f712a3f7
    Status: Image is up to date for composer/satis:latest
    docker.io/composer/satis:latest

    # check image history
    $ docker image history composer/satis
    IMAGE          CREATED       CREATED BY                                      SIZE      COMMENT
    fd52ab1f59bb   4 hours ago   /bin/sh -c #(nop)  CMD ["--ansi" "-vvv" "bui…   0B
    <missing>      4 hours ago   /bin/sh -c #(nop)  ENTRYPOINT ["/satis/bin/d…   0B
    <missing>      4 hours ago   /bin/sh -c #(nop) WORKDIR /build                0B
    <missing>      4 hours ago   /bin/sh -c #(nop) COPY dir:7cd8feead86c2f50b…   5.48MB
    <missing>      4 hours ago   /bin/sh -c #(nop) COPY file:0165badf982d20f2…   1.83kB
    <missing>      4 hours ago   /bin/sh -c #(nop)  ENV COMPOSER_HOME=/compos…   0B
    <missing>      4 hours ago   /bin/sh -c set -eux;   apk add --no-cache --…   88.6MB
    <missing>      4 hours ago   /bin/sh -c #(nop)  MAINTAINER https://github…   0B
    <missing>      5 days ago    /bin/sh -c #(nop)  CMD ["php" "-a"]             0B
    <missing>      5 days ago    /bin/sh -c #(nop)  ENTRYPOINT ["docker-php-e…   0B
    <missing>      5 days ago    /bin/sh -c docker-php-ext-enable sodium         48.2kB
    <missing>      5 days ago    /bin/sh -c #(nop) COPY multi:efd917b98407edb…   6.74kB
    <missing>      10 days ago   /bin/sh -c set -eux;  apk add --no-cache --v…   63.3MB
    <missing>      10 days ago   /bin/sh -c #(nop) COPY file:ce57c04b70896f77…   587B
    <missing>      10 days ago   /bin/sh -c set -eux;   apk add --no-cache --…   10.4MB
    <missing>      10 days ago   /bin/sh -c #(nop)  ENV PHP_SHA256=f9f3c37969…   0B
    <missing>      10 days ago   /bin/sh -c #(nop)  ENV PHP_URL=https://www.p…   0B
    <missing>      10 days ago   /bin/sh -c #(nop)  ENV PHP_VERSION=7.4.14       0B
    <missing>      10 days ago   /bin/sh -c #(nop)  ENV GPG_KEYS=42670A7FE4D0…   0B
    <missing>      10 days ago   /bin/sh -c #(nop)  ENV PHP_LDFLAGS=-Wl,-O1 -…   0B
    <missing>      10 days ago   /bin/sh -c #(nop)  ENV PHP_CPPFLAGS=-fstack-…   0B
    <missing>      10 days ago   /bin/sh -c #(nop)  ENV PHP_CFLAGS=-fstack-pr…   0B
    <missing>      10 days ago   /bin/sh -c set -eux;  mkdir -p "$PHP_INI_DIR…   0B
    <missing>      10 days ago   /bin/sh -c #(nop)  ENV PHP_INI_DIR=/usr/loca…   0B
    <missing>      10 days ago   /bin/sh -c set -eux;  addgroup -g 82 -S www-…   4.68kB
    <missing>      10 days ago   /bin/sh -c apk add --no-cache   ca-certifica…   3.54MB
    <missing>      10 days ago   /bin/sh -c #(nop)  ENV PHPIZE_DEPS=autoconf …   0B
    <missing>      11 days ago   /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B
    <missing>      11 days ago   /bin/sh -c #(nop) ADD file:edbe213ae0c825a5b…   5.61MB
</details>

Checked [justinrainbow/json-schema](https://github.com/justinrainbow/json-schema) repo - line with deprecation notice [was updated ({0}->[0]) almost 4 years ago](https://github.com/justinrainbow/json-schema/commit/42c1043e1ca98978549b6f85c327b84a74e18abd#diff-ea1d86bbc290ec0718daade9efa2817153683acb07b74ef1dc513b977bb808d2L112) may be we should update `composer.lock`.

**Comment by alcohol** [comment]
That is an indirect dependency. That being said, I just ran a `composer update` and it did increase the package by 2 major versions :sweat_smile:

**Comment by alcohol** [comment]
Can you check if 95f3fb0 fixed it?

**Comment by rtm-ctrlz** [comment]
It work for me:
 - using docker image (updated)
 - deprecation notice - gone
 - `build` command works
 
Also I ran `php -l` (7.4.14) for every file in docker image `composer/satis` ( `/satis/` directory, including `vendor` ).
Everything is OK, `no syntax errors detected`.

There are some errors with `symfony/polyfill-*/bootstrap80.php` files, but they are used only with php8, so nothing to worry about.

**Comment by alcohol** [comment]
Thanks :-)
