### ISSUE TITLE
Rename default branch

### ISSUE THREAD

**Issue by theimbender** [composer/satis#633]
Hey I saw that a new `main` branch was created and made default, not sure if there was a reason to maintain a separate `master` branch any longer, if that's not the goal you may want to just delete the new `main` branch and [change the name of `master`](https://github.com/github/renaming) so that all requests like `git pull`s get forwarded to the new branch.

**Comment by alcohol** [comment]
Ah right I forgot Github forwards automatically. I branched from master and left it around because I figured I would give people time to switch. But with the forwarding that isn't necessary I guess.

**Comment by alcohol** [comment]
Wait, I'm not sure about forwarding branch renames. I believe Github only forwards repository name changes. Anyway, I did change the default branch already. But I deleted `master`.

**Comment by riordanp** [comment]
This change broke some of my CI jobs that install Satis in the CLI. 'dev-master' is no longer available via Packagist. I have proposed a change to the Readme to reflect this: https://github.com/composer/satis/pull/635
