### ISSUE TITLE
Docker hub image builds

### ISSUE THREAD

**Issue by klj613** [composer/satis#649]
Hi,

I was wondering what frequency the docker hub image is built? seems its 3 months old. https://hub.docker.com/r/composer/satis/tags?page=1&ordering=last_updated

Unsure if these are automated or manual, etc.

Thanks,
Kristian

**Comment by alcohol** [comment]
Well.. they used to be automated :thinking: 

Let me have a look..

**Comment by alcohol** [comment]
Meh, looks like hub builds are not working for reasons I cannot figure out right now.
I'll look into setting up a build and push workflow in Github actions tomorrow.

**Comment by alcohol** [comment]
For right now I pushed a current build of the `main` branch manually to docker hub.

**Comment by klj613** [comment]
Thank you :)

**Comment by alcohol** [comment]
`Docker` workflow added.
