### ISSUE TITLE
Local mirror using "require-dependencies" produces too many dependencies

### ISSUE THREAD

**Issue by Defcon0** [composer/satis#653]
Hello,

I've created a satis instance using `require-dependencies`:

```
{
    "name": "bacme/satis",
    "homepage": "http://php-bacme-b01.bacme.de",
    "archive": {
        "directory": "dist",
        "format": "zip",
        "skip-dev": true,
        "prefix-url": "https://php-bacme-b01.bacme.de"
    },
    "config": {
        "preferred-install": "dist",
        "disable-tls": true,
        "secure-http": false,
        "http-basic": {
            "satis-private.abc.com": {
                "username": "satis",
                "password": "sdfsdfsfd"
            }
        }
    },
    "require": {
        "abc/contao-acme-corporate-bundle": "^1.16.0"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packagist.org"
        },
        {
            "type": "composer",
            "url": "https://satis-private.abc.com"
        },
        {
            "type": "git",
            "url": "https://composer:abc@atl-bacme-b01.bacme.de:1234/scm/con/contao-acme-corporate-bundle.git"
        }
    ],
    "require-dependencies": true
}
```

Now my package `abc/contao-acme-corporate-bundle` requires a minimum of contao/core-bundle which is ^4.9. But also the package requires some modules which themselves allow contao/core-bundle ^4.4.

Now I would've expected that it won't also retrieve 4.4.1, 4.4.2, ... as these aren't allowed by the main package defined in my satis.json seen above but in fact it does.

Hence the resulting folder is no already about 30 GB large :-( Is there any way to prevent satis from loading these too old package versions? Specifying them in a black list is no option since it would be too many dependencies to define.

Thanks in advance for any tip!

Bye Defcon0

**Comment by GromNaN** [comment]
Hello @Defcon0, can you check if the bug persists after upgrading to the last version of satis. While upgrading to composer 2 I updated dependency resolution.

**Comment by GromNaN** [comment]
Hello @Defcon0, can you check if the bug persists after upgrading to the last version of satis. While upgrading to composer 2 I updated dependency resolution.

**Comment by Defcon0** [comment]
In fact, in my scenario, I needed to use an older version because of the limit to php 7.2. On SUSE with php 7.4, satis doesn't work because of the class ZipArchive which doesn't have a method ported in php-zip (can't remember which one, but it's something with "archive" I think).

**Comment by alcohol** [comment]
If it is at all possible in your situation, I would recommend running satis in Docker. It is quite simple and eliminates any host related PHP version issues.

**Comment by Defcon0** [comment]
You're right, this might be an option. But I understand it correctly, didn't I? The situation I described in the first post shouldn't happen, right? Of course, it might be fixed in the last version, but I just wanted to make sure, I understood `require` and `require-dependencies` correctly.

**Comment by alcohol** [comment]
I think your understanding is correct. Unfortunately we can only support the latest version, and even then, support is very limited and mostly depends on the community/users.

**Comment by Defcon0** [comment]
I understand that. I'll give docker a try if suse doesn't fix their repo.

But maybe it would be an option to remove the ZipArchive-method or replace it by a function existing in the suse package (php74-zip)?

**Comment by GromNaN** [comment]
The `ZipArchive` issue might by solved by installing `unzip`. https://github.com/composer/composer/blob/4c9e75c6e58fbef6c58f44debfa77f5fae8a2c1c/src/Composer/Downloader/ZipDownloader.php#L46

**Comment by Defcon0** [comment]
I can try. But I don't think, it's the problem.

Meanwhile I found the line which causes the problems:

https://github.com/composer/composer/blob/4c9e75c6e58fbef6c58f44debfa77f5fae8a2c1c/src/Composer/Package/Archiver/ZipArchiver.php#L61

The method `setExternalAttributesName()` simply doesn't exist in suse's php 7.4 zip module :-(

**Comment by alcohol** [comment]
That seems like an odd patch/modification.

https://www.php.net/manual/en/class.ziparchive.php definitely describes it as part of the interface.

Unfortunately I can find little information about SUSE's packaging method for php. So without knowing where the php package you are installing comes from, it is hard to figure out what exactly is wrong here.

> But maybe it would be an option to remove the ZipArchive-method or replace it by a function existing in the suse package (php74-zip)?

As we are talking about `composer/composer` core code here, that is definitely not an option. Docker really is your best alternative here I think.

**Comment by Defcon0** [comment]
Installed is SUSE Linux Enterprise Server 12 SP4 with the packages php74 and lots of extensions including php74-zip.

**Comment by alcohol** [comment]
Ah.. unfortunately I do not have access to any SLES machines nor was I able to find any docker images that offer said distro (I assume it is a paid version?).

On the latest OpenSUSE (Leap, 15.2) it does exist:

```
$ docker run --rm -it opensuse/leap sh
Unable to find image 'opensuse/leap:latest' locally
latest: Pulling from opensuse/leap
9314d5c70559: Pull complete 
Digest: sha256:404e7905fd124eb9f101bc26bd90410e03ec1d16d3428b4f6a5924e5b2218a47
Status: Downloaded newer image for opensuse/leap:latest

sh-4.4# zypper install php7-zip
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 7 NEW packages are going to be installed:
  libargon2-1 libpcre2-8-0 libzip5 php7 php7-zip system-user-wwwrun timezone

7 new packages to install.
Overall download size: 2.4 MiB. Already cached: 0 B. After the operation, additional 12.3 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): 
Retrieving package libargon2-1-0.0+git20171227.670229c-2.14.x86_64                                                                      (1/7),  19.9 KiB ( 30.2 KiB unpacked)
Retrieving: libargon2-1-0.0+git20171227.670229c-2.14.x86_64.rpm .......................................................................................................[done]
Retrieving package libpcre2-8-0-10.31-1.14.x86_64                                                                                       (2/7), 235.5 KiB (648.0 KiB unpacked)
Retrieving: libpcre2-8-0-10.31-1.14.x86_64.rpm ........................................................................................................................[done]
Retrieving package libzip5-1.5.1-1.9.x86_64                                                                                             (3/7),  57.3 KiB ( 99.7 KiB unpacked)
Retrieving: libzip5-1.5.1-1.9.x86_64.rpm ..............................................................................................................................[done]
Retrieving package system-user-wwwrun-20170617-15.86.noarch                                                                             (4/7),  11.5 KiB (   96   B unpacked)
Retrieving: system-user-wwwrun-20170617-15.86.noarch.rpm ..............................................................................................................[done]
Retrieving package timezone-2021a-3.44.1.x86_64                                                                                         (5/7), 418.3 KiB (  1.2 MiB unpacked)
Retrieving: timezone-2021a-3.44.1.x86_64.rpm ..........................................................................................................................[done]
Retrieving package php7-7.4.6-3.17.1.x86_64                                                                                             (6/7),   1.6 MiB ( 10.3 MiB unpacked)
Retrieving: php7-7.4.6-3.17.1.x86_64.rpm ..............................................................................................................................[done]
Retrieving package php7-zip-7.4.6-3.17.1.x86_64                                                                                         (7/7),  54.4 KiB ( 63.3 KiB unpacked)
Retrieving: php7-zip-7.4.6-3.17.1.x86_64.rpm ..........................................................................................................................[done]

Checking for file conflicts: ..........................................................................................................................................[done]
(1/7) Installing: libargon2-1-0.0+git20171227.670229c-2.14.x86_64 .....................................................................................................[done]
(2/7) Installing: libpcre2-8-0-10.31-1.14.x86_64 ......................................................................................................................[done]
(3/7) Installing: libzip5-1.5.1-1.9.x86_64 ............................................................................................................................[done]
(4/7) Installing: system-user-wwwrun-20170617-15.86.noarch ............................................................................................................[done]
Additional rpm output:
groupadd -r www
useradd -r -s /sbin/nologin -c "WWW daemon apache" -U -d /var/lib/wwwrun wwwrun
usermod -a -G www wwwrun


(5/7) Installing: timezone-2021a-3.44.1.x86_64 ........................................................................................................................[done]
(6/7) Installing: php7-7.4.6-3.17.1.x86_64 ............................................................................................................................[done]
(7/7) Installing: php7-zip-7.4.6-3.17.1.x86_64 ........................................................................................................................[done]

sh-4.4# php -v
PHP 7.4.6 (cli) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

sh-4.4# php -r "var_dump(method_exists((new ZipArchive()), 'setExternalAttributesName'));"
bool(true)
```

**Comment by Defcon0** [comment]
I also think it's paid. OK, thanks for your help!

**Comment by SvenRtbg** [comment]
I investigated this exact problem. The reason is that the ZIP extension will only provide said method if "libzip" is installed in version 0.11.2 or higher. SLES only provides 0.11.1.

Composer has no way to express such kind of dependencies anyways, and even if it could, would only be able to depend on "ext-zip" in a certain version, without any chance to identify that this extension dynamically limits it's interface based on installed system libraries.

This is just bad luck, but I can feel the pain.

**Comment by Defcon0** [comment]
Too bad, but big thanks for investigating! Maybe SLES provides a higher version in the future.

**Comment by alcohol** [comment]
@SvenRtbg That is an amazing find! Thanks a lot for spending more time on this, it is really appreciated :-)
