### ISSUE TITLE
This is a long file name to just check how the fileinput plugin can autosize the file caption displayed across device sizes.jpg

### ISSUE THREAD

**Issue by hannius** [composer/satis#663]
hello, when i update the latest  satis docker image, i get the error: 
```
In PharArchiver.php line 58:

[PharException]
tar-based phar "/tmp/composer_archive61039adb8c2d8.tar" cannot be created,
filename "examples/This is a long file name to just check how the fileinput
plugin can autosize the file caption displayed across device sizes.jpg" is
too long for tar file format
```

And the detailed information picture is below:

![image](https://user-images.githubusercontent.com/18302266/127611865-e8d4d355-3a6a-44a9-9731-401bcd2f8e5b.png)

Could you pls help me to solve the problem, tks very much.

**Comment by SvenRtbg** [comment]
Shorten the filename. As you can read, the TAR file format does not support the length, this isn't something Satis can change.

If you'd be able to create a TAR with this file inside independent from Satis, you would have a case here. Have you tried that?

**Comment by alcohol** [comment]
I think this is related to Composer v2 being more strict/safe in this context. Not much we can do about this.

**Comment by alcohol** [comment]
Have you tried forcing Satis to use zip instead of tar for archives?

**Comment by hannius** [comment]
Thanks very much , you are right, this is the problem of tar , it has been resloved using zip instead of tar, @SvenRtbg @alcohol
