### ISSUE TITLE
Broken archive download if rearchive is false.

### ISSUE THREAD

**Issue by MadHacker666** [composer/satis#671]
Branch: master
If the "rearchive" option is disabled, a problem arises when loading the archive - the file does not exist.
The problem occurs here: 
https://github.com/composer/satis/blob/ed58c8c922029f201814ba3dbcb3e0879e0e9f7c/src/Builder/ArchiveBuilder.php#L200
In the current implementation, the method returns a promise and the file has not been downloaded yet at the time the method returns. Also, the current implementation ignores the download directory and saves the file in composer dir.
As a result, the code of the method that downloads files without an rearchive is completely incorrect.
As a temporary measure, I use a stub to place the file in the correct path: 

```
Index: src/Builder/ArchiveBuilder.php
comment: !!STUB CODE. Not for production.
<+>UTF-8
===================================================================
diff --git a/src/Builder/ArchiveBuilder.php b/src/Builder/ArchiveBuilder.php
--- a/src/Builder/ArchiveBuilder.php	(revision ed58c8c922029f201814ba3dbcb3e0879e0e9f7c)
+++ b/src/Builder/ArchiveBuilder.php	(date 1631174127017)
@@ -21,6 +21,7 @@
 use Composer\Package\CompletePackageInterface;
 use Composer\Package\PackageInterface;
 use Composer\Util\Filesystem;
+use Composer\Util\SyncHelper;
 use Symfony\Component\Console\Helper\ProgressBar;
 use Symfony\Component\Console\Input\InputInterface;
 use Symfony\Component\Console\Output\OutputInterface;
@@ -197,10 +198,12 @@
             $downloadDir = sys_get_temp_dir() . '/composer_archiver' . uniqid();
             $filesystem->ensureDirectoryExists($downloadDir);
             $downloader = $downloadManager->getDownloader('file');
-            $downloader->download($package, $downloadDir);
-
-            $filesystem->ensureDirectoryExists(dirname($path));
-            $filesystem->rename($downloadDir . '/' . pathinfo($package->getDistUrl(), PATHINFO_BASENAME), $path);
+            $downloadPromise = $downloader->download($package, $downloadDir);
+            $downloadPromise->then(function ($filename) use ($path, $filesystem) {
+                $filesystem->ensureDirectoryExists(dirname($path));
+                $filesystem->rename($filename, $path);
+            });
+            SyncHelper::await($this->composer->getLoop(), $downloadPromise);
             $filesystem->removeDirectory($downloadDir);
 
             return $path;
```

**Comment by alcohol** [comment]
Curious, why not submit a PR if you have already found a fix for the issue?

**Comment by MadHacker666** [comment]
This is not a solution to the problem. This is a stub for the program to do what I need.
I am not a php developer. I cannot be sure that this is a satis problem and not a composer. I have defined the problem as far as my competencies allow me and I hope that this will help to fix it quickly.

**Comment by alcohol** [comment]
Fair enough.
