### ISSUE TITLE
Downloaded packages have incorrect file modification timestamps

### ISSUE THREAD

**Issue by thomasfw** [composer/satis#715]
### Describe the bug

When downloading mirrored package releases from our satis repo, the resulting unzipped files have a modified time of `Tuesday, 1 January 1980 at 00:00`.

This is causing a bit of a headache for us, specifically where our packages are providing [Blade](https://laravel.com/docs/10.x/blade) template files. The Blade engine fails to pick up template changes because the file modification times are incorrect.

I've also manually downloaded a few different releases from satis and confirmed that the modified times are incorrect. So I don't think this is something Composer is doing on the production server, or something specific to those environments.

When I download a release directly from GitHub, the file modification time is set to the time of the tagged release as it should be.

### To Reproduce

🤷‍♂️ ... maybe somebody can download a _mirrored_ package release (ideally with GitHub as the source) from their satis repo and check the file modification times match the release's date?

### Outcome

N/A

### Expected behavior

The file modification times should be set to the time of the tagged release. I also realise that the cause of this might not be satis but this is the first port of call.

### Additional context

We've been using our satis repo for a few years and haven't run into this issue up until now. We did recently switch all of our private repos from BitBucket to Github, and updated the packages in our `satis.json` to use the new sources.

**Comment by thomasfw** [comment]
I've been digging into this a bit more... I see that there's an undocumented (or at least it isn't mentioned [in the official docs](https://getcomposer.org/doc/articles/handling-private-packages.md)) `archive.rearchive` option which is enabled by default. 

**Having disabled this, ~98% of the zip archives now contain the correct timestamps.** 

The other ~2% of the archived releases still contain incorrect timestamps for some inexplicable reason. I can only assume this is something to do with [the package's dist type causing the `archive.rearchive` config option to be overridden](https://github.com/composer/satis/blob/04a4956ed3fb4ae792a2bbc7647217bfc498abf1/src/Builder/ArchiveBuilder.php#L188). Once unzipped, the archives with the incorrect timestamps spit out a directory with a different naming convention to the (non re-archived) ones with correct timestamps, which also suggests to me that they are indeed being re-archived and that this is the cause of the issue.  

Are there any cases where a package dist type might not be `tar` or `zip`, thus forcing the re-archiving? 

What is the reason for re-archiving anyway? I see that satis is using [`Composer\Package\Archiver\ArchiveManager::archive()`](https://github.com/composer/composer/blob/ecb69eaa4aec3c2bd866d17ee7a46e684dc16f71/src/Composer/Package/Archiver/ArchiveManager.php#L146) for this. In which case it looks like I need to open an issue up there, so that the timestamps are preserved.

Thoughts on this from satis maintainers would be much appreciated.

**Comment by thomasfw** [comment]
@alcohol Hi, it would appear that there are issues setting mtime on files archived using [`ZipArchive`](https://www.php.net/manual/en/class.ziparchive.php) in php `<8`. Do you have any ideas for how this could be fixed in Satis? 

Considering the outcome of the discussion in  https://github.com/composer/composer/issues/11342, it seems to me that bumping Satis' minimum php version to 8 and also checking for the `ext-zip` extension might be the best (and least time consuming) solution.

```json
{
    "require": {
        "php": "^8.0",
        "ext-zip": "*"
    }
}
```

**Comment by alcohol** [comment]
Done via [bab7ca3](https://github.com/composer/satis/commit/bab7ca325c1227eaed364597ea720905c62b066e). The container release artifact of `satis` includes said necessary extensions. Git clone users might be less happy about this implementation, but c'est la vie :shrug:

**Comment by thomasfw** [comment]
Great, thanks 🙂
