### ISSUE TITLE
Release stable (i.e. 3.x) branch for pre-mbstring era

### ISSUE THREAD

**Issue by igronus** [composer/satis#732]
Hi all,

Just noticed it's not easy to update the satis on one of our Ubuntu 18.04 servers since the `ext-mbstring` was added to the requirements. It's not so trivial to install it there since it's now not available in repos. Sure it can always be done manually one way or another and/or with paid support and depends on your distro and company policies (our case) of course.

But anyway I guess a lot of systems is affected by this change so as far as I understand the same happened when `2.x` was created on a commit just before the dependencies update.

So I suggest creating a new branch like `3.x` for some state of the project before the mbstring was added. I think the `edf8c0e` commit from 2023-04-14 would be the best for that.

**Comment by alcohol** [comment]
To be honest, I am not sure why we added it... as far as I can tell right now, Satis itself makes no use of any of the functions that the `mbstring` extension provides. Composer uses it, but optionally, and only if available. Might need to double check, but I think that requirement can be removed.

**Comment by alcohol** [comment]
Adjusted in https://github.com/composer/satis/commit/6e7160fcaa4d2cdef55e0eea850480815fe1297b
