### ISSUE TITLE
RuntimeException "Package could not be downloaded, svn: Impossible to get login or passord"

### ISSUE THREAD

**Issue by bricev** [composer/satis#82]
Hi all,

I've got a strange exception thrown from a simple `php ./composer.phar install` command on a composer.json that I use successfully on many other servers.

The composer.json looks like this:
```json
{
    "name": "xxx/yyy",
    "description": "Install some stuff",
    "license": "MIT",
    "minimum-stability": "dev",
    "repositories": [
        { "type": "composer", "url": "http://satis.my_corp.com" }
    ],
    "require": {
        "xxx/zzz": "dev-trunk"
    }
}
```

Where xxx/zzz is a SVN repository that I've successfull checked out on the very same server! 

The SVN credentials **are registered on the server**. 

I've tried to clean all files under ~/.subversion/auth/svn.simple/* and checkout again the SVN repository: I was successfully prompted for login/password that I chose to store in local cache. But that doesn't solve the problem...

Whatever I do, each time I perform a `php ./composer.phar install` or `update` on my project, I have the same RuntimeException!

Please help me understand :)

**Comment by alcohol** [comment]
Closing due to time since opened, please re-open if needed though.
