### ISSUE TITLE
ghcr.io image set to private

### ISSUE THREAD

**Issue by computator** [composer/satis#912]
It appears as if the documented `ghcr.io/composer/satis` image is set to private. I can see that it's being created and pushed from the [`docker` GitHub Action](https://github.com/composer/satis/blob/ad399a68cafaf81d311f973f9faa140a504f4e29/.github/workflows/docker.yaml) and it's logs, but I can't access the image either by pulling it or through the GitHub Web UI.

**Comment by alcohol** [comment]
So it seems indeed, but alas I am not able to change this configuration myself. I will ask @Seldaek if he can and is willing to change this.

**Comment by alcohol** [comment]
Resolved.
